### PR TITLE
fix copied doc updates not insert

### PR DESCRIPTION
**Pull request by swheaton**
## What changes are proposed in this pull request?

Another weird bug that doesn't cause issues really until to-come changes are introduced.

If you do this code (done 3 times with dataset clone)
```python
doc_copy = doc.copy()
_id = bson.ObjectId()
doc_copy.id = _id
```
Then `mongoengine` sets `_created` to `False` which means it thinks it's an update object not a new one.
When you call `save()` it emits an upsert call instead of an insert.
OK, not so bad, maybe a little weird but whatever ...

But in https://github.com/voxel51/fiftyone/pull/4597 @brimoor proposes an optimization where only changed fields are serialized to get the document. In combo, this causes all kinds of strange behavior. It just so happens to work in that PR because `doc._changed_fields` is uninitialized (a code smell in mongoengine, they have a [TODO](https://github.com/MongoEngine/mongoengine/blob/master/mongoengine/base/document.py#L40) to clean it up...) and so `doc._delta()` returns the whole doc.

But say we cleared changed fields because we didn't know about this strange requirement.
```python
import bson
import fiftyone.core.odm as foo

run_doc = foo.RunDocument(config={"foo": "bar"})
run_doc.save()
doc_copy = run_doc.copy()
doc_copy.id = bson.ObjectId()

doc_copy._clear_changed_fields()
doc_copy.version = "51.51"
print(doc_copy._get_changed_fields()  # ["version"]
doc_copy.save(upsert=True)
doc_copy.reload()

# Oops our config field is {} because it's not a changed field so update only wrote "version" field
assert doc_copy.config == {"foo": "bar"}

doc_copy.delete()
run_doc.delete()
```

Ok but we don't clear changed_field so we're fine? Nope, balancing on a thread due to another mongoengine weirdness where `_get_changed_fields()` can return something due to embedded documents being edited

```python
import bson
import fiftyone as fo

ds = fo.Dataset()

# Pretending to clone the dataset doc
doc_copy = ds._doc.copy()
doc_copy.id = bson.ObjectId()
doc_copy.sample_collection_name=f"samples.{str(doc_copy.id)}"
doc_copy.name="blah"
doc_copy.slug="blah"

# Making an embedded document update
doc_copy.sample_fields[0].description = "blah"

# Wha? changed fields is actually ["sample_fields.0.description"] because
#  simple fields aren't tracked but embedded docs are
assert doc_copy._get_changed_fields() == []

ds.delete()
doc_copy.delete()
```

In mongoengine code, this appears to be band-aided with [this](https://github.com/MongoEngine/mongoengine/blob/master/mongoengine/base/document.py#L692):
which is what @brimoor 's optimization is trying to avoid
```
        # Handles cases where not loaded from_son but has _id
        doc = self.to_mongo()
```

## How is this patch tested? If it is not, please explain why.

Added test for `copy_with_new_id`.

Ensured that cloning dataset uses INSERT methods not UPSERT. Added print in `Document._save()`
```python
import fiftyone as fo

ds = fo.Dataset()
ds.clone("blah")

$$ INSERT SON([('_id', ObjectId('66cc999093e25d6a662346e4')), ('name', 'blah'), ('slug', 'blah'), ('version', '0.24.1'), ('created_at', datetime.datetime(2024, 8, 26, 15, 4, 48, 474872)), ('sample_collection_name', 'samples.66cc999093e25d6a662346e4'), ('persistent', False), ('group_media_types', {}), ('tags', []), ('info', {}), ('app_config', SON([('grid_media_field', 'filepath'), ('media_fallback', False), ('media_fields', ['filepath']), ('modal_media_field', 'filepath'), ('plugins', {})])), ('classes', {}), ('default_classes', []), ('mask_targets', {}), ('default_mask_targets', {}), ('skeletons', {}), ('sample_fields', [SON([('name', 'id'), ('ftype', 'fiftyone.core.fields.ObjectIdField'), ('embedded_doc_type', None), ('subfield', None), ('fields', []), ('db_field', '_id'), ('description', None), ('info', None)]), SON([('name', 'filepath'), ('ftype', 'fiftyone.core.fields.StringField'), ('embedded_doc_type', None), ('subfield', None), ('fields', []), ('db_field', 'filepath'), ('description', None), ('info', None)]), SON([('name', 'tags'), ('ftype', 'fiftyone.core.fields.ListField'), ('embedded_doc_type', None), ('subfield', 'fiftyone.core.fields.StringField'), ('fields', []), ('db_field', 'tags'), ('description', None), ('info', None)]), SON([('name', 'metadata'), ('ftype', 'fiftyone.core.fields.EmbeddedDocumentField'), ('embedded_doc_type', 'fiftyone.core.metadata.Metadata'), ('subfield', None), ('fields', [SON([('name', 'size_bytes'), ('ftype', 'fiftyone.core.fields.IntField'), ('embedded_doc_type', None), ('subfield', None), ('fields', []), ('db_field', 'size_bytes'), ('description', None), ('info', None)]), SON([('name', 'mime_type'), ('ftype', 'fiftyone.core.fields.StringField'), ('embedded_doc_type', None), ('subfield', None), ('fields', []), ('db_field', 'mime_type'), ('description', None), ('info', None)])]), ('db_field', 'metadata'), ('description', None), ('info', None)]), SON([('name', '_media_type'), ('ftype', 'fiftyone.core.fields.StringField'), ('embedded_doc_type', None), ('subfield', None), ('fields', []), ('db_field', '_media_type'), ('description', None), ('info', None)]), SON([('name', '_rand'), ('ftype', 'fiftyone.core.fields.FloatField'), ('embedded_doc_type', None), ('subfield', None), ('fields', []), ('db_field', '_rand'), ('description', None), ('info', None)]), SON([('name', '_dataset_id'), ('ftype', 'fiftyone.core.fields.ObjectIdField'), ('embedded_doc_type', None), ('subfield', None), ('fields', []), ('db_field', '_dataset_id'), ('description', None), ('info', None)])]), ('frame_fields', []), ('saved_views', []), ('workspaces', []), ('annotation_runs', {}), ('brain_methods', {}), ('evaluations', {}), ('runs', {})])

^^UPDATES {'$set': {'last_loaded_at': datetime.datetime(2024, 8, 26, 15, 4, 48, 625081)}}
```

Previously,
```
^^UPDATES {'$set': SON([('name', 'blah2'), ('slug', 'blah2'), ('version', '0.24.1'), ('created_at', datetime.datetime(2024, 8, 26, 15, 7, 4, 166390)), ('sample_collection_name', 'samples.66cc9a1861678cf7500272b4'), ('persistent', False), ('app_config', SON([('grid_media_field', 'filepath'), ('media_fallback', False), ('media_fields', ['filepath']), ('modal_media_field', 'filepath'), ('plugins', {})])), ('sample_fields', [SON([('name', 'id'), ('ftype', 'fiftyone.core.fields.ObjectIdField'), ('embedded_doc_type', None), ('subfield', None), ('fields', []), ('db_field', '_id'), ('description', None), ('info', None)]), SON([('name', 'filepath'), ('ftype', 'fiftyone.core.fields.StringField'), ('embedded_doc_type', None), ('subfield', None), ('fields', []), ('db_field', 'filepath'), ('description', None), ('info', None)]), SON([('name', 'tags'), ('ftype', 'fiftyone.core.fields.ListField'), ('embedded_doc_type', None), ('subfield', 'fiftyone.core.fields.StringField'), ('fields', []), ('db_field', 'tags'), ('description', None), ('info', None)]), SON([('name', 'metadata'), ('ftype', 'fiftyone.core.fields.EmbeddedDocumentField'), ('embedded_doc_type', 'fiftyone.core.metadata.Metadata'), ('subfield', None), ('fields', [SON([('name', 'size_bytes'), ('ftype', 'fiftyone.core.fields.IntField'), ('embedded_doc_type', None), ('subfield', None), ('fields', []), ('db_field', 'size_bytes'), ('description', None), ('info', None)]), SON([('name', 'mime_type'), ('ftype', 'fiftyone.core.fields.StringField'), ('embedded_doc_type', None), ('subfield', None), ('fields', []), ('db_field', 'mime_type'), ('description', None), ('info', None)])]), ('db_field', 'metadata'), ('description', None), ('info', None)]), SON([('name', '_media_type'), ('ftype', 'fiftyone.core.fields.StringField'), ('embedded_doc_type', None), ('subfield', None), ('fields', []), ('db_field', '_media_type'), ('description', None), ('info', None)]), SON([('name', '_rand'), ('ftype', 'fiftyone.core.fields.FloatField'), ('embedded_doc_type', None), ('subfield', None), ('fields', []), ('db_field', '_rand'), ('description', None), ('info', None)]), SON([('name', '_dataset_id'), ('ftype', 'fiftyone.core.fields.ObjectIdField'), ('embedded_doc_type', None), ('subfield', None), ('fields', []), ('db_field', '_dataset_id'), ('description', None), ('info', None)])])]), '$unset': {'group_media_types': 1, 'tags': 1, 'info': 1, 'classes': 1, 'default_classes': 1, 'mask_targets': 1, 'default_mask_targets': 1, 'skeletons': 1, 'frame_fields': 1, 'saved_views': 1, 'workspaces': 1, 'annotation_runs': 1, 'brain_methods': 1, 'evaluations': 1, 'runs': 1}}

^^UPDATES {'$set': {'last_loaded_at': datetime.datetime(2024, 8, 26, 15, 7, 4, 291793)}}
```

## Summary by CodeRabbit

- **New Features**
	- Introduced a method to duplicate documents with a new unique identifier, enhancing document management.

- **Bug Fixes**
	- Improved ID generation for copied documents, reducing potential errors and improving maintainability.

- **Tests**
	- Added new tests to ensure the functionality of copying documents with new IDs works as intended.

### CODE REVIEW

**Comment by benjaminpkane** [comment]
Nice find. Odd and opaque behavior.

It makes sense to me. Trying to grok things a bit...we still like regular `copy()` for other use cases? And this only impacts documents (not embedded documents, e.g. labels), correct?

Thinking out loud, what about a `doc.copy(new_id=False)` signature?

**Comment by brimoor** [comment]
@swheaton +1 to both of @benjaminpkane's thoughts here:
- Still trying to fully grok the implications of what you've found here. Are the other places where we use `copy()` okay?
- I like folding this into a `copy(new_id=True)` syntax. Or, another option could be `clone()`, since when you `dataset.clone()` you're creating an identical but fully-independent copy of the dataset (with a new dataset ID).

But, I'm now wondering if we ever use `copy()` for the purposes of making edits to a doc that we intend to upsert in-place... 🤔 

Okay, here's an interesting bit of code when dealing with embedded docs:
https://github.com/voxel51/fiftyone/blob/c9cfc0589471358498a97ad3e7860a02b480fd7a/fiftyone/utils/eval/coco.py#L770-L781

The use case here is that we actually want a copy of the embedded docs with the same IDs because we intend to do in-memory computations on them but don't want the stuff we do to be tracked and persisted on the label objects in the database. Annnnd, this reminds me that apparently `foo.EmbeddedDocument.copy()` does not behave the same as `foo.Document.copy()`, it creates a new ID by default!

```py
d = fo.Detection()
assert d.id == d.copy().id  # False!
```

And then there's `fiftyone.core.document.Document.copy()`, which does a third thing: it explicitly returns a document with `id == None`:
https://github.com/voxel51/fiftyone/blob/c9cfc0589471358498a97ad3e7860a02b480fd7a/fiftyone/core/document.py#L376-L390

**Comment by swheaton** [comment]
Somehow I missed the emails of these reviews coming in ...

Good ideas, I didn't love `copy_with_new_id` anyways.

`foo.Document` does behave that same way, copying resets the ID to `None`. It's just that in our clone_* implementations we want to know the ID before saving so that we can create sample collection name and set up references and stuff. So we don't just leave the ID as `None` which would cause an insert and new ID generated in the _normal_ way.

But yes embedded document is different, not sure why exactly. But I don't see any further bugs due to this.

**Comment by swheaton** [comment]
changed to `copy(new_id=False)`

**Review by brimoor — APPROVED** [review]
LGTM

**Pull request merged**
