### PR TITLE
Allow clearing hidden objects in filter widgets

### LINKED ISSUE #644: Move hidden objects into label filters
The ability to click -> hide labels introduced in #637 is super useful. However, it's a bit confusing for information about hidden labels to be silently stored under the selected objects dropdown, with no visual indication that some labels may currently be hidden. I think a good solution for this is to store information about *hidden* labels within the label filter dropdown for the associated label field. EG if I click on some boxes and then select a hide option, the corresponding label filters will "activate" (light gray background) and when I expand the filters, I'll see a new section that looks similar to this:

```
Manual
[2 hidden x]

Labels
[+ add label]

Confidence
[[slider]]
``` 

I can then click the `x` on a per-label-field basis to unhide any manually hidden labels.

It's slightly more complex to implement this way, but I think it makes it very clear to the user what is happening.

Thoughts?

_Originally posted by @brimoor in https://github.com/voxel51/fiftyone/pull/637#issuecomment-717676090_

### PR DESCRIPTION
**Pull request by lethosor**
## What changes are proposed in this pull request?

Closes #644 

image

The only thing left is to highlight the relevant filters when this control is available - @benjaminpkane what controls that color?

### Is this a user-facing change that should be mentioned in the release notes?

Extension of #637

### What areas of FiftyOne does this PR affect?

-   [x] App: FiftyOne application changes
-   [ ] Build: Build and test infrastructure changes
-   [ ] Core: Core `fiftyone` Python library changes
-   [ ] Documentation: FiftyOne documentation changes
-   [ ] Other

### CODE REVIEW

**Comment by benjaminpkane** [comment]
The activated filter background comes from the `modalFieldIsFiltered`.

https://github.com/voxel51/fiftyone/blob/2d0515f947c5d4a7bcbdd90038db3acd5940daa7/electron/app/recoil/selectors.ts#L259

**Comment by lethosor** [comment]
Thanks! I tracked the source of the color down to CheckboxGrid and implemented a fix there. Should be good to go now.

**Comment by lethosor** [comment]
(Feel free to merge once tests pass and it looks okay)

**Review by benjaminpkane — APPROVED** [review]
:+1:

**Pull request merged**
