### PR TITLE
Model inference/embeddings enhancements

### PR DESCRIPTION
**Pull request by brimoor**
Resolves https://github.com/voxel51/fiftyone/issues/1442.

Change log
- Resolves https://github.com/voxel51/fiftyone/issues/1442 by ensuring that `TorchImageDataset`, `TorchImageClassificationDataset`, and `TorchImagePatchesDataset` use numpy data structures that can be shared between processes rather than large in-memory Python lists that will be wastefully copied between workers
- Adds `samples.select_fields()` to the `apply_model()`, `compute_embeddings()`, and `compute_patch_embeddings()` routines. This can significantly improve DB I/O performance when applying models to datasets with many existing fields (loading existing fields is not needed to run inference)
- Updates the errors/warnings in `apply_model()`, `compute_embeddings()`, and `compute_patch_embeddings()` to explicitly include the IDs of the offending samples for easier debugging 

Mea culpa I haven't gotten around to creating proper unit tests for expensive things like applying models, so I tested this by just running this code from last time I worked on models...

## Test graceful failures when applying models

```py
import fiftyone as fo
import fiftyone.zoo as foz

dataset = foz.load_zoo_dataset("quickstart")
dataset = dataset.select_fields("ground_truth").limit(3).clone()

dataset.add_samples(
    [
        fo.Sample(filepath="non-existent1.png"),
        fo.Sample(filepath="non-existent2.png"),
        fo.Sample(filepath="non-existent3.png"),
        fo.Sample(filepath="non-existent4.png"),
    ]
)

# Inference

# torch, data loader single batches
model = foz.load_zoo_model("inception-v3-imagenet-torch")
dataset.apply_model(model, "predictions1")
print(dataset.values("predictions1"))

# torch, data loader batches
model = foz.load_zoo_model("inception-v3-imagenet-torch")
dataset.apply_model(model, "predictions2", batch_size=2)
print(dataset.values("predictions2"))

# TF, single inference
model = foz.load_zoo_model("ssd-mobilenet-v1-coco-tf")
dataset.apply_model(model, "predictions3")
print(dataset.values("predictions3"))

# TF, batch inference (TF1 only)
model = foz.load_zoo_model("resnet-v2-50-imagenet-tf1")
dataset.apply_model(model, "predictions4", batch_size=2)
print(dataset.values("predictions4"))

# Compute embeddings

# torch, data loader single batches
model = foz.load_zoo_model("inception-v3-imagenet-torch")
embeddings = dataset.compute_embeddings(model)
print(embeddings)

# torch, data loader batches
model = foz.load_zoo_model("inception-v3-imagenet-torch")
embeddings = dataset.compute_embeddings(model, batch_size=2)
print(embeddings)

# TF, batch inference (TF1 only)
model = foz.load_zoo_model("resnet-v2-50-imagenet-tf1")
embeddings = dataset.compute_embeddings(model, batch_size=2)
print(embeddings)

# Compute patch embeddings

for sample in dataset:
    if sample["ground_truth"] is None:
        sample["ground_truth"] = fo.Detections(
            detections=[fo.Detection(bounding_box=[0.1, 0.1, 0.8, 0.8])]
        )
        sample.save()

# torch, data loader single batches
model = foz.load_zoo_model("inception-v3-imagenet-torch")
embeddings = dataset.compute_patch_embeddings(model, "ground_truth")
print(embeddings)

# torch, data loader batches
model = foz.load_zoo_model("inception-v3-imagenet-torch")
embeddings = dataset.compute_patch_embeddings(model, "ground_truth", batch_size=2)
print(embeddings)

# TF, batch inference (TF1 only)
model = foz.load_zoo_model("resnet-v2-50-imagenet-tf1")
embeddings = dataset.compute_patch_embeddings(model, "ground_truth", batch_size=2)
print(embeddings)
```

## Test applying image models to video frames

```py
import numpy as np

import fiftyone as fo
import fiftyone.zoo as foz

dataset = foz.load_zoo_dataset("quickstart-video").clone()

view = dataset.take(1)

# Model inference

model = foz.load_zoo_model("inception-v3-imagenet-torch")
view.apply_model(model, "imagenet_preds", batch_size=8)
print(view.count_values("frames.imagenet_preds.label"))

model = foz.load_zoo_model("ssd-mobilenet-v1-coco-tf")
view.apply_model(model, "coco_preds")
print(view.count_values("frames.coco_preds.detections.label"))

# Frame embeddings

model = foz.load_zoo_model("mobilenet-v2-imagenet-tf1")

embeddings1 = view.compute_embeddings(model)

view.compute_embeddings(model, embeddings_field="embeddings1")
embeddings1b = {
    _id: np.stack(e)
    for _id, e in zip(view.values("id"), view.values("frames.embeddings1"))
}

embeddings2 = view.compute_embeddings(model, batch_size=8)

view.compute_embeddings(model, embeddings_field="embeddings2", batch_size=8)
embeddings2b = {
    _id: np.stack(e)
    for _id, e in zip(view.values("id"), view.values("frames.embeddings2"))
}

# Frame patch embeddings

model = foz.load_zoo_model("mobilenet-v2-imagenet-tf1")

patch_embeddings1 = view.compute_patch_embeddings(
    model, "frames.detections"
)

view.compute_patch_embeddings(
    model, "frames.detections", embeddings_field="patch_embeddings1"
)
patch_embeddings1b = {
    _id: {fn: p for fn, p in enumerate(e, 1)}
    for _id, e in zip(
        view.values("id"), view.values("frames.patch_embeddings1")
    )
}

patch_embeddings2 = view.compute_patch_embeddings(
    model, "frames.detections", batch_size=8
)

view.compute_patch_embeddings(
    model, "frames.detections", embeddings_field="patch_embeddings2"
)
patch_embeddings2b = {
    _id: {fn: p for fn, p in enumerate(e, 1)}
    for _id, e in zip(
        view.values("id"), view.values("frames.patch_embeddings2")
    )
}
```

### CODE REVIEW

**Comment by brimoor** [comment]
@ehofesmann I believe the changes to the Torch datasets in this PR as motivated by https://github.com/voxel51/fiftyone/issues/1442 would also be nice to port over to our Lightning Flash integration to avoid the same memory leaks over there.

**Comment by ehofesmann** [comment]
> @ehofesmann I believe the changes to the Torch datasets in this PR as motivated by #1442 would also be nice to port over to our Lightning Flash integration to avoid the same memory leaks over there.

The Lightning Flash implementation for all of the data loaders uses Python lists so I'm not sure that it would make much sense for our FiftyOne loaders to incorporate NumPy arrays.

**Comment by brimoor** [comment]
> > @ehofesmann I believe the changes to the Torch datasets in this PR as motivated by #1442 would also be nice to port over to our Lightning Flash integration to avoid the same memory leaks over there.
> 
> The Lightning Flash implementation for all of the data loaders uses Python lists so I'm not sure that it would make much sense for our FiftyOne loaders to incorporate NumPy arrays.

What are your thoughts on https://github.com/pytorch/pytorch/issues/13246#issuecomment-436632186 from https://github.com/voxel51/fiftyone/issues/1442 then? This seems like a fundamental memory leak that many Torch users may be suffering from

**Comment by ehofesmann** [comment]
> What are your thoughts on [pytorch/pytorch#13246 (comment)](https://github.com/pytorch/pytorch/issues/13246#issuecomment-436632186) from #1442 then? This seems like a fundamental memory leak that many Torch users may be suffering from

It definitely appears to be an issue that needs to be addressed. It has been brought up regarding pytorch-lightning https://github.com/PyTorchLightning/pytorch-lightning/issues/2352, it's just not how the data loaders in flash are currently working. If I end up needing to make changes to the FiftyOne-related work in that repo, I will bring this issue up.

**Review by ehofesmann — APPROVED** [review]
LGTM

**Comment by brimoor** [comment]
> > What are your thoughts on [pytorch/pytorch#13246 (comment)](https://github.com/pytorch/pytorch/issues/13246#issuecomment-436632186) from #1442 then? This seems like a fundamental memory leak that many Torch users may be suffering from
> 
> It definitely appears to be an issue that needs to be addressed. It has been brought up regarding pytorch-lightning [PyTorchLightning/pytorch-lightning#2352](https://github.com/PyTorchLightning/pytorch-lightning/issues/2352), it's just not how the data loaders in flash are currently working. If I end up needing to make changes to the FiftyOne-related work in that repo, I will bring this issue up.

Okay fair enough, just wanted to make sure this was on your radar

**Pull request merged**
