### PR TITLE
Data model updates

### PR DESCRIPTION
**Pull request by brimoor**
TODO: finish adding unit tests

Addresses a laundry list of data model issues:
- Fixes bug that prevented `dataset.add_sample(video_sample_or_sampleview_in_another_dataset)` from working properly
- Fixes bug that prevented frame labels from being properly cloned when calling `video_dataset.clone()`
- Added support for renaming and deleting embedded document fields of samples across an entire dataset via `dataset.delete_sample_field("embedded.field.name")` and `dataset.rename_sample_field("embedded.field.name")`
- Added support for renaming and deleting embedded document fields of frame labels across an entire dataset via `dataset.delete_frame_field("embedded.field.name")` and `dataset.rename_frame_field("embedded.field.name")`
- Added support for clearing (but not deleting from the schema) sample and frame-level fields across an entire dataset via `dataset.clear_sample_field()` and `dataset.clear_frame_field()`
- Added support for deleting fields/embedded fields of individual samples/frames via `sample_or_frame.clear_field(field_name)`, `del sample_or_frame[field_name]`, `sample_or_frame.embedded.field.clear_field()`, `del sample_or_frame.embedded["field"]` etc
- Converts `media_type` to a private field of samples (the preferred way to implement immutable, derived fields)
- Added support for running `sample_collection.write_json()` and `Dataset.from_json()` for video datasets

### CODE REVIEW

**Comment by benjaminpkane** [comment]
Working on completing the migration revision, and fixing any tests as I review. Lots of good stuff here!

**Comment by benjaminpkane** [comment]
Resolves #609

**Comment by benjaminpkane** [comment]
Things look good to me. I will wait for unit tests.

**Comment by brimoor** [comment]
Hey @benjaminpkane, when you get a chance, can you look into updating the App to work on this branch. It seems that the `media_type -> _media_type` transition is causing an issue for the App

Screen Shot 2020-11-13 at 11 30 05 AM

**Comment by brimoor** [comment]
Also, if you'll indulge me, a couple comments about the new `Refresh field colors` option:

- It looks like the font isn't being styled appropriately
- Rather than always having that option activated (light gray background), can you instead make it inactive by default and just have the active flash temporarily on selection? It doesn't feel right to have it selected permanently (in general, we're hunting row the right UI to use for "non-toggable" options)

**Comment by benjaminpkane** [comment]
Points addressed. I'm not fond of the the `Refresh field colors` look and feel, but intend on improving it in the sidebar updates

**Review by benjaminpkane — APPROVED** [review]

**Pull request merged**
