### PR TITLE
Selection options

### LINKED ISSUE #391: Show currently selected samples in the App, and allow selection/exclusion
We should replace `Dataset: coco-2017-validation` in the App screenshot below with `Selected # samples`, to indicate how many samples are currently selected:

Also, we should add an icon next to `Selected # samples` that the user can click on. This icon would open a small window that lets the user pick between two actions to take:
- show only these samples: this would add a `Select([list, of, selected, samples])` stage to the current view
- exclude these samples: this would add an `Exclude([list, of, selected, samples])` stage to the current view

Screen Shot 2020-08-13 at 3 25 08 PM

### PR DESCRIPTION
**Pull request by lethosor**
## What changes are proposed in this pull request?

A new menu that allows some basic operations to be performed from the UI
image

Clearing is new (and could only be done previously by manually unselecting everything). The other two can also be done by creating stages from Python. Note that they are implemented by creating view stages for simplicity.

Closes #391
Related: #113 

## How is this patch tested? If it is not, please explain why.

Local testing

### Is this a user-facing change that should be mentioned in the release notes?

-   [ ] No. You can skip the rest of this section.
-   [X] Yes. Give a description of this change to be included in the release
        notes for FiftyOne users.

Added the ability to clear, select, and exclude the selected samples from the app

### What areas of FiftyOne does this PR affect?

-   [x] App: FiftyOne application changes
-   [ ] Build: Build and test infrastructure changes
-   [ ] Core: Core `fiftyone` Python library changes
-   [ ] Documentation: FiftyOne documentation changes
-   [ ] Other

### CODE REVIEW

**Review by brimoor — COMMENTED** [review]
Looking good! I tested the functionality and it is mostly working, except for these two details:

(1) When selection/exclusion is applied, you need to refresh more of the App. The display options stats and `Viewing XXX samples` aren't updated, for example. I did a `session.refresh()` manually to get those updated

(2) I did the following:

- Select two samples
- Choose "Only show selected"
- Unselect the two samples
- Delete the `Select` stage that was created

After doing this, the two samples that I had originally selected and then deselected became selected again. Expected behavior is that, since they were deselected prior to deleting the `Select` stage, they should remain deselected afterwards.

One final suggestion on design: for the "0 samples selected" state, how about just rendering that in plain text with no disabled dropdown around it? My reasoning is that this would match visually with the "Viewing XXX samples" on the right, and it avoids rendering a dropdown that is not actually clickable. I currently see a "not active" cursor, which is quite distracting when I hover over it with no samples selected (e.g, when navigating between scrolling and using the view bar). In general, it's nice to remove as much visual clutter as possible, so that the user doesn't have to hover over something just to find that it is not clickable.

**Comment by brimoor** [comment]
A couple other comments related to Select/Exclude fields that would be nice to address before advertising a feature that enables easy creation of `Select/Exclude` stages:

- In the App backlog, there is a feature request to adopt a more compact rendering strategy for `Select` and `Exclude`, which can be very long. My proposal is to render `<first-few-charcters>...` when it gets too long (maybe always, even when one sample is selected, since the IDs are not really meant for visual consumption). When the user clicks into the stage, the full text would be expanded

- There seems to be a problem with creating `Select/Exclude` fields with > 1 ID in them. The intention is to accept input via `list,of,ids` rather than JSON-style `["list", "of", "ids"]` (which is how these stages used to accept input, I believe). When a stage is created programmatically, one sees `list,of,ids` in the view bar, but one cannot actually input multiple IDs in that way (or in JSON-style input)

**Comment by brimoor** [comment]
Let's not advertise a feature that will cause view bar to look like this :)

Screen Shot 2020-09-08 at 11 26 58 AM

**Comment by lethosor** [comment]
> (1) When selection/exclusion is applied, you need to refresh more of the App. The display options stats and Viewing XXX samples aren't updated, for example. I did a session.refresh() manually to get those updated

The relevant routes are using a decorator that is very similar to `_update_state` (what `refresh()` uses), and is certainly intended to do the same thing as `refresh()`: https://github.com/voxel51/fiftyone/pull/509/files#diff-72c8f530eb29b913a6aa6dfaf40522bcR275
I would need someone more familiar with the backend to help figure out why this isn't updating stats.

> After doing this, the two samples that I had originally selected and then deselected became selected again. Expected behavior is that, since they were deselected prior to deleting the `Select` stage, they should remain deselected afterwards.

As far as I can tell, this is an issue with the view bar, which caches the entire session state (including `selection`).

> Let's not advertise a feature that will cause view bar to look like this :)

The functionality itself is useful (and as mentioned above, the ability to clear selections is new), so I think that this is worth mentioning regardless of the view bar issues that you pointed out in https://github.com/voxel51/fiftyone/pull/509#issuecomment-688954004. I will look into addressing these, although it's worth noting that they were present and known before this PR (and could have been reproduced by creating a large `Select` stage from Python, for instance). There are several details that would need to be addressed with those, and I don't feel like most of them should be addressed in this PR. For instance:

* > My proposal is to render <first-few-charcters>... when it gets too long (maybe always, even when one sample is selected, since the IDs are not really meant for visual consumption).

  This would involve special behavior for certain view stages - I'm assuming you *don't* want long `Limit` stages truncated like this, for instance. I don't know if view stages currently support special rendering behaviors based on their types.

**Comment by brimoor** [comment]
@lethosor I hear you. Some of my comments aren't directly related to this PR, but they are directly related to the *feature* that we're going to announce

**Comment by lethosor** [comment]
> (1) When selection/exclusion is applied, you need to refresh more of the App. The display options stats and `Viewing XXX samples` aren't updated, for example. I did a `session.refresh()` manually to get those updated

I adopted the approach used by the view bar to fix this. This required discarding the selected samples when applying a selection, though (i.e. you'll have to select them again to perform another operation). I think this is fine because selection and exclusion can be used interchangeably - if you have 9 samples, deselecting one and `Select`ing the remaining 8 produces the same result as selecting one and `Exclude`ing it.

> One final suggestion on design: for the "0 samples selected" state, how about just rendering that in plain text with no disabled dropdown around it? My reasoning is that this would match visually with the "Viewing XXX samples" on the right, and it avoids rendering a dropdown that is not actually clickable. I currently see a "not active" cursor, which is quite distracting when I hover over it with no samples selected

I had experimented with a couple options earlier, and went with the "not allowed" cursor because a couple other things use that (e.g. unsupported fields).
I decided on this one:
image
We can only easily align the "0" with either the left edge of the grid or the position of the "1" when a sample is selected (which is shifted to the right a bit due to the button), not both. I went with the former.

**Comment by lethosor** [comment]
As for remaining issues:

> * There seems to be a problem with creating `Select/Exclude` fields with > 1 ID in them. The intention is to accept input via `list,of,ids` rather than JSON-style `["list", "of", "ids"]` (which is how these stages used to accept input, I believe). When a stage is created programmatically, one sees `list,of,ids` in the view bar, but one cannot actually input multiple IDs in that way (or in JSON-style input)

@benjaminpkane plans to address this, I believe in #486.

 

> * In the App backlog, there is a feature request to adopt a more compact rendering strategy for `Select` and `Exclude`, which can be very long. My proposal is to render `<first-few-charcters>...` when it gets too long (maybe always, even when one sample is selected, since the IDs are not really meant for visual consumption). When the user clicks into the stage, the full text would be expanded

Unsure what the plan is on this (see issues mentioned above) but we might be able to improve at least the scrolling behavior for 0.5.4.

**Comment by benjaminpkane** [comment]
> As for remaining issues:
> 
> > * There seems to be a problem with creating `Select/Exclude` fields with > 1 ID in them. The intention is to accept input via `list,of,ids` rather than JSON-style `["list", "of", "ids"]` (which is how these stages used to accept input, I believe). When a stage is created programmatically, one sees `list,of,ids` in the view bar, but one cannot actually input multiple IDs in that way (or in JSON-style input)
> 
> @benjaminpkane plans to address this, I believe in #486.
> 
> > * In the App backlog, there is a feature request to adopt a more compact rendering strategy for `Select` and `Exclude`, which can be very long. My proposal is to render `<first-few-charcters>...` when it gets too long (maybe always, even when one sample is selected, since the IDs are not really meant for visual consumption). When the user clicks into the stage, the full text would be expanded
> 
> Unsure what the plan is on this (see issues mentioned above) but we might be able to improve at least the scrolling behavior for 0.5.4.

I'll have these addressed in #486 tonight.

**Review by benjaminpkane — APPROVED** [review]
LGTM! Thanks for making the stories!

The first feature that really integrates with the view bar (or views, in general). Easy to use. Super exciting.

**Comment by lethosor** [comment]
Screenshot after #486 was merged in, for reference:

image

**Pull request merged**
