### PR TITLE
Custom embedded fields in the App

### PR DESCRIPTION
**Pull request by benjaminpkane**
Adds support for excluding and selecting embedded label fields in the App, and rendering custom embedded fields in the labels plot tab.

### CODE REVIEW

**Comment by benjaminpkane** [comment]
Undrafting but date/datetimes and range values need some cleanup.

**Review by brimoor — CHANGES_REQUESTED** [review]
@benjaminpkane Almost there! Here's a few things I'm seeing:

1. Getting `SampleField is not JSON serializable` when trying to load a view that involves selecting/excluding fields via `session.view = view`

2. Can you omit `index` from label stats graphs if there is no data? For consistency with how this is handled in the filters sidebar

3. When the user does something like `select_fields("ground_truth.detections.label")`, the API always includes all default fields of `Detection` (`id`, `label`, `confidence`, etc), for consistency with how `select_fields(field)` will also include all default top-level fields. In the App right now, `select_fields("ground_truth.detections.label")` is causing `id` to be all `None` in the filters sidebar, but all default field data should still be present (it is in the API)

```py
import fiftyone as fo
import fiftyone.zoo as foz

dataset = foz.load_zoo_dataset("quickstart")
dataset.add_dynamic_sample_fields()

session = fo.launch_app(dataset)

# Omits only the `area` field from `ground_truth`
view1 = dataset.exclude_fields("ground_truth.detections.area")

# Omits all top-level non-default fields except `ground_truth`
view2 = dataset.select_fields("ground_truth")

# Omits all top-level non-default fields except `ground_truth`
# Omits *only* non-default fields from `ground_truth.detections`
view3 = dataset.select_fields("ground_truth.detections.label")

session = fo.launch_app(view1)
session = fo.launch_app(view2)
session = fo.launch_app(view3)

# ERROR: SampleField is not JSON serializable
session.view = view1
session.view = view2
session.view = view3
```

4. You mentioned date/datetime tweaks. Just confirming that's not quite working yet in the label stats graphs. I've included my test code below

```py
from datetime import date, datetime, timedelta

import fiftyone as fo
import fiftyone.zoo as foz

dataset = foz.load_zoo_dataset("quickstart")
dataset.add_sample_field('ground_truth.detections.dates', fo.DateField)
dataset.add_sample_field('ground_truth.detections.datetimes', fo.DateTimeField)

ref_date = date.today()
ref_dt = datetime.utcnow()

for i, sample in enumerate(dataset.iter_samples(progress=True, autosave=True)):
    sample["dates"] = ref_date - timedelta(days=i)
    sample["datetimes"] = ref_dt - timedelta(hours=i)
    for j, detection in enumerate(sample.ground_truth.detections):
        detection["dates"] = ref_date - timedelta(days=i + j)
        detection["datetimes"] = ref_dt - timedelta(hours=i + j)

session = fo.launch_app(dataset)
```

**Comment by brimoor** [comment]
I get the error shown below when trying to clear the view bar when the view contains a `select_fields()` stage:

```py
import fiftyone as fo
import fiftyone.zoo as foz

dataset = foz.load_zoo_dataset("quickstart")
view = dataset.select_fields("ground_truth")

session = fo.launch_app(view)

# Try to clear the view in the view bar
```

```
TypeError: Cannot read properties of undefined (reading 'Count')
at http://localhost:5151/assets/index.7572b468.js:587:12286
at l (http://localhost:5151/assets/index.7572b468.js:177:68426)
at C (http://localhost:5151/assets/index.7572b468.js:177:57391)
at R (http://localhost:5151/assets/index.7572b468.js:177:58340)
at http://localhost:5151/assets/index.7572b468.js:177:59748
at re (http://localhost:5151/assets/index.7572b468.js:177:59530)
at Object.te [as get] (http://localhost:5151/assets/index.7572b468.js:177:59741)
at gGe (http://localhost:5151/assets/index.7572b468.js:177:15118)
at NGe (http://localhost:5151/assets/index.7572b468.js:177:17283)
at http://localhost:5151/assets/index.7572b468.js:177:37902
```

**Comment by brimoor** [comment]
There's something strange going on in the App when working with `view2` below. Everything is loading much slower than expected for a 200 sample dataset:

```py
import fiftyone as fo
import fiftyone.zoo as foz

dataset = foz.load_zoo_dataset("quickstart")
dataset.evaluate_detections("predictions", gt_field="ground_truth", eval_key="eval1", iou=0.5)
dataset.evaluate_detections("predictions", gt_field="ground_truth", eval_key="eval2", iou=0.9)

view1 = dataset.to_evaluation_patches("eval1")
view2 = dataset.load_evaluation_view("eval1", select_fields=True)
view3 = view2.to_evaluation_patches("eval1")

session = fo.launch_app(view1)

# The App is strangely sluggish when working with this view (see GIF below)
session = fo.launch_app(view2)

session = fo.launch_app(view3)
```

**Comment by benjaminpkane** [comment]
All of the above are addressed except for the `id` comment. That looks like a core library issue. See below:

```py
import fiftyone.zoo as foz
import fiftyone as fo

dataset = foz.load_zoo_dataset("quickstart")
dataset.select_fields("ground_truth.detections.label").count("ground_truth.detections._id") # zero
```

**Comment by benjaminpkane** [comment]
I'm not seeing any performance issues with the last code you shared

**Comment by brimoor** [comment]
> All of the above are addressed except for the `id` comment

Ah yeah I see what's wrong. Will fix, thanks!

**Comment by brimoor** [comment]
@benjaminpkane when I load this view in the App:

```py
session.view = dataset.select_fields("ground_truth.detections.label")
```

the labels don't appear in Flashlight or Looker. Presumably it thinks it is missing some data, but shouldn't be.

**Pull request merged**
