### PR TITLE
Keep app_config in sync with dataset schema changes

### PR DESCRIPTION
**Pull request by brimoor**
Adds logic to keep `dataset.app_config` in sync with renames/deletions of sample fields.

Also adds more documentation about `dataset.app_config` and, in particular, some sections to the App User Guide showing how to use multiple media fields.

```py
import fiftyone as fo
import fiftyone.utils.image as foui
import fiftyone.zoo as foz

dataset = foz.load_zoo_dataset("quickstart")
foui.transform_images(
    dataset,
    size=(-1, 32),
    output_field="thumbnail_path",
    output_dir="/tmp/thumbnails",
)

dataset.app_config.media_fields = ["filepath", "thumbnail_path"]
dataset.app_config.grid_media_field = "thumbnail_path"
dataset.save()

session = fo.launch_app(dataset)

# In the App, move `thumbnail_path` to a new group...

dataset.reload()
print(dataset.app_config)

dataset.rename_sample_field("thumbnail_path", "tp")
print(dataset.app_config)

# This isn't currently sufficient; must hard refresh in browser to grab schema change
session.refresh()

dataset.delete_sample_field("tp")
print(dataset.app_config)

# ERROR: GraphQL doesn't like empty sidebar group?
session.refresh()

# FIX ME: the dataset is now broken until sidebar groups are manually cleaned up
dataset.app_config.sidebar_groups.pop(-1)
dataset.save()
```

### CODE REVIEW

**Comment by benjaminpkane** [comment]
I'm not sure I was able to reproduce the GraphQL issue, but paths are now nullable/optional. I also think I was able to fix your first issue.

**Review by benjaminpkane — APPROVED** [review]
LGTM

**Comment by brimoor** [comment]
@benjaminpkane yeah no more error after this!!

```py
dataset.rename_sample_field("thumbnail_path", "tp")
session.refresh()
```

However, following along with the example in the description, I now get a different error after deleting the field:

```py
dataset.delete_sample_field("tp")
session.refresh()
```

```
TypeError: Cannot read properties of null (reading 'filter')
at C9 (http://localhost:5151/assets/index.0c8f3722.js:65:11954)
at fHe (http://localhost:5151/assets/index.0c8f3722.js:286:86613)
at bpe (http://localhost:5151/assets/index.0c8f3722.js:286:85760)
at http://localhost:5151/assets/index.0c8f3722.js:286:111248
at http://localhost:5151/assets/index.0c8f3722.js:38:47837
at http://localhost:5151/assets/index.0c8f3722.js:38:46062
at Object.u [as replaceState] (http://localhost:5151/assets/index.0c8f3722.js:38:33796)
at http://localhost:5151/assets/index.0c8f3722.js:38:46017
at http://localhost:5151/assets/index.0c8f3722.js:38:47828
at http://localhost:5151/assets/index.71bbd775.js:623:453
```

**Comment by benjaminpkane** [comment]
Ok, fixed

**Pull request merged**
