### PR TITLE
Expand group dataset metadata field for slice media types

### PR DESCRIPTION
**Pull request by benjaminpkane**
## What changes are proposed in this pull request?

For group datasets, the `metadata` field does not expand its schema when a new slice media type is implicitly added causing unwanted side effects like unnecessary metadata computation in the App server. This PR adds default metadata schema handling of new slice media types when adding samples to a group dataset.

## How is this patch tested? If it is not, please explain why.

New integration/unit test 

### Is this a user-facing change that should be mentioned in the release notes?

* Fixed metadata field expansion for group datasets when implicitly adding new slice media types, e.g. image and video

### What areas of FiftyOne does this PR affect?

-   [x] App: FiftyOne application changes
-   [ ] Build: Build and test infrastructure changes
-   [x] Core: Core `fiftyone` Python library changes
-   [ ] Documentation: FiftyOne documentation changes
-   [ ] Other

### CODE REVIEW

**Comment by sashankaryal** [comment]
This test is failing, should we do something about it?

>     [chromium] › oss/specs/regression-tests/group-video/group-video-label.spec.ts:87:3 › groups video labels › video plays with correct label for each slice

**Comment by benjaminpkane** [comment]
> This test is failing, should we do something about it?
> 
> > ```
> > [chromium] › oss/specs/regression-tests/group-video/group-video-label.spec.ts:87:3 › groups video labels › video plays with correct label for each slice 
> > ```

Right. I'll take a look locally this afternoon

**Comment by brimoor** [comment]
Just to clarify what this PR is addressing, currently on `develop` in the following situation:

```py
import fiftyone as fo

group = fo.Group()
sample1 = fo.Sample(filepath="/Users/Brian/Desktop/test.png", group=group.element("img"))
sample2 = fo.Sample(filepath="/Users/Brian/Desktop/test.mov", group=group.element("vid"))

dataset = fo.Dataset()
dataset.add_samples([sample1, sample2])

dataset.compute_metadata()

fo.pprint(dataset.select_group_slices(_allow_mixed=True).head())
```

the samples contain the image and video-specific fields as desired:

```
[
    <SampleView: {
        'id': '65e7f45243c6316183d89d9a',
        'media_type': 'image',
        'filepath': '/Users/Brian/Desktop/test.png',
        'tags': [],
        'metadata': <ImageMetadata: {
            'size_bytes': 90227,
            'mime_type': 'image/png',
            'width': 1906,
            'height': 422,
            'num_channels': 4,
        }>,
        'group': <Group: {'id': '65e7f45143c6316183d89d98', 'name': 'img'}>,
    }>,
    <SampleView: {
        'id': '65e7f45243c6316183d89d9b',
        'media_type': 'video',
        'filepath': '/Users/Brian/Desktop/test.mov',
        'tags': [],
        'metadata': <VideoMetadata: {
            'size_bytes': 1647380,
            'mime_type': 'video/quicktime',
            'frame_width': 2940,
            'frame_height': 1758,
            'frame_rate': 58.96551724137931,
            'total_frame_count': 228,
            'duration': 3.816667,
            'encoding_str': 'avc1',
        }>,
        'group': <Group: {'id': '65e7f45143c6316183d89d98', 'name': 'vid'}>,
        'frames': <FramesView: 0>,
    }>,
]
```

However, these media type-specific fields are not added to the dataset's `metadata` field schema:

```py
fo.pprint(dataset.get_field_schema(flat=True))
```

```
{
    'id': <fiftyone.core.fields.ObjectIdField object at 0x7f77e27a7be0>,
    'filepath': <fiftyone.core.fields.StringField object at 0x7f77e27a7c10>,
    'tags': <fiftyone.core.fields.ListField object at 0x7f77e27a7c70>,
    'metadata': <fiftyone.core.fields.EmbeddedDocumentField object at 0x7f77b0cb9160>,
    'metadata.size_bytes': <fiftyone.core.fields.IntField object at 0x7f77e3fbefa0>,
    'metadata.mime_type': <fiftyone.core.fields.StringField object at 0x7f77e3fbef70>,
    'group': <fiftyone.core.fields.EmbeddedDocumentField object at 0x7f77e3fbec10>,
    'group.id': <fiftyone.core.fields.ObjectIdField object at 0x7f77e3fbec40>,
    'group.name': <fiftyone.core.fields.StringField object at 0x7f77e3fcef70>,
}
```

This change makes it so that the `metadata` field in this situation (a grouped dataset with mixed media type slices) will now have all mixed fields declared on it:

```
{
    'id': <fiftyone.core.fields.ObjectIdField object at 0x7fd818859760>,
    'filepath': <fiftyone.core.fields.StringField object at 0x7fd818875fa0>,
    'tags': <fiftyone.core.fields.ListField object at 0x7fd818878fd0>,
    'metadata': <fiftyone.core.fields.EmbeddedDocumentField object at 0x7fd82a9fe370>,
    'metadata.size_bytes': <fiftyone.core.fields.IntField object at 0x7fd82a9fe0a0>,
    'metadata.mime_type': <fiftyone.core.fields.StringField object at 0x7fd82a9feee0>,
    'metadata.width': <fiftyone.core.fields.IntField object at 0x7fd82a9fe8b0>,
    'metadata.height': <fiftyone.core.fields.IntField object at 0x7fd82ab98520>,
    'metadata.num_channels': <fiftyone.core.fields.IntField object at 0x7fd82ab989d0>,
    'metadata.frame_width': <fiftyone.core.fields.IntField object at 0x7fd82ab31040>,
    'metadata.frame_height': <fiftyone.core.fields.IntField object at 0x7fd809114220>,
    'metadata.frame_rate': <fiftyone.core.fields.FloatField object at 0x7fd809114d30>,
    'metadata.total_frame_count': <fiftyone.core.fields.IntField object at 0x7fd809114ca0>,
    'metadata.duration': <fiftyone.core.fields.FloatField object at 0x7fd809114130>,
    'metadata.encoding_str': <fiftyone.core.fields.StringField object at 0x7fd809114fa0>,
    'group': <fiftyone.core.fields.EmbeddedDocumentField object at 0x7fd82ab2dd00>,
    'group.id': <fiftyone.core.fields.ObjectIdField object at 0x7fd82aa68880>,
    'group.name': <fiftyone.core.fields.StringField object at 0x7fd82aa68400>,
}
```

although the type of the `metadata` field remains the generic `Metadata` type:

```py
print(dataset.get_field("metadata").document_type)
# fiftyone.core.metadata.Metadata
```

**Review by brimoor — COMMENTED** [review]
Implementation LGTM.

One hesitation is that mixed image + video group datasets will now have quite a few `metadata` subfields in the sidebar, different subsets of which will always be empty when each slice is active...

However, in other cases it is nice that `metadata` will now automatically expand to make everything filterable. For example when working with grouped datasets that *only* contain image slices, now subfields like `metadata.width|height` will automatically become filterable when previously it was only the generic `Metadata` fields.

@benjaminpkane Out of curiosity, can you clarify why Flashlight (<-- I assume?) needs to have the subfields explicitly declared in the dataset's schema in order to avoid recomputing metadata? If the App just reads in the full `metadata` field values it will find the subfields despite not being formally declared in the dataset's schema.

**Comment by benjaminpkane** [comment]
> @benjaminpkane Out of curiosity, can you clarify why Flashlight (<-- I assume?) needs to have the subfields explicitly declared in the dataset's schema in order to avoid recomputing metadata? If the App just reads in the full `metadata` field values it will find the subfields despite not being formally declared in the dataset's schema.

Yes, historically this wouldn't be an issue. But the grid optimizations that filter sample data in [_project_pagination_paths](https://github.com/voxel51/fiftyone/blob/1852aaf1fc138579647de36bf0953f286767f2d2/fiftyone/server/view.py#L244) remove the undeclared fields. The alternative is to skip projections for the `metadata` field, but that would leave image/video metadata fields out of the sidebar which could be misleading

**Review by brimoor — APPROVED** [review]
@benjaminpkane thanks for clarifying why this is needed. I'm onboard with this PR as implemented 👍

**Review by swheaton — APPROVED** [review]
thanks @benjaminpkane ! Merge when you're ready but I'll mark the issue as DONE

**Pull request merged**
