### PR TITLE
App issues

### LINKED ISSUE #1831: [FR] Make results lists scrollabe in the App
On `fiftyone>=0.16`, the dataset list dropdown now behaves like other "long list" elements: they are limited to 10 results and never scrollable, and the user must start typing in order to limit their results to <10 in order to find certain datasets.

I propose that, to increase usability:
- The default results count is increased
- These lists are scrollable, to ensure that users that don't want to (or don't realize they can) start typing to narrow results can still find the element of interest to them

Screen Shot 2022-06-07 at 11 51 49 AM

Screen Shot 2022-06-07 at 11 49 48 AM

### LINKED ISSUE #1832: [BUG] App cannot handle schema changes to an in-use dataset
On `fiftyone>=0.16.0`, the App cannot handle schema changes to an in-use dataset:

```py
import fiftyone as fo

sample = fo.Sample(filepath="/path/to/image.jpg")

dataset = fo.Dataset()
dataset.add_sample(sample)

session = fo.launch_app(dataset)

sample["value"] = 1
sample.save()

# Raises error shown below
session.refresh()

# Does not escape the error page
session.dataset = None

# Doesn't help
session.refresh()

# Now press `x` in error modal to revert to empty dataset state in App

# Error below is still raised
session.dataset = dataset
```

```
Error: invalid path value
at http://localhost:5151/assets/index.1baa3d4c.js:191:11855
at a (http://localhost:5151/assets/vendor.2936b611.js:52:494206)
at _ (http://localhost:5151/assets/vendor.2936b611.js:52:483152)
at b (http://localhost:5151/assets/vendor.2936b611.js:52:484363)
at http://localhost:5151/assets/vendor.2936b611.js:52:485657
at http://localhost:5151/assets/vendor.2936b611.js:52:485629
at Object.Q [as get] (http://localhost:5151/assets/vendor.2936b611.js:52:485651)
at getNodeLoadable (http://localhost:5151/assets/vendor.2936b611.js:52:442147)
at _ (http://localhost:5151/assets/vendor.2936b611.js:52:482529)
at http://localhost:5151/assets/index.1baa3d4c.js:355:3674
```

### LINKED ISSUE #1835: [BUG] Sidebar statistics fail to load in App
On `fiftyone>0.16.0`, I get the error below when trying to load an oldish dataset (created prior to the introduction of the `created_at` field) in the App.

The error occurs as the sidebar stats load:

Screen Shot 2022-06-07 at 11 58 43 AM

```
TypeError: Cannot read properties of undefined (reading 'Count')
at http://localhost:5151/assets/index.1baa3d4c.js:191:12071
at a (http://localhost:5151/assets/vendor.2936b611.js:52:494206)
at _ (http://localhost:5151/assets/vendor.2936b611.js:52:483152)
at b (http://localhost:5151/assets/vendor.2936b611.js:52:484363)
at http://localhost:5151/assets/vendor.2936b611.js:52:485657
at http://localhost:5151/assets/vendor.2936b611.js:52:485629
at Object.Q [as get] (http://localhost:5151/assets/vendor.2936b611.js:52:485651)
at getNodeLoadable (http://localhost:5151/assets/vendor.2936b611.js:52:442147)
at http://localhost:5151/assets/vendor.2936b611.js:52:483869
at l2.getLeafNode (http://localhost:5151/assets/vendor.2936b611.js:52:474894)
```

### LINKED ISSUE #1850: [BUG] App cannot handle deleting a dataset and creating a new one of the same name
### System information

-   **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux 20.04
-   **FiftyOne installed from (pip or source)**: 0.16.2
-   **FiftyOne version (run `fiftyone --version`)**: FiftyOne v0.16.2, Voxel51, Inc.
-   **Python version**: Python 3.9.5

### Commands to reproduce

```py
import fiftyone as fo
from time import sleep

ds_name = 'coco-2017-train'
t_sleep = 5

ds1 = fo.load_dataset(ds_name)
ds2 = fo.Dataset(name='temp_dataset1')
ds2.merge_samples(ds1.take(5))

t_sleep = 5

fo.launch_app(ds1, auto=False)
sleep(t_sleep)
fo.launch_app(ds2, auto=False)

# simulating that I have done analysis on 5 images and are now selecting 5 new images
ds2.delete()
ds2 = fo.Dataset(name='temp_dataset1')
ds2.merge_samples(ds1.take(5))

sleep(t_sleep)
fo.launch_app(ds1, auto=False)
sleep(t_sleep)
fo.launch_app(ds2, auto=False)
```

### Describe the problem

The app does not show the image in the temporary dataset if it is deleted and then created again. but the datset seems to have the images in it with the correct length.

### Code to reproduce issue

Run the code above, you have to look at the app to see that no images are shown.

### What areas of FiftyOne does this bug affect?

-   [x] `App`: FiftyOne application issue
-   [ ] `Core`: Core `fiftyone` Python library issue
-   [ ] `Server`: Fiftyone server issue

### Willingness to contribute

The FiftyOne Community encourages bug fix contributions. Would you or another
member of your organization be willing to contribute a fix for this bug to the
FiftyOne codebase?

-   [ ] Yes. I can contribute a fix for this bug independently.
-   [x] Yes. I would be willing to contribute a fix for this bug with guidance from the FiftyOne community.
-   [ ] No. I cannot contribute a bug fix at this time.

### LINKED ISSUE #1853: [BUG] App can't handle dataset schema changes while dataset is loaded
On `fiftyone==0.16.2`, an error is raised when a dataset's schema is changed after it has been loaded in the App.

This is the same core issue motivating other instances of this, such as https://github.com/voxel51/fiftyone/issues/1832 and https://github.com/voxel51/fiftyone/issues/1850.

```py
import fiftyone as fo
import fiftyone.brain as fob
import fiftyone.zoo as foz

dataset = foz.load_zoo_dataset("quickstart")

session = fo.launch_app(dataset)

results = fob.compute_similarity(dataset, brain_key="img_sim")
results.find_duplicates(fraction=0.1)

# Raises error below
session.view = results.duplicates_view(
    type_field="dup_type",
    id_field="dup_id",
    dist_field="dup_dist",
)
```

```
Error: invalid path dup_dist
at http://localhost:5151/assets/index.33425aae.js:191:11855
at a (http://localhost:5151/assets/vendor.2936b611.js:52:494206)
at _ (http://localhost:5151/assets/vendor.2936b611.js:52:483152)
at b (http://localhost:5151/assets/vendor.2936b611.js:52:484363)
at http://localhost:5151/assets/vendor.2936b611.js:52:485657
at http://localhost:5151/assets/vendor.2936b611.js:52:485629
at Object.Q [as get] (http://localhost:5151/assets/vendor.2936b611.js:52:485651)
at getNodeLoadable (http://localhost:5151/assets/vendor.2936b611.js:52:442147)
at http://localhost:5151/assets/vendor.2936b611.js:52:483869
at l2.getLeafNode (http://localhost:5151/assets/vendor.2936b611.js:52:474894)
```

### LINKED ISSUE #1867: [BUG] Cannot use app after creating new field for samples in my dataset
### System information

-   **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: MacOS
-   **FiftyOne installed from (pip or source)**: pip
-   **FiftyOne version (run `fiftyone --version`)**: 0.16.2
-   **Python version**: 3.9.0

### Commands to reproduce

As thoroughly as possible, please provide the Python and/or shell commands used
to encounter the issue. Application steps can be described in the next section.

```py
import fiftyone as fo

name = "val_data"
dataset_dir = " "
splits = ["val"]
val_data = fo.Dataset(name)

for split in splits:
        val_data.add_dir(
        dataset_dir=dataset_dir,
        dataset_type=fo.types.YOLOv5Dataset,
        split=split,
        tags=split,
)

val_data_copy = val_data.clone()

session = fo.launch_app(val_data_copy, port=5151)

val_data_copy.compute_metrics()

for sample in val_data_copy:
        sample["asp"] = round((sample["metadata"].width) / (sample["metadata"].height), 2)
        sample.save()
```

### Describe the problem
After adding this new field to all my samples, the app errors out with the following error when i refresh the browser tab
Screen Shot 2022-06-10 at 1 02 16 PM

### What areas of FiftyOne does this bug affect?

-   [X] `App`: FiftyOne application issue
-   [ ] `Core`: Core `fiftyone` Python library issue
-   [ ] `Server`: Fiftyone server issue

### Willingness to contribute

The FiftyOne Community encourages bug fix contributions. Would you or another
member of your organization be willing to contribute a fix for this bug to the
FiftyOne codebase?

-   [ ] Yes. I can contribute a fix for this bug independently.
-   [X] Yes. I would be willing to contribute a fix for this bug with guidance from the FiftyOne community.
-   [ ] No. I cannot contribute a bug fix at this time.

### PR DESCRIPTION
**Pull request by benjaminpkane**
### Issues

* Resolves #1831 
* Resolves #1832 
* Resolves #1835
* Resolves #1853 
* Resolves #1867
* Resolves #1853
* Resolves #1850

### CODE REVIEW

**Comment by benjaminpkane** [comment]
Also resolves #1853

**Comment by brimoor** [comment]
https://github.com/voxel51/fiftyone/issues/1867 is not fully resolved yet. I don't get an error if I do a ctrl + shift + R refresh, but a simple refresh still causes the error:

```py
import fiftyone as fo
import fiftyone.zoo as foz

dataset = foz.load_zoo_dataset("quickstart")
session = fo.launch_app(dataset)

dataset.set_values("new_field", [True] * len(dataset))

# Error: invalid path new_field
session.refresh()
```

**Comment by brimoor** [comment]
^same thing for https://github.com/voxel51/fiftyone/issues/1832.

**Comment by benjaminpkane** [comment]
@brimoor comments addressed

**Comment by benjaminpkane** [comment]
Note that if the App is in an error state, making `session.refresh()`, `session.dataset = None`, etc. will have no effect. Reloading or clearing the error in the App is required to exit the error boundary.

**Review by brimoor — APPROVED** [review]
LGTM (didn't have time to actually test though)

**Pull request merged**
