### PR TITLE
use yarn v4 in e2e-pw

### PR DESCRIPTION
**Pull request by imanjra**
## What changes are proposed in this pull request?

Use Yarn 3.2.1 in e2e-pw (same as app)

## How is this patch tested? If it is not, please explain why.

E2E

### Is this a user-facing change that should be mentioned in the release notes?

-   [x] No. You can skip the rest of this section.
-   [ ] Yes. Give a description of this change to be included in the release
        notes for FiftyOne users.

(Details in 1-2 sentences. You can just refer to another PR with a description
if this PR is part of a larger change.)

### What areas of FiftyOne does this PR affect?

-   [ ] App: FiftyOne application changes
-   [ ] Build: Build and test infrastructure changes
-   [ ] Core: Core `fiftyone` Python library changes
-   [ ] Documentation: FiftyOne documentation changes
-   [ ] Other

## Summary by CodeRabbit

- **Chores**
  - Updated `.gitignore` to stop ignoring `.yarnrc.yml`.
  - Added `.yarnrc.yml` with configurations for yarn compression, cache, node linker, and executable path.

### CODE REVIEW

**Review by sashankaryal — APPROVED** [review]
lgtm but e2e is not running because of this change 🤔

**Review by sashankaryal — CHANGES_REQUESTED** [review]
lgtm but e2e is not running because of this change 🤔

**Comment by benjaminpkane** [comment]
Can we just upgrade to yarn 4? We can do the same in App soon

**Review by sashankaryal — APPROVED** [review]
✔️

**Review by benjaminpkane — APPROVED** [review]
🙇

**Pull request merged**
