### PR TITLE
Stage UUIDs

### LINKED ISSUE #485: Don't re-create other view stages when modifying/creating other stages
Current behavior:

- Create a `Take(1, seed=None)` view stage in the App. An image appears
- Add another stage, say, `Limit(1)` in the view bar. Now a different image appears, because creating the new stage causes the existing `Take` stage to be re-instantiated

Note that editing a stage, eg clicking into the `seed` parameter of an existing `Take(1, seed=None)` stage and then submitting the form, should cause the view stage to be recreated. This would be a way to intentionally regenerate a randomized view, for example.

The desired behavior is that existing view stages are not re-instantiated when other view stages are created, modified, re-organized, etc. The issue is that stages can have default parameters, and those default parameters can be randomly generated (e.g., `_randint` for the `Take()` and `Shuffle()` stages), so stages can't be re-instantiated.

For reference, the backend exhibits the desired behavior:

v = dataset.take(1)
v2 = v.limit(1)  # contains same sample

It seems that the best way to achieve this may be to let the backend own the definition of the view and have the App report changes that it would like to be made to the view.

### PR DESCRIPTION
**Pull request by benjaminpkane**
## What changes are proposed in this pull request?

Resolves #485 and prevents view bar stages from flickering when the view is changed from python.

```py
view = dataset.take(1)
session.view = view
session.view = view # _randint remains the same and no animations occur in the view bar!
```

## How is this patch tested? If it is not, please explain why.

A uuid serialization and deserialization test has been added to the stage unit tests.

### Is this a user-facing change that should be mentioned in the release notes?

-   [ ] No. You can skip the rest of this section.
-   [x] Yes. Give a description of this change to be included in the release
        notes for FiftyOne users.

Take and Shuffle seeds are persisted to the App.

### What areas of FiftyOne does this PR affect?

-   [x] App: FiftyOne application changes
-   [ ] Build: Build and test infrastructure changes
-   [ ] Core: Core `fiftyone` Python library changes
-   [ ] Documentation: FiftyOne documentation changes
-   [ ] Other

### CODE REVIEW

**Comment by lethosor** [comment]
The Shuffle and Take stages don't seem to be working when created from the app (as far as I can tell, they don't finalize - they're not showing up in the Python shell). Still trying to track it down, but I noticed that those two are the only stages that changed in this PR, besides the base ViewStage class.

Side note, the second parameter to Take is named "reverse" in the app, and I'm pretty sure it should be "seed", like Shuffle.

**Comment by benjaminpkane** [comment]
OK, good catches. Stages created _in_ the view bar were not initialzing "hidden" (_randint) parameters correctly.

Things seem to be working now.

**Comment by benjaminpkane** [comment]
I think we should merge this before #514, then I can merge `develop` into #514 and monkey test for ~10 minutes.

Reviewing #532 now.

**Review by lethosor — APPROVED** [review]
Looks good! As a bonus, view bar operations seem faster on my end now too.

**Pull request merged**
