### PR TITLE
More view and aggregation updates

### PR DESCRIPTION
**Pull request by brimoor**
Resolves https://github.com/voxel51/fiftyone/issues/811 and https://github.com/voxel51/fiftyone/issues/813.

Changelog
- Replaces the `MapValues` view stage with a `SetField` stage that allows for setting new fields on a view using an arbitrary expression to define the value. Supports both sample-level and frame-level fields
- Removes `AggregationResult` class in favor of returning the raw aggregation results directly (cf. discussion in https://github.com/voxel51/fiftyone/issues/811)
- Adds support for the `[]` syntax (and automatic unwinding of common fields) to `SetField`, which supports processing of array fields and embedded array fields in the expected ways
- Adds a number of new `ViewExpression` methods exposing various string-related operations, some control flow things like case/switch statements, reductions, and other optimizations
- Fixes a subtle bug in `FilterLabels` that would overwrite any custom fields that the user may have added to their `Detections` instance (the issue here was that `$mergeObjects` does not merge subfields, it overwrites the entire top-level fields. True embedded merging required a bit more tedium)

Docs changes
- Updates `docs/source/user_guide/using_aggregations.rst` to reflect the new aggregation API
- Adds more examples to `docs/source/user_guide/using_views.rst` to whet the reader's appetite with the possibilities of `ViewExpression`s
- Adds thorough examples of using each `ViewExpression` method to the API reference docs

Example usages:

```py
import fiftyone as fo
import fiftyone.zoo as foz
from fiftyone import ViewField as F

#
# Sample-level fields
#

dataset = foz.load_zoo_dataset("quickstart")

print(dataset.distinct("predictions.detections.label"))
view = dataset.map_labels("predictions", {"airplane": "OTHER"})
print(view.distinct("predictions.detections.label"))

# implement `map_labels()` via `set_field()`, for fun
print(dataset.distinct("predictions.detections.label"))
view = dataset.set_field("predictions.detections.label", F("label").map_values({"airplane": "OTHER"}))
print(view.distinct("predictions.detections.label"))

view = dataset.set_field("predictions.detections.is_cat", F("label") == "cat")
print(view.distinct("predictions.detections.is_cat"))

view = dataset.set_field("predictions.num_predictions", F("detections").length())
print(view.bounds("predictions.num_predictions"))

#
# Frame-level fields
#

dataset = foz.load_zoo_dataset("quickstart-video")

print(dataset.distinct("frames.ground_truth_detections.detections.label"))
view = dataset.filter_labels("frames.ground_truth_detections", F("label") == "vehicle")
print(view.distinct("frames.ground_truth_detections.detections.label"))

# `map_labels()` now supports frame-level labels!
print(dataset.distinct("frames.ground_truth_detections.detections.label"))
view = dataset.map_labels("frames.ground_truth_detections", {"person": "PERSON"})
print(view.distinct("frames.ground_truth_detections.detections.label"))

# implement `map_labels()` via `set_field()`, for fun
print(dataset.distinct("frames.ground_truth_detections.detections.label"))
view = dataset.set_field(
    "frames.ground_truth_detections.detections.label",
    F("label").map_values({"person": "PERSON"})
)
print(view.distinct("frames.ground_truth_detections.detections.label"))
```

### CODE REVIEW

**Comment by benjaminpkane** [comment]
My initial comment is that if we think stages like `FilterLabels`, and `LimitLabels` are here to stay (and not be generalized) for the foreseeable future, then `MapLabels` is not out of place.

> The difference between MapValues and SetField is whether the "root" document is the value or it's parent document.

Interesting, this is because `SetField` is not as useful if it does not have access to the parent?

**Comment by brimoor** [comment]
> My initial comment is that if we think stages like `FilterLabels`, and `LimitLabels` are here to stay (and will not be generalized) for the foreseeable future, then `MapLabels` is not out of place.

Yeah I agree that `MapLabels` is consistent with `FilterLabels`, `LimitLabels`, etc. Labels are the most important data type, so I do think it makes sense to provide easy-to-use methods for those types.

**Comment by brimoor** [comment]
> > The difference between MapValues and SetField is whether the "root" document is the value or it's parent document.
> 
> Interesting, this is because `SetField` is not as useful if it does not have access to the parent?

Actually its the other way around: the idea of `MapValues` is that it is exclusively useful for transforming values to other values. `SetField` gets access to the parent document of the field you are setting. In fact, `SetField` has a `root` flag that enables you to specify whether you would like the expression to be relative to the root sample document instead, in which case you have access to any information you want.

So from that standpoint, if something is on the chopping block, it should be `MapValues`.

I'd be interested to get your feedback on the current behavior of `SetField` w.r.t. the parent document vs. root sample document business. I thought about always defaulting to requiring the expression to always be defined relative to the root sample document, but, automatic array unwinding adds some complications there. I would have to do some logic on the `expr` argument to match any unwinding that may have taken place.

**Comment by benjaminpkane** [comment]
Looking through the code, I don't see any `root=True` usage. It might also be a leaky abstraction to users, if I understand how `root=True` works (or would work). I'll respond again in the morning after looking at the implementation more, but a `root=True` option doesn't seem release critical.

**Comment by benjaminpkane** [comment]
Very cool to see all the new additions to view expressions.

**Comment by benjaminpkane** [comment]
I am happy to help update things server side when `AggregationResult`s have been removed. Might speed things along. I'll need to tweak some javascript code at a minimum unless serialized results do not change at all.

**Comment by brimoor** [comment]
> I am happy to help update things server side when `AggregationResult`s have been removed. Might speed things along. I'll need to tweak some javascript code at a minimum unless serialized results do not change at all.

@benjaminpkane That would be great. I've removed `AggregationResult` and updated almost all Python code. There's a least one place that I left a todo that needs your attention in `fiftyone.server.main._gather_results()`.

The serialized format of the aggregation results has changed slightly, so you will need to make some small updates in various places.

One small thing I'm undecided about is which of these is preferable:

```py
#
# current behavior
#
# The motivation here is that np.histogram() returns a `(counts, edges)` tuple, but we also 
# return `other` and (a) three output arguments is starting to be a lot, and (b) `other` is 
# often probably not interesting
counts, edges, other = dataset.histogram_values(...)

# alternative
result = dataset.histogram_values(...)
# result = {"counts": counts, "edges": edges, "other": other}
```

Any thoughts here?

**Comment by benjaminpkane** [comment]
`counts, edges, other` seems convenient to me. Once a user learns the format, I think they would prefer a tuple.

**Comment by benjaminpkane** [comment]
Ok, server looks good now.

**Comment by brimoor** [comment]
@benjaminpkane can you explain the purpose of the `hide_frames` and `hide_result` arguments of `ViewStage`s that process frame labels? The `SetField` and `MapLabels` stages now support frame labels, but I'm unsure what to do with those arguments and why they exist in general.

**Comment by benjaminpkane** [comment]
`hide_result` applies Fields Sidebar filters to pagination (allowing for only matched results), but allows for the full sample info to still be sent so in the sample modal when a filter is changed, requiring more data to be presented, the sample has it.

For example, a user may select only `cat` detections in the sample grid for field, expand a sample (open the modal) and then remove the "only cats" filter. The modal has the data to show all detections because of `hide_result`. Perhaps requiring a new request to be sent when the modal is opened is preferred. `hide_result` seemed like a more appropriate MVP, though.

`hide_frames` can and should be removed. I can at least try to remove its usage in the server right now. It places frames in the `_frames` field. That's all.

**Comment by benjaminpkane** [comment]
`hide_frames` was meant to be an optimization for pagination, but I think it is negligible at this. I just need to truncate pagination requests to only contain the first frame.

**Review by benjaminpkane — APPROVED** [review]
LGTM :rocket:

**Pull request merged**
