### PR TITLE
Adding migration API

### PR DESCRIPTION
**Pull request by brimoor**
Resolves https://github.com/voxel51/fiftyone/issues/826.

Adds a migration API that allows for arbitrary migration of one or all datasets between package versions. This functionality is exposed via the new `fiftyone migrate` CLI command.

Also moves `fiftyone.utils.uid` to `fiftyone.core.uid` and moves the import tracking function from `fiftyone/__init__.py` into this module, for clarity.

**Example usage**

```shell
# In an environment with this branch installed

# Load quickstart dataset if necessary
fiftyone zoo datasets load quickstart

# View current versions of everything
fiftyone migrate --info

# Migrate everything down to v0.6.0
fiftyone migrate --all -v 0.6.0 --verbose
fiftyone migrate --info
```

```shell
# In a fresh environment, install v0.6.0 and use the dataset
pip install --index https://pypi.voxel51.com fiftyone==0.6.0
fiftyone --version
fiftyone datasets stream quickstart
```

```py
# Back in environment with this branch installed

import fiftyone as fo
# Migrating database to v0.7.2

dataset = fo.load_dataset("quickstart")
# Migrating dataset 'quickstart' to v0.7.2
```

**Incremental revision tests**

```shell
# Incremental down
fiftyone migrate -n quickstart -v 0.7.2 --verbose
fiftyone migrate -n quickstart -v 0.6.6 --verbose
fiftyone migrate -n quickstart -v 0.6.5 --verbose
fiftyone migrate -n quickstart -v 0.6.3 --verbose
fiftyone migrate -n quickstart -v 0.6.2 --verbose
fiftyone migrate -n quickstart -v 0.6.1 --verbose

# Incremental up
fiftyone migrate -n quickstart -v 0.6.2 --verbose
fiftyone migrate -n quickstart -v 0.6.3 --verbose
fiftyone migrate -n quickstart -v 0.6.5 --verbose
fiftyone migrate -n quickstart -v 0.6.6 --verbose
fiftyone migrate -n quickstart -v 0.7.2 --verbose
```

### CODE REVIEW

**Comment by brimoor** [comment]
@benjaminpkane I tried to test this by installing `fiftyone==0.6.0` in a fresh virtual environment so I could launch the App and view the downgraded `quickstart` dataset, but I got the following error:

```
$ pip install fiftyone==0.6.0
Collecting fiftyone==0.6.0
  Using cached fiftyone-0.6.0-py3-none-any.whl (221 kB)
Requirement already satisfied: setuptools in ./dev/env/tmp3/lib/python3.6/site-packages (from fiftyone==0.6.0) (51.0.0)
ERROR: Could not find a version that satisfies the requirement fiftyone-gui<0.7,>=0.6.0 (from fiftyone)
ERROR: No matching distribution found for fiftyone-gui<0.7,>=0.6.0
```

I believe this is because the old GUI app was too big to upload to public pypi. Can you remind me if/how we could address this so that `

Also, to avoid the above, I substituted the old pip install command:

```
pip install --index https://voxel51@pypi.voxel51.com fiftyone==0.6.0
```

which worked fine. But then I get the following error when trying to open the quickstart dataset (which has been migrated via `fiftyone migrate --all -v 0.6.0`) in the v0.6.0 app:

```
$ fiftyone app launch quickstart
Uncaught exception
Traceback (most recent call last):
  File "/Users/Brian/dev/env/tmp3/bin/fiftyone", line 8, in <module>
    sys.exit(main())
  File "/Users/Brian/dev/env/tmp3/lib/python3.6/site-packages/fiftyone/core/cli.py", line 1490, in main
    args.execute(args)
  File "/Users/Brian/dev/env/tmp3/lib/python3.6/site-packages/fiftyone/core/cli.py", line 1473, in <lambda>
    parser.set_defaults(execute=lambda args: command.execute(parser, args))
  File "/Users/Brian/dev/env/tmp3/lib/python3.6/site-packages/fiftyone/core/cli.py", line 754, in execute
    dataset = fod.load_dataset(args.name)
  File "/Users/Brian/dev/env/tmp3/lib/python3.6/site-packages/fiftyone/core/dataset.py", line 84, in load_dataset
    return Dataset(name, _create=False)
  File "/Users/Brian/dev/env/tmp3/lib/python3.6/site-packages/fiftyone/core/singleton.py", line 36, in __call__
    instance.__init__(name=name, _create=_create, *args, **kwargs)
  File "/Users/Brian/dev/env/tmp3/lib/python3.6/site-packages/fiftyone/core/dataset.py", line 178, in __init__
    ) = _load_dataset(name)
  File "/Users/Brian/dev/env/tmp3/lib/python3.6/site-packages/fiftyone/core/dataset.py", line 1952, in _load_dataset
    dataset_doc = foo.DatasetDocument.objects.get(name=name)
  File "/Users/Brian/dev/env/tmp3/lib/python3.6/site-packages/mongoengine/queryset/base.py", line 267, in get
    result = next(queryset)
  File "/Users/Brian/dev/env/tmp3/lib/python3.6/site-packages/mongoengine/queryset/base.py", line 1572, in __next__
    _auto_dereference=self._auto_dereference,
  File "/Users/Brian/dev/env/tmp3/lib/python3.6/site-packages/mongoengine/base/document.py", line 804, in _from_son
    obj = cls(__auto_convert=False, _created=created, **data)
  File "/Users/Brian/dev/env/tmp3/lib/python3.6/site-packages/mongoengine/base/document.py", line 93, in __init__
    raise FieldDoesNotExist(msg)
mongoengine.errors.FieldDoesNotExist: The fields "{'version'}" do not exist on the document "DatasetDocument"
```

**Comment by benjaminpkane** [comment]
The only way to download a version prior to v0.7.0 is with the extra index command:
```
pip install --index https://voxel51@pypi.voxel51.com fiftyone==...
```
I don't think there is a way around this, practically speaking.

**Comment by benjaminpkane** [comment]
The error means `version` is still in the dataset document. Hmm.

https://github.com/voxel51/fiftyone/blob/b5f84a531b5c3d55b0e0142c8729fe5b418be8d0/fiftyone/migrations/revisions/v0_6_2.py#L129

The above should have deleted it. I can try to reproduce, but can you confirm that `version` is in the raw mongo JSON output after this downgrade in dataset documents?

**Comment by brimoor** [comment]
> The error means `version` is still in the dataset document. Hmm.
> 
> https://github.com/voxel51/fiftyone/blob/b5f84a531b5c3d55b0e0142c8729fe5b418be8d0/fiftyone/migrations/revisions/v0_6_2.py#L129
> 
> The above should have deleted it. I can try to reproduce, but can you confirm that `version` is in the raw mongo JSON output after this downgrade in dataset documents?

ooooooh I see, the migration method I was tweaking was inserting the destination version, which is only safe after the migration that introduces that field. Thanks for nudging me in the right direction!

**Comment by brimoor** [comment]
Okay, I've spent way too much time on this now, but I think I've covered all the relevant cases, including downgrading to versions prior to either the first dataset or database migration, in which case version information needs to be **missing**.

I also added notes to the docs about using `pip install --index https://pypi.voxel51.com fiftyone==<version>` for versions before 0.7.0.

I was able to successfully migrate down to v0.6.0 and view a dataset, and then migrate back up. So, I think we're all set here.

**Review by benjaminpkane — APPROVED** [review]
Thanks for taking this on! Migrations are pretty slick now. Much better than other projects I've encountered out in the wild. Not that much code, either. LGTM!

**Pull request merged**
