### PR TITLE
Allow FilterLabels to process all Label types

### PR DESCRIPTION
**Pull request by brimoor**
Allows `FilterLabels()` to accept any `Label` type, including non-list fields like `Classification`. Previously `FilterLabels()` would only support list types (e.g., `Classifications`) and one must use `FilterField()` to filter `Classification` labels.

This is more consistent with other stages like `MapLabels` that support any `Label` type.

Note that, although this does completely deprecate the need for using `FilterField` for `Label` types, it is still useful for filtering non-`Label` types.

```py
import fiftyone as fo
import fiftyone.zoo as foz
from fiftyone import ViewField as F

# Test filter_labels() with a non-list field type (Classification)

dataset1 = foz.load_zoo_dataset(
    "cifar10",
    split="test",
    max_samples=100,
    shuffle=True,
)
print(dataset1)

view1 = dataset1.filter_labels(
    "ground_truth", F("label") == "cat", only_matches=True
)
print(view1)
print(view1.first())  # `cat` sample

# Test filter_labels() with a list field type (Detections)

dataset2 = foz.load_zoo_dataset(
    "coco-2017",
    split="validation",
    max_samples=100,
    shuffle=True,
)
print(dataset2)

view2 = dataset2.filter_labels(
    "ground_truth", F("label") == "person", only_matches=True
)
print(view2)
print(view2.first())  # only contains `person` detections

# Check App functionality

session = fo.launch_app()

session.view = view1
session.view = view2
```

### CODE REVIEW

**Review by benjaminpkane — APPROVED** [review]
I have finally added frame labels support. I won't claim it is bug free, but I'll be able merging this work into #793 and continue testing from there.

```py
import fiftyone as fo
import fiftyone.zoo as foz
F = fo.ViewField

dataset = foz.load_zoo_dataset("quickstart-video")
with_people = dataset.filter_labels("frames.ground_truth_detections", F("label") == "person", only_matches=True)
print(len(with_people)) # == 6

for idx, sample in enumerate(dataset): 
     label = "event" if idx % 2 == 0 else "odd" 
     sample[1]["idx"] = fo.Classification(label=label) 
     sample.save()

only_even = dataset.filter_labels("frames.idx", F("label") == "even", only_matches=True)
print(len(only_even)) # == 5
```

**Comment by benjaminpkane** [comment]
Ok, still a couple bugs to fix. Will follow up.

**Comment by benjaminpkane** [comment]
#793 has fixes related to counting frame labels that are not list labels, and serialization of filter stages so the server can load the stage correctly.

I can work on docs later today and finish this PR.

**Comment by brimoor** [comment]
Hey @benjaminpkane I think something is wrong with the App here. Can you take a look?

If you run the example in the description, `session.view = view2` at the end shows an empty view, although the printing statements show that `view2` does contain person-only detections as expected.

**Comment by benjaminpkane** [comment]
> Hey @benjaminpkane I think something is wrong with the App here. Can you take a look?
> 
> If you run the example in the description, `session.view = view2` at the end shows an empty view, although the printing statements show that `view2` does contain person-only detections as expected.

My previous comment notes this. It is an issue with filter serialization. Things work in #793. I'm not sure it is worth getting it to work in this PR. I'll note that supporting both the deprecated classes and `FilterLabels` has made things quite messy.

**Comment by benjaminpkane** [comment]
Ok, fixed.

**Comment by brimoor** [comment]
> > Hey @benjaminpkane I think something is wrong with the App here. Can you take a look?
> > If you run the example in the description, `session.view = view2` at the end shows an empty view, although the printing statements show that `view2` does contain person-only detections as expected.
> 
> My previous comment notes this. It is an issue with filter serialization. Things work in #793. I'm not sure it is worth getting it to work in this PR. I'll note that supporting both the deprecated classes and `FilterLabels` has made things quite messy.

I'm still seeing the bug after pulling the latest changes, but nvm let's just let https://github.com/voxel51/fiftyone/pull/793 deal with it.

**Pull request merged**
