### PR TITLE
View bar reskin and logic updates

### PR DESCRIPTION
**Pull request by benjaminpkane**
## What changes are proposed in this pull request?

Ready for review.

Screenshot from 2020-09-01 14-53-28

Includes "autocomplete" in stages, an initial reskin pass, robust positions and z-index work for pop-out elements (JSON editor, error messages, search results, and more.

## How is this patch tested? If it is not, in a single sentence please explain why.

Locally.

### Is this a user-facing change?

-   [ ] No. You can skip the rest of this section.
-   [x] Yes. Give a description of this change to be included in the release
        notes for FiftyOne users.

Adds "autocomplete" in stages, and a new skin to the view bar. Scrolling behavior has been overhauled, as well.

### What areas of FiftyOne does this PR affect?

-   [x] `App`: FiftyOne application changes
-   [ ] `Build`: Build and test infrastructure changes
-   [ ] `Core`: Core `fiftyone` Python library changes
-   [ ] `Documentation`: FiftyOne documentation changes
-   [ ] `Other`

### Should this PR be mentioned in the release notes? If so, please choose on category:

-   [ ] `breaking-change` - The PR will be mentioned in the "Breaking Changes"
        section
-   [x] `feature` - A new user-facing feature worth mentioning in the release
        notes
-   [ ] `bug-fix` - A user-facing bug fix worth mentioning in the release notes
-   [ ] `documentation` - A user-facing documentation change worth mentioning
        in the release notes

### CODE REVIEW

**Comment by benjaminpkane** [comment]
This is ready for review. I'd like to test things more myself, but I welcome any comments/issues/suggestions.

**Comment by brimoor** [comment]
Lookin' good!! Per our conversation a second ago, here's a couple suggestions to enhance user experience of view bar:

**Autocomplete**
- It would be nice if the current match (ie, whatever will be selected based on autocomplete rules when ENTER is pressed) would be highlighted in the actual dropdown, for consistency with how it looks when you manually arrow through the options and then press ENTER). The rule could be:
    - Typing causes autocomplete to appear in the box and move the current selection in the dropdown to the best match
    - Pressing arrow keys changes the highlighted stage in the dropdown and updates the text in the box to exactly match the selected stage
- Related point: it may help with consistency to ALWAYS match based on `.startswith()` and never `.contains()`. The latter is a bit more powerful, but then it introduces some 

**Colors**
- When the view bar loses focus, deactivate the currently active stage in the view bar, if any. Goal is that the entire view bar is gray if it is not selected
- Only use one highlight color for the view bar. Pick orange or blue. This color would be used for all of the following (a) indicate active stage, (b) indicate active field within a stage (no need for second color) c) autocomplete text. Basically, everything about the currently active stage will be the highlight color, and everything else will be gray

**Bugs**
- Pressing ENTER on leftmost add stage element doesn't do anything (pressing ENTER on all other ones does create a stage, as expected)

**Misc**
- Pressing DEL/ESC on a stage with no stage type selected should delete the stage (EG pressing ENTER and then DEL/ESC on a `+` icon should create and then delete the stage). IDK if it should be DEL, ESC, or DEL/ESC, whatever is consistent with the current design

**Comment by lethosor** [comment]
Another color suggestion: could the buttons between stages be lighter? I find them a bit hard to see (I had to turn up my screen brightness a fair amount to make out the icons on these):
image

A minor issue: I was able to get the view bar into this state by clicking on the "x" on the far right when a text box was active. I think this might have occurred before, though. It's still functional, but the right border doesn't show up until a new stage is added.

image

**Comment by lethosor** [comment]
Fixes are looking good!

I ran into a weird issue with the `SortBy` stage - the "field" field is always orange: 

image

and clicking on it produces this:

image

Scrolling sideways in the view bar reverts to this state, which is then usable, but it took me a while to figure that out:

image

**Comment by benjaminpkane** [comment]
> Fixes are looking good!
> 
> I ran into a weird issue with the `SortBy` stage - the "field" field is always orange:
> 
> image
> 
> and clicking on it produces this:
> 
> image
> 
> Scrolling sideways in the view bar reverts to this state, which is then usable, but it took me a while to figure that out:
> 
> image
> 
> Update: this also occurs with `Mongo`, and presumably other stages that have a large text area like this.

Thanks, good catches. Should be easy fixes. The larger text editor parameters are separate components. I'd like to have them share more state/logic/styles but the patterns are still revealing themselves.

**Comment by lethosor** [comment]
The object editor (assuming that's what you're calling the big text area) looks good now!
I'm seeing a couple odd things now, not sure if you've addressed them:
* Clicking outside of a stage's type (e.g. "Limit") when editing it deletes the stage. Unsure if this is intentional, but it doesn't happen on develop.
* I'm having trouble selecting a stage type with just the keyboard (this overlaps with some of @brimoor's feedback above, so you might already be addressing this):
  * The first thing I tried, typing "lim", filled in an "it" in orange to the right of my cursor, and appears to select "limit" in the dropdown (at least, I can press the up arrow to unselect it in the dropdown), but pressing `enter` immediately gives a `lim is not a valid stage` error
   * pressing `tab` navigates away from the stage, which I guess is reasonable
   * pressing the down arrow replaces the contents of the field with "Limit", but hitting `enter` does not select it. Clicking on "Limit" in the dropdown is the only way I've found to actually select it from this state.

**Comment by benjaminpkane** [comment]
Most comments have been addressed. Thanks for helping with the details!

I'll be addressing the search logic (`contains` vs `startsWith`), and @lethosor's comment:

> * Clicking outside of a stage's type (e.g. "Limit") when editing it deletes the stage. Unsure if this is intentional, but it doesn't happen on develop.

Other than that, I believe everything has been addressed. Will be ready shortly.

**Comment by lethosor** [comment]
Yeah, the stage type selection feels a lot better to me now, thanks! Not seeing anything else that hasn't already been mentioned.

**Comment by benjaminpkane** [comment]
Okay, changes are in.

I took some liberties with respect to the `ESC` shortcut for stages. `ESC` (or any blur event) will now only delete a focused stage if it does not have parameters present. I removed the `x` button for stages when no parameters present because of this, which I think looks better.

**Comment by benjaminpkane** [comment]
@brimoor, many of your comments have been addressed in #509.

* Long strings for parameters are limited to 25 characters when the parameters is not being edited
* `Select`/`Exclude` accept comma separated values and array syntax values

I will be updating the placeholder text for parameters, e.g. `list,of,sample,ids`, but I'd like to leave it out of this PR.

**Review by lethosor — APPROVED** [review]
Looks good!

**Pull request merged**
