### PR TITLE
feature/multiple-pcd-overlay

### PR DESCRIPTION
**Pull request by sashankaryal**
## What changes are proposed in this pull request?
- Add ability to visualize multiple pcds in a group on top of each other
- Add ability to assign custom RGB color per pointcloud slice (colors are persisted using browser storage)
- Sync camera position in local storage so that it persists across samples and between page refreshes

gh-2-small

gh-1-small

Notes to the reviewer:
1. A lot more group refactoring incoming in the dynamic groups PR, so if possible, please turn on your "functional" mode here because most of the group code is refactored in the next PR
2. Modal sidebar work is pending and tracked in another PR that @benjaminpkane owns.

## How is this patch tested? If it is not, please explain why.

Locally, with three kinds of datasets: 
1. Pointcloud only dataset
3. Quickstart groups dataset (with one pointcloud slice)
4. Custom group dataset with multiple pointcloud slices per group

To create a custom dataset, the following code may be used:
```py
import fiftyone as fo
import fiftyone.zoo as foz

dataset = fo.Dataset()
qsg = foz.load_zoo_dataset("quickstart-groups", max_samples=12)

qsg_pngs = qsg.select_group_slices("left").clone()
qsg_pcds = qsg.select_group_slices("pcd").clone()

ground_truth_label = qsg_pcds.first()["ground_truth"]

g1 = fo.Group()
g1s1 = fo.Sample(filepath=qsg_pcds.first().filepath, group=g1.element("pcd1"))
g1s1["detections"] = ground_truth_label
g1s2 = fo.Sample(filepath=qsg_pcds.skip(1).first().filepath, group=g1.element("pcd2"))
g1s3 = fo.Sample(filepath=qsg_pngs.first().filepath, group=g1.element("png"))

g2 = fo.Group()
g2s1 = fo.Sample(filepath=qsg_pcds.skip(2).first().filepath, group=g2.element("pcd1"))
g2s1["detections"] = ground_truth_label
g2s2 = fo.Sample(filepath=qsg_pcds.skip(3).first().filepath, group=g2.element("pcd2"))
g2s3 = fo.Sample(filepath=qsg_pngs.skip(1).first().filepath, group=g2.element("png"))

samples = [g1s1, g1s2, g1s3, g2s1, g2s2, g2s3]

dataset.add_samples(samples)
dataset.default_group_slice = "png"
```

## Release Notes
-   [ ] No. You can skip the rest of this section.
-   [x] Yes. Give a description of this change to be included in the release
        notes for FiftyOne users.

### What areas of FiftyOne does this PR affect?

-   [x] App: FiftyOne application changes
-   [ ] Build: Build and test infrastructure changes
-   [ ] Core: Core `fiftyone` Python library changes
-   [x] Documentation: FiftyOne documentation changes
-   [ ] Other

### CODE REVIEW

**Comment by benjaminpkane** [comment]
Will leave comments, if any, before Monday!

**Comment by brimoor** [comment]
@sashankaryal @benjaminpkane on this branch the App seems to be ignoring `sidebar_mode=fast`. Sidebar stats always load. Can you patch this?

**Review by benjaminpkane — APPROVED** [review]
LGTM!

**Comment by brimoor** [comment]
@sashankaryal @benjaminpkane here's some things I saw when usability testing just now:

1. Can you update the verbiage here?
- `Select pcds` -> `Select point clouds`
- `pcd1 selected` -> `Showing pcd1`

Screen Shot 2023-05-05 at 11 21 34 AM

Screen Shot 2023-05-05 at 11 21 41 AM

2. When I refresh my browser, color settings for multiple slices are persisted as documented in the PR, but the PCD selection always resets to just one slice. Should we instead remember the slices that are currently being shown, for consistency with how everything else (I believe) is persisted?

3. I believe we should always be seeing detection count (7 in this case) appear in the sidebar when the modal is open. Unlike grid view, the modal does not care about sidebar mode. It should always show top-level counts.

I assume this is related to whatever bug caused the grid to not respect sidebar mode prior to @benjaminpkane's merge this AM

Screen Shot 2023-05-05 at 11 25 02 AM

4. Unrelated to this PR, but I noticed it: when the sidebar is in `group` stats mode, the checkbox next to `sample tags` should not appear. It correctly does not appear when in `slide` statistics mode

Screen Shot 2023-05-05 at 11 24 58 AM

5. nit: can you update `Toggle Media` tooltip to `Toggle media`?

Screen Shot 2023-05-05 at 11 23 15 AM

**Pull request merged**
