### PR TITLE
Tagging simplification and server tests

### PR DESCRIPTION
**Pull request by benjaminpkane**
Adds to server tests and improves the tagging implementation by sharing parameter generation between the tagging statistics that create the checkbox list and subsequent tagging calls.

### CODE REVIEW

**Comment by ehofesmann** [comment]
Clicking the tag icon in the modal for `quickstart-groups` is raising this error in this branch:
```
Traceback (most recent call last):
File "/home/eric/work/fiftyone/fiftyone/fiftyone/server/decorators.py", line 33, in wrapper
response = await func(endpoint, request, data, *args)
File "/home/eric/work/fiftyone/fiftyone/fiftyone/server/routes/tagging.py", line 55, in post
count_aggs, tag_aggs = build_label_tag_aggregations(view)
File "/home/eric/work/fiftyone/fiftyone/fiftyone/server/routes/tagging.py", line 88, in build_label_tag_aggregations
for field_name, field in view.get_frame_field_schema().items():
AttributeError: 'NoneType' object has no attribute 'items'
```

**Comment by ehofesmann** [comment]
Some of the help keys are duplicated
image

**Comment by benjaminpkane** [comment]
Addressed!

**Review by brimoor — APPROVED** [review]
LGTM

**Pull request merged**
