### PR TITLE
Update docs to mention builtin orchestrator

### PR DESCRIPTION
**Pull request by CamronStaley**
## What changes are proposed in this pull request?

Update docs to mention builtin orchestrator

### What areas of FiftyOne does this PR affect?

-   [ ] App: FiftyOne application changes
-   [ ] Build: Build and test infrastructure changes
-   [ ] Core: Core `fiftyone` Python library changes
-   [x] Documentation: FiftyOne documentation changes
-   [ ] Other

## Summary by CodeRabbit

- **New Features**
	- Added new sections: "Dataset Zoo" and "Model Zoo" in the documentation.
	- Introduced a section on "FiftyOne Teams Built-in Orchestrator" for managing delegated operations.
	- Enhanced documentation for plugin development with detailed guides and visual aids.
	- Added a new TimelineView for custom animations in the app.

- **Bug Fixes**
	- Clarified references to the orchestration tool in various documentation sections.
	- Fixed various issues related to overlay z-index and performance improvements in the app.

- **Documentation**
	- Expanded and refined existing sections for clarity and usability.
	- Streamlined setup instructions for the built-in orchestrator in the Teams context.
	- Updated release notes with enhancements and fixes across different components.

### CODE REVIEW

**Review by brimoor — APPROVED** [review]
Added some more updates and now LGTM

**Review by swheaton — DISMISSED** [review]
I have changes locally, do not merge

**Comment by swheaton** [comment]
Although if BM is good with it as exists now maybe I'll just throw my changes away and move on.

**Review by swheaton — APPROVED** [review]
lgtm, defer to product

**Pull request merged**
