### PR TITLE
adding the ability to use any device trough parameter + apple's MPS automatic check

### PR DESCRIPTION
**Pull request by timmermansjoy**
## What changes are proposed in this pull request?

added the functionality to do inference on the GPU on apple devices with the [metal backend in pytorch](https://pytorch.org/blog/introducing-accelerated-pytorch-training-on-mac/)

(Please fill in changes proposed in this fix)

changed up the `_using_gpu` so it also checks for cuda and mps and then after also make the images go to `self._device` instead of going to `cuda()` directly

## How is this patch tested? If it is not, please explain why.

tested on some models in the zoo, I can not test if it conflicts on other devices 

(Details)

## Release Notes

for Mac users have the ability to utilise more of their available hardware by utilising the MPS backend

### Is this a user-facing change that should be mentioned in the release notes?

-   [x] No. You can skip the rest of this section.
-   [ ] Yes. Give a description of this change to be included in the release
        notes for FiftyOne users.

(Details in 1-2 sentences. You can just refer to another PR with a description
if this PR is part of a larger change.)

### What areas of FiftyOne does this PR affect?

-   [ ] App: FiftyOne application changes
-   [ ] Build: Build and test infrastructure changes
-   [ ] Core: Core `fiftyone` Python library changes
-   [ ] Documentation: FiftyOne documentation changes
-   [ ] Other

### CODE REVIEW

**Comment by timmermansjoy** [comment]
Because not all ops are implemented yet, the code should be run with [PYTORCH_ENABLE_MPS_FALLBACK=1](https://stackoverflow.com/questions/72416726/how-to-move-pytorch-model-to-gpu-on-apple-m1-chips) but I have not found a way to do so and that is why its a [WIP]

**Comment by timmermansjoy** [comment]
Maybe this is useless because after some speed testing, the MPS implementation makes it slower, Don't really know why tho? maybe batch size is too small for it to be utilised? I found the following about it: https://github.com/pytorch/pytorch/issues/77799



Screenshot 2023-03-27 at 10 43 55

Screenshot 2023-03-27 at 10 46 14


Screenshot 2023-03-27 at 10 47 56

**Comment by Rusteam** [comment]
is there any update on this?

**Comment by timmermansjoy** [comment]
@Rusteam I want some discussion around this. since in my testing it is not always faster and it can give worse results and some models don't work with it where you would have to run it with [PYTORCH_ENABLE_MPS_FALLBACK=1](https://stackoverflow.com/questions/72416726/how-to-move-pytorch-model-to-gpu-on-apple-m1-chips) but I don't know how you can run that inside the library

**Comment by Rusteam** [comment]
Maybe we should test with simple models that do run on mps like resnet50? I can also try running it on my Mac to see if there's any improvement.

**Comment by timmermansjoy** [comment]
@Rusteam yea you try it out yourself. I tested it on my M2 max. I do have an older laptop laying around with a rx560 in so I could test it with apple gpu vs AMD gpu. 

the changes I have made should enough to run all models with MPS. let me know what your finds are aswel maybe there have been some provements and I will do some more testing this weekend if you find its good

**Comment by timmermansjoy** [comment]
also, just to be clear. the examples I shared was with the default `mobilenet-v2-imagenet-torch` network. that's a pretty light simple model. while being 30% slower with mps then cpu

**Comment by Rusteam** [comment]
Is there a flag to set to disable mps (and use cpu only)? If you can add it, I'll definitely complete this task much sooner

**Comment by timmermansjoy** [comment]
@Rusteam No there isn't what I have done is just keep the torch file open. add another device="cpu" there and then just comment / uncomment that one out. If you are using Jupyter notebooks you should add:
```py
%load_ext autoreload
%autoreload 2
```

at the top and then your changes will have instant effect and you can just run the cells.

**Comment by Rusteam** [comment]
MPS definitely makes most standard models faster. I've actually trained efficientnet-b0 for image classifcation and yolov5 for detection on MPS and it was pretty fast.

With fiftyone models zoo using MPS also makes a lot of sense. 
I've run an image classification and an object detection model on the quickstart dataset
both on CPU and MPS for about 200 samples. These are my results:
|Device|Model|Samples/s|
|---|---|---|
|MPS|resnet 18|25.1|
|MPS|deeplabv3-resnet50|4.3|
|CPU|resnet 18|17.0|
|CPU|deeplabv3-resnet50|1.3|

**Comment by Rusteam** [comment]
> @Rusteam interesting. could you share your code maybe? I will run it on my machines aswell. I will also do some more testing then and I will add the parameter of device so people can still fallback to using CPU if the model gives issues

I just checked out your branch and ran this:
```
fiftyone zoo models apply resnet18-imagenet-torch quickstart resnet18
fiftyone zoo models apply deeplabv3-resnet50-coco-torch quickstart deeplabv3-resnet50
```

and then once again on the default branch to do it on CPU only.

**Comment by brimoor** [comment]
With respect to how to expose this feature, you are welcome to add an optional `device` parameter to [TorchImageModelConfig](https://github.com/voxel51/fiftyone/blob/82b256322549de3e17870b332af70e1eeabc225e/fiftyone/utils/torch.py#L93).

It could support:
- `device="cpu|cuda:0"`. Any string to pass to `torch.device(device)`
- `device="mps"`
- `device=None`, maintain the [current behavior](https://github.com/voxel51/fiftyone/blob/82b256322549de3e17870b332af70e1eeabc225e/fiftyone/utils/torch.py#L227) for backwards compatibility

**Comment by timmermansjoy** [comment]
Tnx will have a shot at it

**Comment by timmermansjoy** [comment]
Okay yea I guess its good enough for now, people can experiment with the device parameters or fall back on that if the device is not supported like the CLIP model (this was a older branch maybe the model got fixed already).

Unless it would be preferred to have CPU be the default and only pass in parameter device to make models always work / not cause breaking changes down the road. I see this PR as good enough for now with still having future improvements planned but those can be in other PR's

This PR gives performance improvements on the Quickstart dataset:

| Model                                 |  cpu_time | mps_time 1st time | mps_time 7 time avrage |                                                                                                                                                     improvement |
| ------------------------------------- | --------: | ----------------: | ---------------------: | --------------------------------------------------------------------------------------------------------------------------------------------------------------: |
| resnet18-imagenet-torch               |  10.2 sec |           8.0 sec |                2.4 sec |                                                                                                                                                           4.25x |
| densenet161-imagenet-torch            |  54.4 sec |         180.0 sec |               14.1 sec |                                                                                                                                                            3.8x |
| clip-vit-base32-torch                 |  40.2 sec |                -- |                     -- |                                                                                                                                            could not run on mps |
| keypoint-rcnn-resnet50-fpn-coco-torch | 175.4 sec |                -- |                     -- | The operator 'torchvision::nms' is not currently supported on the MPS backend Error: [srcBuf length] > 0 INTERNAL ASSERT FAILED at "/mps/OperationUtils.mm":283 |
| vgg16-bn-imagenet-torch               |  56.7 sec |                -- |                     -- |                                                                                        Error: Adaptive pool MPS: input sizes must be divisible by output sizes. |
| wide-resnet101-2-imagenet-torch       |  63.1 sec |          23.1 sec |                    8.7 |                                                                                                                                                            7.8x |


thanks @Rusteam and @brimoor for the help

**Comment by Rusteam** [comment]
I'd also add an env variable like `FIFTYONE_DISABLE_MPS=False` for scenarios when we run models from cli and they're not supported on mps. If set to True, then we can bypass that PyTorch error that some ops are not implemented on mps.

**Comment by timmermansjoy** [comment]
@Rusteam I would suggest a FO_DEVICE env instead? since otherwise its going to explode with potential future hardware / devices

**Comment by Rusteam** [comment]
yep that's another way of achieving it.

**Comment by Rusteam** [comment]
I guess you can ignore it for now as there's a native PyTorch env variable to fall back to cpu.

**Review by benjaminpkane — APPROVED** [review]
LGTM! 🙌  Thanks @timmermansjoy. Pardon the delay

I want to follow up with other team members about whether `mps` should be used optimistically. Regardless `device="mps"` will be in the next release

**Pull request merged**
