### PR TITLE
Fix modal popout widths

### PR DESCRIPTION
**Pull request by benjaminpkane**
Adds the `useAlign` hook to `left` aligned popouts for the grid, and `right` aligned popouts for the modal.

Before:
Screen Shot 2023-09-01 at 2 00 15 PM
After:
Screen Shot 2023-09-01 at 2 04 26 PM

### CODE REVIEW

**Comment by benjaminpkane** [comment]
Will tweak this. Modal should be right aligned

**Comment by benjaminpkane** [comment]
Also did some cleanup to `Popout`. `bounds` and `mRef` have no effect, so I found it worthwhile to remove

**Comment by sashankaryal** [comment]
lgtm

**Review by sashankaryal — APPROVED** [review]
lgtm. right align works correctly in the modal 🥳

**Pull request merged**
