### PR TITLE
Prevent receding loading state on empty page transition

### PR DESCRIPTION
**Pull request by benjaminpkane**
Removes a small pixelating state flicker when navigating from the empty dataset page. Wondering if this change is ok @imanjra?

## Before

https://github.com/voxel51/fiftyone/assets/19821840/4a81fdc4-e385-4a70-a388-c45d9818aae9

## After

https://github.com/voxel51/fiftyone/assets/19821840/6887fa01-560f-41ad-a3b0-94b186fdd797

### CODE REVIEW

**Comment by imanjra** [comment]
@benjaminpkane Unfortunately, this will undo the synchronization of placement loading (https://github.com/voxel51/fiftyone/pull/3793). There are couple of other options I considered as an alternative to global Pixelating state. One of them was moving the pixelating state downward to Spaces container where sidebar would load and sample would say Pixelating... until placements are loaded. 


_Unrelated: thoughts on replacing `Pixelating...` screen with actual pixel like sample panel?_

**Comment by benjaminpkane** [comment]
Adding the dataset operators to the GraphQL page query would be ideal. But in the meantime, I will add the operators request to the page query `subscribe`  function in `@fiftyone/relay` in this PR for initialization. Converting to draft for now

Falling pixels could be cool 👍 can take offline

**Review by sashankaryal — APPROVED** [review]
lgtm

**Comment by benjaminpkane** [comment]
Closing for now

**Pull request closed without merging**
