### PR TITLE
[HOLD] Label studio integration adds annotations backwards

### PR DESCRIPTION
**Pull request by stobias123**
## What changes are proposed in this pull request?

I noticed after importing a bunch of pre-annotated files, the annotations were being attached to the files in backwards order. 

This PR fixes that and attaches annotations to the correct image.

## How is this patch tested? If it is not, please explain why.
On label studio `1.7.2`

### What areas of FiftyOne does this PR affect?

-   [ ] App: FiftyOne application changes
-   [ ] Build: Build and test infrastructure changes
-   [x] Core: Core `fiftyone` Python library changes
-   [ ] Documentation: FiftyOne documentation changes
-   [ ] Other

### CODE REVIEW

**Review by ehofesmann — COMMENTED** [review]
Thanks for the PR @stobias123 ! 
I am not able to reproduce the original issue on label studio v1.7.2 using the quickstart dataset (`dataset = foz.load_zoo_dataset("quickstart", max_samples=5)`).

This PR seems to result in the annotations being reversed. Would you be able to share a reproducible example of when you see the annotations being added backwards? It may be a bit more nuanced (for example based on filenames or something)

**Comment by stobias123** [comment]
Sure here's my full code
```
    ds = fo.load_dataset(dataset_name)
    view = ds.load_saved_view(view_name)
    complete = view.exists("gt_detections")
    view = view.exclude(complete)
    print('View filtered to {} samples'.format(len(view)))
    view = view.take(take)
    view = view.sort_by('id')
    print('Sending {} samples to label studio'.format(len(view)))
    #view.compute_metadata()

    def random_hex_string():
        return ''.join(random.choice(string.hexdigits) for _ in range(16))
    id = random_hex_string()
    anno_key = f"{dataset_name.replace('-','_').replace('/','_')}_label_run_{id}"
        label_schema = {
        "pred_detections": {
            "type": "detections",
            "classes": classes
        },
    }

    view.annotate(
        anno_key,
        backend="labelstudio",
        label_schema=label_schema,
    )
    ```
    
    Continues to be an issue for me :(

**Comment by stobias123** [comment]
Sure here's my full code
```
    ds = fo.load_dataset(dataset_name)
    view = ds.load_saved_view(view_name)
    complete = view.exists("gt_detections")
    view = view.exclude(complete)
    print('View filtered to {} samples'.format(len(view)))
    view = view.take(take)
    view = view.sort_by('id')
    print('Sending {} samples to label studio'.format(len(view)))
    #view.compute_metadata()

    def random_hex_string():
        return ''.join(random.choice(string.hexdigits) for _ in range(16))
    id = random_hex_string()
    anno_key = f"{dataset_name.replace('-','_').replace('/','_')}_label_run_{id}"
        label_schema = {
        "pred_detections": {
            "type": "detections",
            "classes": classes
        },
    }

    view.annotate(
        anno_key,
        backend="labelstudio",
        label_schema=label_schema,
    )
    ```
    
    Continues to be an issue for me :(

**Comment by stobias123** [comment]
closing - I dont seem to have this issue any more, probably something weird I did along the way

**Pull request closed without merging**
