### PR TITLE
Fix image map keys when using subset/subdirectory in cvat dataset

### PR DESCRIPTION
**Pull request by bartonp2**
## What changes are proposed in this pull request?

This simply includes the subset parameter of each image entry of a cvat dataset, in addition to its filename. The subset was already used in the _image_paths_map of the dataset, but not in the _cvat_images_map. This led to key errors when trying to retrieve an item.

This pull requests makes the _image_paths_map and _cvat_images_map consistent avoiding runtime errors when trying to read a cvat dataset with subdirectories.

## How is this patch tested? If it is not, please explain why.

This was tested on a local project.

### Is this a user-facing change that should be mentioned in the release notes?

-   [x] No. You can skip the rest of this section.
-   [ ] Yes. Give a description of this change to be included in the release
        notes for FiftyOne users.

(Details in 1-2 sentences. You can just refer to another PR with a description
if this PR is part of a larger change.)

### What areas of FiftyOne does this PR affect?

-   [ ] App: FiftyOne application changes
-   [ ] Build: Build and test infrastructure changes
-   [x] Core: Core `fiftyone` Python library changes
-   [ ] Documentation: FiftyOne documentation changes
-   [ ] Other

### CODE REVIEW

**Comment by benjaminpkane** [comment]
Hi @bartonp2 :wave:

It looks like a unit test is failing
```
tests/unittests/import_export_tests.py::MultitaskImageDatasetTests::test_cvat_image_dataset
```

**Comment by brimoor** [comment]
@bartonp2 Thanks for the PR! I think the reason the tests are currently failing is that, per [our CVAT import docs](https://voxel51.com/docs/fiftyone/user_guide/dataset_creation/datasets.html#cvatimagedataset), we're expecting a CVAT XML like this:

```
<image id="0" name="<uuid1>.<ext>" width="640" height="480">
    <box label="car" xtl="100" ytl="50" xbr="325" ybr="190" occluded="0">
        <attribute name="type">sedan</attribute>
        ...
    </box>
    ...
</image>
```

with no `subset` key.

Instead, it is currently implemented such that, if the corresponding images are arranged in subfolders like so:

```
data_path/
    <uuid1>.<ext>
    path/
        to/
            subfolder/
                <uuid2>.<ext>
    ...
```

Then the XML should contain this:

```
<image id="0" name="<uuid1>.<ext>" width="640" height="480">
    ...
</image>
<image id="1" name="path/to/subfolder/<uuid2>.<ext>" width="640" height="480">
    ...
</image>
```

I'm not familiar with the `subset` key in CVAT's data model, but, for backwards compatibility with our current assumptions, I think you can just update to `d.get("subset", None)` and then only join onto "name"` if the subset syntax was used.

**Comment by bartonp2** [comment]
Hi @brimoor 

Yes I agree. Came to the same conclusion just now.

This subset key appeared when I exported the whole project from cvat, rather than just a task. This is a new feature introduced in their latest release which may explain the inconsistency.

**Comment by ehofesmann** [comment]
Just FYI, the subset parameter appears to also exist when exporting tasks but is just set to `default`. There should likely be a check to see if `subset` is `default` to avoid joining it to the `"name"`.

```
<?xml version="1.0" encoding="utf-8"?>
<annotations>
  <version>1.1</version>
  <meta>
    <task>
      <id>119059</id>
      <name>test3</name>
      <size>1</size>
      <mode>annotation</mode>
      <overlap>0</overlap>
      <bugtracker></bugtracker>
      <created>2021-09-09 14:50:11.115141+01:00</created>
      <updated>2021-09-09 14:50:29.196097+01:00</updated>
----  <subset>default</subset> ----
      <start_frame>0</start_frame>
      <stop_frame>0</stop_frame>
      <frame_filter></frame_filter>
      <segments>
        <segment>
          <id>199878</id>
          <start>0</start>
          <stop>0</stop>
          <url>http://cvat.org/?id=199878</url>
        </segment>
      </segments>
      <owner>
      </owner>
      <assignee></assignee>
      <labels>
        <label>
          <name>test</name>
          <color>#8f95c0</color>
          <attributes>
          </attributes>
        </label>
      </labels>
    </task>
    <dumped>2021-09-09 14:50:42.416702+01:00</dumped>
  </meta>
  <image id="0" name="000000001371.jpg" width="640" height="480">
    <box label="test" occluded="0" source="manual" xtl="119.38" ytl="77.13" xbr="351.15" ybr="253.06" z_order="0">
    </box>
  </image>
</annotations>
```

**Comment by bartonp2** [comment]
Hm this is annoying since the subset was also called "default" in my export, where the images where actually located in a subdirectory called "default".

Upon testing when exporting only a single task, I do not get the "subset" field in contrast to @ehofesmann

**Comment by bartonp2** [comment]
Ah after some confusion I realised that the "subset" parameter @ehofesmann is referring to is under the metadata and is a different one.

The "subset" parameter causing the problems is however under the "image" tag like so:

```
  <image id="217" name="frame_000217.PNG" subset="default" task_id="88400" width="2448" height="2048">
    <polygon label="plan" occluded="0" source="manual" points="1643.00,468.00;1628.00,469.00;1613.00,470.00;1603.00,472.00;1591.00,473.00;1580.00,474.00;1565.00,474.00;1554.00,475.00;1548.00,476.00;1537.00,478.00;1532.00,479.00" z_order="0">
    </polygon>
    <points label="earth" occluded="0" source="manual" points="1720.19,1359.85;761.00,1272.65;548.90,1574.31" z_order="0">
    </points>
  </image>
```

**Comment by ehofesmann** [comment]
Right! To clarify, CVAT released a new version last month that provided the ability to export entire projects rather than just tasks. Since data can be stored in a variety of custom "subsets" within a project, these subsets are now being written to the exported `XML`. 

However, since all images in a task are within the same subset, when exporting a dataset from just a task, the image-level `subset` parameter does not appear but it is still stored in the task metadata.

For reference, the previous XML block I shared was exported for a single task, this is exported from a project containing two tasks in two different subsets:
```
<?xml version="1.0" encoding="utf-8"?>
<annotations>
  <version>1.1</version>
  <meta>
    <project>
      <id>9065</id>
      <name>example_project</name>
      <bugtracker></bugtracker>
      <created>2021-06-10 15:00:15.832031+01:00</created>
      <updated>2021-06-10 15:00:15.832062+01:00</updated>
      <tasks>
        <task>
          <id>119071</id>
          <name>testnosub</name>
          <size>1</size>
          <mode>annotation</mode>
          <overlap>0</overlap>
          <bugtracker></bugtracker>
          <created>2021-09-09 15:20:42.397091+01:00</created>
          <updated>2021-09-09 15:21:05.627229+01:00</updated>
          <subset>default</subset>
          <start_frame>0</start_frame>
          <stop_frame>0</stop_frame>
          <frame_filter></frame_filter>
          <segments>
            <segment>
              <id>199884</id>
              <start>0</start>
              <stop>0</stop>
              <url>http://cvat.org/?id=199884</url>
            </segment>
          </segments>
          <owner>
          </owner>
          <assignee></assignee>
        </task>
        <task>
          <id>119058</id>
          <name>test</name>
          <size>1</size>
          <mode>annotation</mode>
          <overlap>0</overlap>
          <bugtracker></bugtracker>
          <created>2021-09-09 14:46:17.955714+01:00</created>
          <updated>2021-09-09 14:46:39.154608+01:00</updated>
          <subset>Train</subset>
          <start_frame>0</start_frame>
          <stop_frame>1</stop_frame>
          <frame_filter></frame_filter>
          <segments>
            <segment>
              <id>199877</id>
              <start>0</start>
              <stop>1</stop>
              <url>http://cvat.org/?id=199877</url>
            </segment>
          </segments>
          <owner>
          </owner>
          <assignee></assignee>
        </task>
      </tasks>
      <labels>
        <label>
          <name>banana</name>
          <color>#80c080</color>
          <attributes>
          </attributes>
        </label>
      </labels>
      <owner>
      </owner>
      <assignee></assignee>
    </project>
    <dumped>2021-09-09 15:22:25.615784+01:00</dumped>
  </meta>
  <image id="0" name="000000000036.jpg" subset="default" task_id="119071" width="481" height="640">
  </image>
  <image id="0" name="000000000001.jpg" subset="Train" task_id="119058" width="640" height="480">
  </image>
</annotations>
```

**Comment by ehofesmann** [comment]
Another likely issue that the current template does not account for projects at all and may have trouble reading the exported project XML in the first place.

**Comment by bartonp2** [comment]
> Another likely issue that the current template does not account for projects at all and may have trouble reading the exported project XML in the first place.

This is what this patch aims to fix. By implementing the changes @brimoor suggested I think this should work fine.

**Comment by brimoor** [comment]
> Another likely issue that the current template does not account for projects at all and may have trouble reading the exported project XML in the first place.

[This](https://github.com/voxel51/fiftyone/blob/develop/fiftyone/resources/cvat_image_annotation_template.xml) is only used for export. For import, [this](https://github.com/voxel51/fiftyone/blob/a2e000a85e3421998f9c7ec2cbab045ca9581f53/fiftyone/utils/cvat.py#L4481-L4533) just needs to find the appropriate keys.

**Comment by brimoor** [comment]
@ehofesmann what would the corresponding change for CVAT video datasets look like here?

**Comment by ehofesmann** [comment]
> @ehofesmann what would the corresponding change for CVAT video datasets look like here?

**Note**: Only one video per task is supported and when exported, all frames are downloaded as images.

### If exported as `CVAT for Images 1.1`
Every frame is a separate image and the format matches the image exports (`subset` only exists when exporting the project, not individual tasks)

### If exported as `CVAT for Videos 1.1`
Only tracks are exported but it seems to work similarly to images. If a project is exported then the `subset` will be specified in the annotation tracks, otherwise it is excluded.

```
<?xml version="1.0" encoding="utf-8"?>
<annotations>
  <version>1.1</version>
...
  <track id="0" label="test" source="manual" task_id="119121" subset="Test">
    <box frame="0" outside="0" occluded="0" keyframe="1" xtl="129.45" ytl="87.66" xbr="297.24" ybr="214.79" z_order="0">
    </box>
    <box frame="1" outside="0" occluded="0" keyframe="0" xtl="129.45" ytl="87.66" xbr="297.24" ybr="214.79" z_order="0">
    </box>
  </track>
  <track id="1" label="test" source="manual" task_id="119119" subset="default">
    <box frame="0" outside="0" occluded="0" keyframe="1" xtl="152.64" ytl="53.02" xbr="390.33" ybr="245.82" z_order="0">
    </box>
    <box frame="1" outside="1" occluded="0" keyframe="1" xtl="152.64" ytl="53.02" xbr="390.33" ybr="245.82" z_order="0">
    </box>
  </track>
</annotations>
```

**Review by ehofesmann — APPROVED** [review]
Thanks for this @bartonp2! 
I'll make a separate PR for video `subset` support.

**Pull request merged**
