### PR TITLE
CTA for embeddings and model evaluation

### PR DESCRIPTION
**Pull request by imanjra**
## What changes are proposed in this pull request?

Add CTA for embeddings and model evaluation panel

## How is this patch tested? If it is not, please explain why.

Using embeddings and model evaluation panel

### Is this a user-facing change that should be mentioned in the release notes?

-   [x] No. You can skip the rest of this section.
-   [ ] Yes. Give a description of this change to be included in the release
        notes for FiftyOne users.

(Details in 1-2 sentences. You can just refer to another PR with a description
if this PR is part of a larger change.)

### What areas of FiftyOne does this PR affect?

-   [x] App: FiftyOne application changes
-   [ ] Build: Build and test infrastructure changes
-   [ ] Core: Core `fiftyone` Python library changes
-   [ ] Documentation: FiftyOne documentation changes
-   [ ] Other

## Release Notes

- **New Features**
  - Introduced `PanelCTA` component for customizable call-to-action panels.
  - Added `EmbeddingsCTA` component for enhanced user interaction with embeddings.
  - New button functionality in `Embeddings` component for conditional actions based on application mode.

- **Improvements**
  - Enhanced `MuiButton` with dynamic styling options for different variants.
  - Updated layout and styling for several components to improve user experience.
  - Introduced new `useFirstExistingUri` hook for streamlined URI handling.

- **Removals**
  - Removed `EmptyOverview` and `EmptyEmbeddings` components to streamline the codebase.

- **Constants**
  - Added new constants for demo links and application mode identification.

### CODE REVIEW

**Comment by ritch** [comment]
We should handle these sort of panel dimensions:

image

**Comment by ritch** [comment]
image

Text centering is lost on smaller widths.

**Review by ritch — CHANGES_REQUESTED** [review]
Need to fix min-dimensions issues in comments.

**Review by brimoor — DISMISSED** [review]
LGTM

**Comment by imanjra** [comment]
@ritch fixed both width and height to be more adaptive. Please take another look.

**Review by ritch — APPROVED** [review]

**Pull request merged**
