### PR TITLE
Convert to mixed view for group datasets when making optimized sample collection

### PR DESCRIPTION
**Pull request by benjaminpkane**
When selecting multiple samples across slices in a group dataset in the modal, converting to a flat view ensures all samples are matched and no lookup occurs after the selection.

Supporting e2e and unit tests for `make_optimized_select_view` from @manivoxel51 and I will validate this change

### CODE REVIEW

**Comment by manivoxel51** [comment]
> When selecting multiple samples across slices in a group dataset in the modal, converting to a flat view ensures all samples are matched and no lookup occurs after the selection.
> 
> Supporting e2e and unit tests for `make_optimized_select_view` from @manivoxel51 and I will validate this change

@benjaminpkane I pulled this branch seeing a crash when clicking on Tagger
```
  File "/Users/maniaskari/code/fiftyone/fiftyone/server/decorators.py", line 29, in wrapper
    response = await func(endpoint, request, data, *args)
  File "/Users/maniaskari/code/fiftyone/fiftyone/server/routes/tagging.py", line 35, in post
    view = fost.get_tag_view(
  File "/Users/maniaskari/code/fiftyone/fiftyone/server/tags.py", line 39, in get_tag_view
    view = fov.make_optimized_select_view(view, sample_ids)
  File "/Users/maniaskari/code/fiftyone/fiftyone/core/view.py", line 1788, in make_optimized_select_view
    view = view._add_view_stage(stage, validate=False)
  File "/Users/maniaskari/code/fiftyone/fiftyone/core/view.py", line 1610, in _add_view_stage
    media_type = stage.get_media_type(self)
  File "/Users/maniaskari/code/fiftyone/fiftyone/core/stages.py", line 4581, in get_media_type
    if slices not in group_media_types:
TypeError: argument of type 'NoneType' is not iterable
```
trying to wrap my head around what's going on

**Comment by benjaminpkane** [comment]
If sample ids are defined, the group element filter should not be used. For clarity, I think the frontend should also account for this, i.e. not include the `groupId` and `slices` in the tagging payloads. I pushed a tweak for the backend which fixes it

**Comment by manivoxel51** [comment]
@benjaminpkane I added a unit test! lmk what you think 
we will add the e2e separately since this was purely a backend issue. Lanny is cooking some Tagger Poms last I heard 😄

**Review by benjaminpkane — COMMENTED** [review]
LGTM. I might add more coverage to optimized selection in another PR

Python tests are failing, but it is unrelated

**Pull request merged**
