### PR TITLE
[Operators] unit tests for coroutine timeout

### PR DESCRIPTION
**Pull request by kaixi-wang**
just adding unit tests

### CODE REVIEW

**Comment by swheaton** [comment]
And why do we want to prevent cancellation?

**Comment by kaixi-wang** [comment]
> And why do we want to prevent cancellation?

annotation plugin throwing cancellation errors. still want/need to test locally with the plugin though

**Comment by swheaton** [comment]
I feel like that's from the multiprocessing and we should fix that not hide it

**Comment by kaixi-wang** [comment]
on second thought, yeah your right. Shielding would just make debugging harder... removed the shield, but it wouldn't hurt to keep the tests.

**Review by ritch — APPROVED** [review]

**Pull request merged**
