### PR TITLE
Docs images

### PR DESCRIPTION
**Pull request by ehofesmann**
Added gif to docs overview.

Update images for tutorials and recipes to show the new App. The `evaluating object detections` tutorial has not been updated due to this error: https://github.com/voxel51/fiftyone/issues/448. There will be a separate PR for that walkthrough that modifies it to use fewer images to avoid this error and so that you don't have to run inference on the entire dataset.

There were minor changes to `model_inference.ipynb` and `label_deduplication.ipynb` where the sorting operation required a ViewField.

### CODE REVIEW

**Comment by brimoor** [comment]
> Reverting is not enough to keep the image out of the repo - if you want to cut down on repo size, you'll need to rebase this branch to get rid of the image from the history entirely.

Of course. But now it won't be in the build. We will purge all images from the repo's history once we have a solution in-place for hosting the images externally

**Comment by lethosor** [comment]
Eric gave me the go-ahead to rebase this. This image is particularly large so I'd like to purge it from the history sooner.

**Comment by brimoor** [comment]
go for it

**Comment by ehofesmann** [comment]
I like the idea of hosting on YouTube. I don't think that gifs are the right option for videos any longer than a few seconds anyway, the filesize gets pretty big compared to something like `.mp4`. 

@brimoor, could the regression that caused the `F("ground_truth.label")` issue possibly have something to do with the sorting problems I ran in to? It may have been running out of memory because it needed to make a new field when sorting.

**Comment by brimoor** [comment]
> @brimoor, could the regression that caused the `F("ground_truth.label")` issue possibly have something to do with the sorting problems I ran in to? It may have been running out of memory because it needed to make a new field when sorting.

I don't think so; the new field must resolve to a simple string, int, etc. that is sortable, so it doesn't add much space. The issue is that the entire documents need to be sorted, which can be big if they all contain 100+ detections.

But, I can't explain why you're seeing errors now but didn't see them before. 🤷‍♂️ Bottom line, we'll have to investigate. The idea of adding an index to support sorting is a good one, I think.

**Pull request merged**
