### PR TITLE
App bug reports

### LINKED ISSUE #2110: [BUG] Shift selecting samples not working in App
When you click on a sample in the grid and hold shift to select a range of samples, it is currently not selecting any between the first and last click.

range_selection

### LINKED ISSUE #2111: [BUG] App timezone issues
I'm noticing two small issues when working with timezones:
1. App doesn't respond to setting `fo.config.timezone = None` in a session
2. App doesn't understand `timezone = "local"`

```py
from datetime import date, datetime, timedelta

import fiftyone as fo
import fiftyone.zoo as foz
from fiftyone import ViewField as F

dataset = foz.load_zoo_dataset("quickstart").select_fields().clone()

ref_date = date.today()
ref_dt = datetime.utcnow()

for idx, sample in enumerate(dataset):
    sample["dates"] = ref_date - timedelta(days=idx)
    sample["datetimes"] = ref_dt - timedelta(hours=idx)
    sample.save()

###################################################
# BUG 1
###################################################

print(fo.config.timezone)
# None -> defaults to UTC time

# I should see UTC times
print(dataset.first())
session = fo.launch_app(dataset)  # BUG: `datetimes` slider shows local time, not UTC

###################################################
# BUG 2
###################################################

fo.config.timezone = "US/Eastern"
dataset.reload()

# I see my local time now
print(dataset.first())
session.refresh()  # BUG: doesn't cause App to refresh

###################################################
# BUG 3 (now fixed)
###################################################

fo.config.timezone = None
dataset.reload()

# I should see UTC again
print(dataset.first())  # correct: UTC
session.refresh()  # BUG: still local

###################################################
# BUG 4
###################################################

fo.config.timezone = "local"
dataset.reload()

# I should see my local time
print(dataset.first())  # correct: local
session.refresh()  # ERROR: label overlays in App grid don't work; App doesn't understand local
```

### LINKED ISSUE #2112: [BUG] Range sliders format datetime values incorrectly
The range slider uses a different formatting method, which currently has a bug that causes the configured timezone to not be set.

### LINKED ISSUE #2121: [BUG] Unselecting a field in the sidebar doesn't prevent tagging
In the App, when you unselect a label field and tag selected samples, then it tags all labels in all label fields, even ones that aren't selected.

For example, if you unselect `predictions` in the quickstart dataset, the tag the ground truth of the first sample, the `Labels` text changes from `+ tag 17 selected labels` to `+ tag 3 selected labels` as you untag the `predictions` field. 
image

But actually applying this tag doesn't just apply it to the 3 selected labels in the ground truth, it applies it to all 17 in ground truth and predictions for that sample.
image

### PR DESCRIPTION
**Pull request by benjaminpkane**
### Issues
* Resolves #2112 
* Resolves #2110 
* Resolves #2111 
* Resolves #2121

### CODE REVIEW

**Comment by brimoor** [comment]
(don't think we need to release imminently for this)

**Comment by brimoor** [comment]
@benjaminpkane still WIP or want a review on this?

**Review by brimoor — CHANGES_REQUESTED** [review]
@benjaminpkane confirmed that tagging/shift selection is working again, but I'm still seeing the timezone errors as described in this issue (updated to reflect my observations when I ran through it):

https://github.com/voxel51/fiftyone/issues/2111

**Comment by benjaminpkane** [comment]
Timezone issues addressed

**Review by brimoor — APPROVED** [review]
LGTM.

One usability thing that I don't believe I previously saw is that the datetime tooltips cover up the sliders, which would make it difficult for a new user to realize they can filter:

Screen Shot 2022-10-27 at 5 33 13 PM

**Comment by brimoor** [comment]
> One usability thing that I don't believe I previously saw is that the datetime tooltips cover up the sliders, which would make it difficult for a new user to realize they can filter:

Ah must be due to the theming updates that were merged in (unrelated to this PR)

**Pull request merged**
