### PR TITLE
App sidebar mode and optimizations

### PR DESCRIPTION
**Pull request by benjaminpkane**
### Change log

- Significantly optimizes the performance of the sidebar by lazily computing statistics only for currently visible fields
- Added new sidebar modes `all|best|fast` with updated default behavior that further optimizes the performance of the App for large datasets
- Added support for configuring the sidebar mode dynamically in the App and programmatically on a per-dataset basis
- Added support for programmatically configuring sidebar groups and default expansion states on a
  per-dataset basis

### Issues resolved

* Resolves https://github.com/voxel51/fiftyone/issues/1270
* Resolves https://github.com/voxel51/fiftyone/issues/2255
* Resolves https://github.com/voxel51/fiftyone/issues/2244

### CODE REVIEW

**Comment by benjaminpkane** [comment]
Stale

**Comment by brimoor** [comment]
@benjaminpkane can you add a loading state to the `Loading` indicators in the filter widgets? Something as simple as animating the dots:

```
Loading.
Loading..
Loading...
```

This would help convey that something is happening, like the spinners for the counts.

**Comment by benjaminpkane** [comment]
> @benjaminpkane can you add a loading state to the `Loading` indicators in the filter widgets?
> 
> Something as simple as animating the dots:
> 
> ```
> Loading.
> Loading..
> Loading...
> ```
> 
> This would help convey that something is happening, like the spinners for the counts.

Ok, I added the above

**Review by brimoor — APPROVED** [review]
LGTM

**Pull request merged**
