### PR TITLE
[HOLD] Raise error for no dataset name

### PR DESCRIPTION
**Pull request by kaixi-wang**
## What changes are proposed in this pull request?

Raise an error for attempts to load a Dataset without providing a name to prevent any further operations that may lead to upserting a dataset document with no name.

### CODE REVIEW

**Review by brimoor — CHANGES_REQUESTED** [review]
I've seen you add this before but don't understand why, because this already raises an informative error:

```py
import fiftyone as fo

dataset = fo.load_dataset(None)
# ValueError: Dataset 'None' not found
```

**Comment by brimoor** [comment]
Also, in the unfortunate scenario where a user winds up with a dataset named `None`, it would be nice for `fo.load_dataset(None)` to work.

**Comment by kaixi-wang** [comment]
> I've seen you suggest this before but don't understand why, because this already raises an informative error:
> 
> ```python
> import fiftyone as fo
> 
> dataset = fo.load_dataset(None)
> # ValueError: Dataset 'None' not found
> 
> fo.Dataset(None, _create=False)
> # ValueError: Dataset 'None' not found
> ```

Since all datasets need names, Dataset with name =n `None` is in an error state. We would not/should not allow the dataset to continue to "work"

**Comment by brimoor** [comment]
If a `None`-named dataset does happen somehow, this PR would prevent the user from loading it. I think it is better to let them load it so they can fix the problem with `dataset.name = "valid-name"`.

**Pull request closed without merging**
