### PR TITLE
Routing and Sidebar

### LINKED ISSUE #1232: [FR] Opening the expanded view during grid selection
Per user feedback, it would be useful if one could still open the expanded sample view even during grid selection. `Ctrl + click` could be used to override the default click selection when in selection mode in  the grid.

### LINKED ISSUE #1337: [FR] App gets stuck when unplayable video is encountered
When working with the HMDB51 dataset as follows:

```py
import fiftyone as fo
import fiftyone.zoo as foz
import fiftyone.utils.video as fouv
from fiftyone import ViewField as F

dataset = foz.load_zoo_dataset("hmdb51", split="test")
fouv.reencode_videos(dataset)

view = dataset.match(F("ground_truth.label") == "catch")

session = fo.launch_app(view=view)
```

There are some `catch` videos for which the App seems unable to play them for whatever reason, even after re-encoding.

The grid view functions fine until I hover over an unsupported video, at which point all subsequent hover operations don't work (infinite loading state):

Screen Shot 2021-10-13 at 10 02 36 PM

Similarity, in the expanded modal, when I am arrowing between videos, when I reach an unplayable video, the arrow keys stop working:

Screen Shot 2021-10-13 at 10 02 48 PM

Both of these indicate some kind of uncaught exception that is clogging things up and needs to be handled more gracefully.

### LINKED ISSUE #1347: [BUG] Pressing ESC when viewing a single frame clip in the App enters a broken state
I created a clips view with a clip containing exactly 1 frame by tagging a single bounding box in a video dataset, using the filter sidebar to show only tagged labels, and then using the clips menu to convert to clips on the field containing the tagged label.

```py
import fiftyone as fo
import fiftyone.zoo as foz

dataset = foz.load_zoo_dataset("quickstart-video")
session = fo.launch_app(dataset)
```

I am able to view the clip as expected in the expanded sample modal (shown below). However, if I press ESC immediately after opening the expanded modal, the App escapes into a broken state where the labels disappear. The expected behavior is that the expanded modal closes.

Screen Shot 2021-10-14 at 10 47 37 PM

### LINKED ISSUE #1419: [FR] Show error stack traces in the App
Currently if an error occurs while loading an App page, one of two things happens:
1. The generic error page pictured below is loaded
2. A non-fatal server error dialog appears in the bottom-right of the App, and the backend stack trace is printed to the user's shell

Errors can occur for a number of reasons
- **User error**: they tried to load an invalid view in the App
- **User error**: they are trying to view a video dataset in the App w/o ffmpeg installed
- **Internal error**: something that's our fault

In user error cases, the user needs to see the stack trace from the backend server to understand what went wrong. Option 2 achieves that, but the stack trace is not visible when working from notebooks. Option 1 doesn't show the trace at all, which is bad.

One solution here is to simplify to *always* showing the fatal error App page but also including the relevant JS or backend stack trace. The backend stack trace is generally necessary because the user needs to fix things. The JS stack trace might be helpful for github issue creation purposes, but in general these types of errors are not the user's fault, so we could instead not show the full error and instead either provide instructions to access the error from the browser's console or, perhaps, collapse the error by default and let the user opt-in to seeing it, if desired.

Screen Shot 2021-11-12 at 2 35 48 PM

### LINKED ISSUE #1503: [BUG] App cannot render empty heatmaps
On `fiftyone==0.14.2`, the App fails to render samples with a `Heatmap` or `Segmentation` field whose array is empty:

```py
import numpy as np

import fiftyone as fo
import fiftyone.zoo as foz

dataset = foz.load_zoo_dataset("quickstart", max_samples=1)

sample = dataset.first()
sample["heatmap"] = fo.Heatmap(map=np.zeros((0, 0)))
sample["segmentation"] = fo.Segmentation(mask=np.zeros((0, 0)))
sample.save()

session = fo.launch_app(dataset)
```

### LINKED ISSUE #1509: [BUG] The epoch incorrectly renders as 0 in the App
The epoch incorrectly renders as `0` rather than `1970-1-1` in the App grid:

```py
from datetime import date, datetime
import fiftyone as fo

sample = fo.Sample(
    filepath="/path/to/image.png",
    date=date(1970, 1, 1),
    datetime=datetime(1970, 1, 1, 0, 0),
)

dataset = fo.Dataset()
dataset.add_sample(sample)

session = fo.launch_app(dataset)
```

Screen Shot 2022-01-04 at 3 10 23 PM

Screen Shot 2022-01-04 at 3 10 31 PM

### LINKED ISSUE #1521: [BUG] Gracefully handle attempts to load a deleted dataset in the App
Currently, if the dataset on a `Session` is deleted, an error is raised by the App when loading the page and the user cannot escape the error page without modifying the session via python.

### LINKED ISSUE #1731: [BUG] Keypoint skeleton not showing in the App for videos
When viewing a video in the App that has keypoints, the skeleton is not drawn when specified through `dataset.skeletons`, only if it is provided through `dataset.default_skeleton`.

## Example
```python
import fiftyone as fo
import fiftyone.zoo as foz

img_dataset = foz.load_zoo_dataset("quickstart", max_samples=1).select_fields().clone()
vid_dataset = foz.load_zoo_dataset("quickstart-video", max_samples=1).select_fields().clone()

skeleton = fo.KeypointSkeleton(
    labels=["point1", "point2"],
    edges=[[0,1]],
)

img_dataset.skeletons["kps"] = skeleton
vid_dataset.skeletons["kps"] = skeleton

kps = fo.Keypoints(
    keypoints=[
        fo.Keypoint(label="test", points=[[0.5,0.5], [0.7,0.7]])
    ],
)

sample = img_dataset.first()
sample["kps"] = kps
sample.save()

sample = vid_dataset.first()
sample.frames[1]["kps"] = kps
sample.save()

session = fo.launch_app(img_dataset)
# Skeleton is drawn for image dataset

session.dataset = vid_dataset
# No skeleton for video dataset

vid_dataset.default_skeleton = skeleton
session.refresh()
# Skeleton is drawn for video dataset
```

### PR DESCRIPTION
**Pull request by benjaminpkane**
### Features

* Interactive Sidebar (dragging, grouping)
* Path filtering via `EmbeddedDocument` schemas, e.g. `metadata.size_bytes`
* Routed datasets: `/datasets/:dataset-name`
* Improved App error handling with tracebacks

### Changes

* Server sent events (SSE) in lieu of websockets (`/events` route)
* New lightweight `Session` events framework (to be replaced with `GraphQL` subscriptions)
* New [`starlette`](https://www.starlette.io/) ASGI server
* Initial GraphQL API release (transitional work) with [`strawberry-graphql`](https://strawberry.rocks/) server and [`react-relay`](https://relay.dev/) client
* React 18
* Custom router designed for the "Render-as-You-Fetch" and `react-relay`
* Drops Python 3.6 support

### Issues

* Resolves #1521
* Resolves #1509
* Resolves #1503
* Resolves #1419
* Resolves #1347
* Resolves #1337
* Resolves #1232
* Resolves #1731

### TODO
* [x] Tests
* [x] Finish new session events (e.g. sample selection)
* [x] Test and update notebook support (e.g. screenshots)
* [x] Test and update desktop App support
* [x] Update relevant documentation
* [x] Address sidebar comments
* [x] Keypoints
* [x]  App bugs
* [x] Colab
* [x] Windows

### CODE REVIEW

**Comment by benjaminpkane** [comment]
I've undrafted this work. Though there are still some outstanding details. See TODOs

**Comment by benjaminpkane** [comment]
I encourage anyone with time to monkey test these updates. Specifically sessions, sessions in notebooks, desktop, and any and all field/label types in the app.

**Comment by brimoor** [comment]
Make sure you update the README badges, docs, etc to reflect the min Python 3.7 requirement (just came to mind when reading the description here, didn’t have a chance to grep the code)

**Comment by benjaminpkane** [comment]
Ok, skeletons for frames work now, but they use the field name and not the path, e.g. `frames.kps` uses the `kps` skeleton.

This is related to `.` not being supported in the dictionary because of MongoDB/mongoengine. I'm making an issue

**Review by ehofesmann — APPROVED** [review]
Gotcha, that's fine, the video skeletons are working for me without `frames.`. Everything else LGTM

**Comment by nirgmultinarity** [comment]
> Ok, skeletons for frames work now, but they use the field name and not the path, e.g. `frames.kps` uses the `kps` skeleton.
> 
> This is related to `.` not being supported in the dictionary because of MongoDB/mongoengine. I'm making an issue

Video skeletons only partially work for me without `frames.` now, the labels are shown but the edges are not being drawn.

**Pull request merged**
