### PR TITLE
Adds string and boolean field filters in the sidebar

### PR DESCRIPTION
**Pull request by benjaminpkane**
Resolves https://github.com/voxel51/fiftyone/issues/827, https://github.com/voxel51/fiftyone/issues/833, and https://github.com/voxel51/fiftyone/issues/833.

Also addresses points 1 and 2 from https://github.com/voxel51/fiftyone/issues/803.

Very happy with this refactor. Lots of technical debt has been banished.

* Adds string and boolean field filters in the sidebar
* Adds color by label support for classification and scalar field bubbles in the sample grid

Needs more testing, I have yet to test video and classifications. The implementation is complete. though.

### CODE REVIEW

**Review by brimoor — COMMENTED** [review]
Amazing!

Can you also add support for this to boolean fields as well, treating `True` and `False` as strings? This would be a quick way to get filtering working on all primitive field types without worrying about new UI elements (the boolean toggle).

Also, can you make string/bool fields appear under the scalar graphs tab?

In fact, boolean fields currently *do* already appear in the scalar graphs (not strings), although the x-tick labels don't seem to show up.

My test code:

```py

import random

import fiftyone as fo
import fiftyone.zoo as foz

ANIMALS = [
    "bear", "bird", "cat", "cow", "dog", "elephant", "giraffe",
    "horse", "sheep", "zebra"
]

dataset = foz.load_zoo_dataset("quickstart").clone()

for sample in dataset.select_fields():
    sample["string"] = random.choice(ANIMALS)
    sample["bool"] = (random.random() < 0.5)
    sample.save()

session = fo.launch_app(dataset)
```

**Comment by brimoor** [comment]
One more thing on this branch: can you get per-label colors working for classifications, strings, and boolean fields? I think the per-label colors option doesn't apply to one or more of these.

These requests are motivated by viewing datasets that have been evaluated via https://github.com/voxel51/fiftyone/pull/849 in the App and wanting to filter by correct/incorrect (boolean field), TP/FP/FN/TN (string field), and wanting to see the different values for these fields in different colors (so that red = correct, green = incorrect, for example).

In searching for an existing issue about this, I found https://github.com/voxel51/fiftyone/issues/725, which is less-critical but related.

**Comment by benjaminpkane** [comment]
Will be undrafted today.

**Comment by benjaminpkane** [comment]
Undrafting

**Comment by brimoor** [comment]
I think `Filter no label/value` is working in reverse- I'd expect it to remove objects/samples that have no label/value, but on the test code I put above, it removes all samples

**Comment by brimoor** [comment]
Also, are you able to get string fields to appear under the scalars tab? I'm not seeing a graph for the `string` field when running my sample code above.

**Comment by brimoor** [comment]
Here's some test code that has `None` values in all field types:

```py

import random

import fiftyone as fo
import fiftyone.zoo as foz
from fiftyone import ViewField as F

ANIMALS = [
    "bear", "bird", "cat", "cow", "dog", "elephant", "giraffe",
    "horse", "sheep", "zebra"
]

dataset = foz.load_zoo_dataset("quickstart").clone()

dataset.add_sample_field("string", fo.StringField)
dataset.add_sample_field("bool", fo.BooleanField)

with fo.ProgressBar() as pb:
    for sample in pb(dataset):
        for detection in sample["ground_truth"].detections:
            if random.random() < 0.1:
                detection.label = None

        for detection in sample["predictions"].detections:
            if random.random() < 0.1:
                detection.label = None

        if random.random() < 0.1:
            sample["uniqueness"] = None

        s = random.choice(ANIMALS)
        if random.random() < 0.1:
            s = None

        sample["string"] = s

        r = random.random()
        if r < 0.33:
            b = True
        elif r < 0.66:
            b = False
        else:
            b = None

        sample["bool"] = b
        sample.save()

print(dataset.filter_labels("ground_truth", F("label") == None).count("ground_truth.detections"))
print(dataset.filter_labels("predictions", F("label") == None).count("predictions.detections"))
print(dataset.match(F("uniqueness") == None).count())
print(dataset.match(F("string") == None).count())
print(dataset.match(F("bool") == None).count())

session = fo.launch_app(dataset)
```

**Comment by brimoor** [comment]
Also in running the test code with `None` labels above, I think I found a bug: the App crashes if objects have `label == None`.

**Comment by brimoor** [comment]
I did a bit more thinking about filtering over in https://github.com/voxel51/fiftyone/issues/803#issuecomment-776817054.

Do you think you can sneak support into this PR for hiding the `Filter no values` toggles when there are no `None` values? This would reduce cognitive overload of the filtering options.

**Comment by benjaminpkane** [comment]
> Do you think you can sneak support into this PR for hiding the `Filter no values` toggles when there are no `None` values? This would reduce cognitive overload of the filtering options.

Yes, will do.

**Comment by benjaminpkane** [comment]
> Also, are you able to get string fields to appear under the scalars tab? I'm not seeing a graph for the `string` field when running my sample code above.

Working on it. I forgot about this request.

**Comment by brimoor** [comment]
@benjaminpkane what do you think about adding (a) from https://github.com/voxel51/fiftyone/issues/833 in here? For labels it would be `+ filter by label` and for other values `+ filter by value`.

I'm not quite sure on part (b) from there anymore. May need more discussion.

**Comment by benjaminpkane** [comment]
Will change to (a). Makes sense to me.

For (b) I would propose `Exclude no value` or `Exclude None` (where `None` is code highlighted.

**Comment by brimoor** [comment]
ok yeah I like `exclude` for the None cases.

I think that terminology should be used for `Exclude true` and `Exclude false` in the boolean filters too, until we figure out something better as per https://github.com/voxel51/fiftyone/issues/803#issuecomment-776826126.

**Comment by benjaminpkane** [comment]
Comments addressed, though I am still testing. Happy to tweak things still, like `Exclude ...` (See screenshots)
Screenshot from 2021-02-10 13-20-53
Screenshot from 2021-02-10 13-20-34

. Still digesting some comments made on issues outside this PR. May sneak some more changes in, though.

**Comment by brimoor** [comment]
Looking good! I noticed a couple things in expanded sample mode:
- The `Exclude None` filter for labels doesn't seem to be working. Perhaps this is because the label has been cast to a string or something like that? On a related note: I think it would be preferable to render `label == None` as `label == ""` so that users can have boxes with no labels if that's what they'd like
- I noticed that applying label filter to a field that has been unselected does not cause the label fields background to change colors. The color change is important regardless of whether the label field is toggled on because it conveys whether their is an active filter on that field (in my opinion)

**Comment by brimoor** [comment]
I hate to keep stringing along this PR, but do you think you can squeeze in hiding the `Exclude None` element when there are no `None`-valued items in the current view?

I bring this up because of a second point of clarification I just found: when using the `filter by label/value` option in the App to select certain labels you want to see, I think that `None` valued fields should also be hidden, since their label/value doesn't match the search any more than a non-None-non-matching label value does. If the `Exclude None` element were always shown, then this would necessitate auto-checking the `Exclude None` box when a filter is performed. But, it would be cleaner if the `Exclude None` element just disappeared since it is no longer relevant.

Screen Shot 2021-02-10 at 4 18 20 PM

**Comment by benjaminpkane** [comment]
> I hate to keep stringing along this PR, but do you think you can squeeze in hiding the `Exclude None` element when there are no `None`-valued items in the current view?

In the extended view?

**Comment by brimoor** [comment]
> > I hate to keep stringing along this PR, but do you think you can squeeze in hiding the `Exclude None` element when there are no `None`-valued items in the current view?
> 
> In the extended view?

yes in https://github.com/voxel51/fiftyone/pull/848#issuecomment-777044873 I'm back in extended view on the sample grid modal

**Comment by benjaminpkane** [comment]
Ok, I'll address the new comments today. I am seeing some weird behavior from the state library (recoil), so I need to work through that.

**Comment by benjaminpkane** [comment]
Ok, comments addressed, I hope. My `None` solution was to add it as a special case in the search results.

I could add an inversion/negation checkbox in the morning so the selected values can be excluded instead.

Screenshot from 2021-02-10 20-22-48
Screenshot from 2021-02-10 20-22-38

list.

**Comment by brimoor** [comment]
Thanks for all the work on this!

I do think it would be really useful to have a field exclusion option. My thoughts on that are in point 2 of https://github.com/voxel51/fiftyone/issues/803, but it occurs to me that selecting one label and excluding another one independently doesn't make sense; it's either all selection or all exclusion. So I think your checkbox idea sounds promising.

Here's my last set of observations. And I'll go ahead and approve now to avoid holding you up :)

1. In expanded sample modal: the scalar fields are clickable but it doesn't do anything. Can you remove the click event (like is true for `tags`, for example)?

Screen Shot 2021-02-11 at 8 57 15 AM

2. Can you make list selection dropdowns auto-hide after something is selected? I think the typical case is to select one thing at a time, so defaulting to auto-hide saves the user time. It's easy to click into the modal again if multiple clicks are desired.

Screen Shot 2021-02-11 at 9 03 12 AM

3. I think if a range filter is applied to a numeric field, this should automatically remove any `None`-valued fields. This is how the equivalent view stage would work, btw, since `a < None < b == False` in MongoDB.
 
Screen Shot 2021-02-11 at 9 00 51 AM

**Review by brimoor — APPROVED** [review]
LGTM

**Pull request merged**
