### PR TITLE
Adding support for applying image models to video frames

### PR DESCRIPTION
**Pull request by brimoor**
Resolves https://github.com/voxel51/fiftyone/issues/989.

If `SampleCollection.apply_model()` detects an image model and a video collection, it will apply the model to each frame of the video and store the results as frame labels.

Similarly, `compute_embeddings()` and `compute_patch_embeddings()` will also compute frame embeddings when presented with video collections.

A `skip_failures` flag is also added that enables graceful processing all possible data in a collection without terminating if an error occurs for any reason (eg missing or malformed image, failed transform, etc). The default is `skip_failures=True`, so this PR enables inference/embedding runs to generate as many results as possible.

### Frame inference example

```py
import fiftyone as fo
import fiftyone.zoo as foz

dataset = foz.load_zoo_dataset("quickstart-video")

view = dataset.take(2)

model = foz.load_zoo_model("inception-v3-imagenet-torch")
view.apply_model(model, "imagenet_preds", batch_size=8)

model = foz.load_zoo_model("ssd-mobilenet-v1-coco-tf")
view.apply_model(model, "coco_preds")

session = fo.launch_app(view=view)
```

### Frame embeddings example

```py
import fiftyone as fo
import fiftyone.zoo as foz

dataset = foz.load_zoo_dataset("quickstart-video")
view = dataset.take(2)

model = foz.load_zoo_model("mobilenet-v2-imagenet-tf1")

embeddings1 = view.compute_embeddings(model)

embeddings2 = view.compute_embeddings(model, batch_size=8)
```

### Frame patch embeddings example

```py
import fiftyone as fo
import fiftyone.zoo as foz

dataset = foz.load_zoo_dataset("quickstart-video")
view = dataset.take(2)

model = foz.load_zoo_model("mobilenet-v2-imagenet-tf1")

patch_embeddings1 = view.compute_patch_embeddings(
    model, "frames.ground_truth_detections"
)

patch_embeddings2 = view.compute_embeddings(
    model, "frames.ground_truth_detections", batch_size=8
)
```

### Example of graceful handling of errors

```py
import fiftyone as fo
import fiftyone.zoo as foz

dataset = fo.Dataset()
dataset.add_samples(
    [
        fo.Sample(filepath="non-existent1.png"),
        fo.Sample(filepath="non-existent2.png"),
        fo.Sample(filepath="non-existent3.png"),
        fo.Sample(filepath="non-existent4.png"),
    ]
)

model = foz.load_zoo_model("inception-v3-imagenet-torch")  # torch, data loader
dataset.apply_model(model, "predictions1")

model = foz.load_zoo_model("inception-v3-imagenet-torch")  # torch, data loader w/ batching
dataset.apply_model(model, "predictions2", batch_size=2)

model = foz.load_zoo_model("ssd-mobilenet-v1-coco-tf")  # TF, single inference
dataset.apply_model(model, "predictions3")

model = foz.load_zoo_model("resnet-v2-50-imagenet-tf1")  # TF, batch inference
dataset.apply_model(model, "predictions4", batch_size=2)
```

### CODE REVIEW

**Review by ehofesmann — CHANGES_REQUESTED** [review]
This is working for the `quickstart-video` dataset, but when I try it on a custom dataset with the following code, I'm getting an error:

```
/videos
    /class1
        video1.mp4
````

```python
import fiftyone as fo
import fiftyone.zoo as foz

dataset = fo.Dataset.from_dir(
    "./videos",
    dataset_type=fo.types.VideoClassificationDirectoryTree,
)

model = foz.load_zoo_model("ssd-mobilenet-v1-coco-tf")
view = dataset.take(1)
view.apply_model(model, "coco_preds")

print(view.first().frames[1])
```
```shell
*** mongoengine.errors.FieldDoesNotExist: The fields "{'coco_preds'}" do not exist on the document "frames.samples.2021.05.03.14.07.45"
```

Is this and error encountered before or specific to my environment?

**Comment by ehofesmann** [comment]
> This is working for the `quickstart-video` dataset, but when I try it on a custom dataset with the following code, I'm getting an error:
> 
> ```
> /videos
>     /class1
>         video1.mp4
> ```
> 
> ```python
> import fiftyone as fo
> import fiftyone.zoo as foz
> 
> dataset = fo.Dataset.from_dir(
>     "./videos",
>     dataset_type=fo.types.VideoClassificationDirectoryTree,
> )
> 
> model = foz.load_zoo_model("ssd-mobilenet-v1-coco-tf")
> view = dataset.take(1)
> view.apply_model(model, "coco_preds")
> 
> print(view.first().frames[1])
> ```
> 
> ```shell
> *** mongoengine.errors.FieldDoesNotExist: The fields "{'coco_preds'}" do not exist on the document "frames.samples.2021.05.03.14.07.45"
> ```
> 
> Is this and error encountered before or specific to my environment?

FYI, when using #974 to convert the video `to_frames` and evaluating them individually, everything works as expected. One note is that not all frames contain a detection, that may be contributing to the error.

**Comment by brimoor** [comment]
> This is working for the `quickstart-video` dataset, but when I try it on a custom dataset with the following code, I'm getting an error:
> 
> ```
> /videos
>     /class1
>         video1.mp4
> ```
> 
> ```python
> import fiftyone as fo
> import fiftyone.zoo as foz
> 
> dataset = fo.Dataset.from_dir(
>     "./videos",
>     dataset_type=fo.types.VideoClassificationDirectoryTree,
> )
> 
> model = foz.load_zoo_model("ssd-mobilenet-v1-coco-tf")
> view = dataset.take(1)
> view.apply_model(model, "coco_preds")
> 
> print(view.first().frames[1])
> ```
> 
> ```shell
> *** mongoengine.errors.FieldDoesNotExist: The fields "{'coco_preds'}" do not exist on the document "frames.samples.2021.05.03.14.07.45"
> ```
> 
> Is this and error encountered before or specific to my environment?

@ehofesmann I'm unable to reproduce this. I did merge https://github.com/voxel51/fiftyone/pull/992 in here before running your code, which could have plausibly fixed something, but I struggle to see why there would be any difference in behavior between your test code and the example code that I provided in the PR description. Can you try it agin with the latest code here?

The error suggests that predictions were added to your frames and written to the database but for whatever reason the new field was not added to the dataset's schema so you get an error when trying to load the data into a `Frame`. I can imagine how such an error might appear when running inference on a view rather than a dataset, but my example code uses a view too...

**Review by ehofesmann — APPROVED** [review]
You're right, it must have been a version issue. After updating this works nicely!

**Pull request merged**
