### PR TITLE
adding results output for execute_queued_ops and execute_ops

### PR DESCRIPTION
**Pull request by CamronStaley**
## What changes are proposed in this pull request?

Adding results output so we can track which operators executed successful / unsuccessfully and those that were not executed at all because they were in an unexpected state.

## How is this patch tested? If it is not, please explain why.

Used the cli:
```
fiftyone delegated launch -t local
```

Output (just added a print statement locally):
```
Running operation 66e8cab28cecb3ff22558acb (@voxel51/utils/compute_metadata)
Computing metadata...
 100% |█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 200/200 [43.7ms elapsed, 0s remaining, 4.6K samples/s] 
Operation 66e8cab28cecb3ff22558acb complete

Running operation 66fc466cf65a5cf806dfd007 (@voxel51/utils/compute_metadata)
Computing metadata...
 100% |█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 200/200 [17.8ms elapsed, 0s remaining, 11.2K samples/s] 
Operation 66fc466cf65a5cf806dfd007 complete
[<fiftyone.operators.executor.ExecutionResult object at 0x17af5b850>, <fiftyone.operators.executor.ExecutionResult object at 0x17adb7970>]
```
^ print output is that list with two result objects at the end
### Is this a user-facing change that should be mentioned in the release notes?

-   [ ] No. You can skip the rest of this section.
-   [x] Yes. Give a description of this change to be included in the release
        notes for FiftyOne users.

Results are now returned by execute_queued_operations and execute_operation (None if operation is not actioned on due to it not being in the expected "QUEUED" state.

### What areas of FiftyOne does this PR affect?

-   [x] App: FiftyOne application changes
-   [ ] Build: Build and test infrastructure changes
-   [ ] Core: Core `fiftyone` Python library changes
-   [ ] Documentation: FiftyOne documentation changes
-   [ ] Other

## Summary by CodeRabbit

- **New Features**
	- Enhanced tracking of results from queued operations.
	- Improved feedback during operation execution.

- **Bug Fixes**
	- Adjusted logging statements for better clarity on operation success or failure.

- **Tests**
	- Updated unit tests to verify results from executed operations.
	- Added a new test for handling operations already in progress.

### CODE REVIEW

**Review by swheaton — CHANGES_REQUESTED** [review]
seems reasonable to me!
Can we:
1. Move `delegated_operators_tests.py` to `operators/delegated_tests.py`. Files here don't all follow this pattern, but I think it's a good one so let's make it better than we found it.
2. Make existing tests in above inspect the (new) return of `execute_queued_operations()` in addition to whatever else they were doing.
3. Small new test that includes `None` in output from one of the calls to `execute_operation()`. Probably have to mock that call.

happy to help with this, just say the word

**Comment by CamronStaley** [comment]
@swheaton done

**Comment by swheaton** [comment]
make sure you are running `black` and linting your commits. You should install this project's pre-commit hooks : https://github.com/voxel51/fiftyone/blob/develop/CONTRIBUTING.md#pre-commit-hooks

Additionally I have black hooked up to autoformat on save in my IDE.

**Review by swheaton — APPROVED** [review]
thanks for adding [to] tests. I yes-and'ed it slightly to check a few things about the ExecutionResult itself. Also black'ed the file (see ^^ comment).

**Pull request merged**
