### PR TITLE
Add toggle to add_samples to hide progress bar

### LINKED ISSUE #2436: [FR] Allow disabling of progress bar when adding samples to dataset
### Proposal Summary

Allow a disabling of the progress tracking when adding samples. The progress bar could interfere with other output or progress bars and it should therefore be possible to disable the progress bar.

``` python
import fiftyone as fo

samples = ...
dataset = fo.Dataset()
dataset.add_samples(samples, progress=False)
```

### Motivation
- Output control by user
- Difficult currently because the parameter is not forwarded. Monkey patching requires in-depth knowledge of progress tracking.

### What areas of FiftyOne does this feature affect?

-   [ ] App: FiftyOne application
-   [X] Core: Core `fiftyone` Python library
-   [ ] Server: FiftyOne server

### Details
The implementation could be done by forwarding the parameter to the ``add_samples`` signature and setting the default to the current value.

### Willingness to contribute

The FiftyOne Community welcomes contributions! Would you or another member of your organization be willing to contribute an implementation of this feature?

-   [X] Yes. I can contribute this feature independently
-   [ ] Yes. I would be willing to contribute this feature with guidance from the FiftyOne community
-   [ ] No. I cannot contribute this feature at this time

### PR DESCRIPTION
**Pull request by sebimarkgraf**
## What changes are proposed in this pull request?

Add progress bar toggle
Fixes #2436

## How is this patch tested? If it is not, please explain why.
Only forwards a parameter.
Testing it in add_samples would either require mocking the complete batch object or verifying the output, and in that case
testing a different object.

### Is this a user-facing change that should be mentioned in the release notes?
-   [ ] No. You can skip the rest of this section.
-   [X] Yes. Give a description of this change to be included in the release
        notes for FiftyOne users.

Add possibility of disabling the progress bar when adding samples.

### What areas of FiftyOne does this PR affect?

-   [ ] App: FiftyOne application changes
-   [ ] Build: Build and test infrastructure changes
-   [X] Core: Core `fiftyone` Python library changes
-   [ ] Documentation: FiftyOne documentation changes
-   [ ] Other

### CODE REVIEW

**Review by brimoor — COMMENTED** [review]
Hi @sebimarkgraf, just left some comments on https://github.com/voxel51/fiftyone/issues/2436 that are relevant here 🤗

**Comment by sebimarkgraf** [comment]
@brimoor 
I did update the parameters except for the datasets and the usage in the model files.
Here, I am unsure about adding of the progress parameter.

The next step would be to test the correct forwarding of the parameter in this method and writing a good test case for the changed implementation in the iter_* methods.

**Comment by sebimarkgraf** [comment]
@brimoor 
Not sure about additional tests.
While I thought about adding a pytest parameterization for the testcases with the progress parameter, this does not seem to really fit in with the general testing approach in the current setup.

Do you have anymore requests for this PR?

**Review by brimoor — APPROVED** [review]
Hi @sebimarkgraf, apologies for the delay 😅, thanks so much for the contribution!

**Pull request merged**
