### PR TITLE
Server error messages

### PR DESCRIPTION
**Pull request by benjaminpkane**
## What changes are proposed in this pull request?

The goal of this PR is to introduce a way to communicate notifications (specifically, server errors to start with) to `Session`s and the App.

An immediate benefit is users (including us) are immediately made aware of a server error. Currently, server errors occur silently, unless you are watching the server logs.

Server errors are caught via a decorator, and a `notification` socketio event is sent to all clients (the App, and all `Session`s). The traceback is printed by `Session`s. Not sure if we should include a traceback in the App.

Open to any and all suggestions! The spirit of this PR is to make it easier for us to track down bugs. And to maybe make it easier for us to help users. Or for users to help us!

Screenshot from 2020-09-21 17-53-40

## How is this patch tested? If it is not, please explain why.

Forthcoming server test(s).

### Is this a user-facing change that should be mentioned in the release notes?

-   [ ] No. You can skip the rest of this section.
-   [x] Yes. Give a description of this change to be included in the release
        notes for FiftyOne users.

Server error notifications in the App. A traceback is also printed by connected `Session`s.

### What areas of FiftyOne does this PR affect?

-   [x] App: FiftyOne application changes
-   [ ] Build: Build and test infrastructure changes
-   [x] Core: Core `fiftyone` Python library changes
-   [ ] Documentation: FiftyOne documentation changes
-   [ ] Other

### CODE REVIEW

**Comment by benjaminpkane** [comment]
This is ready. Storybook should be working now, as well.

**Comment by benjaminpkane** [comment]
One can test this by trying to clear the sample selection. An exception is raised by the server for demonstrative purposes.

**Review by lethosor — APPROVED** [review]
Looks good!

**Comment by lethosor** [comment]
As a side note: ipython handles printing to an interactive console well, but the plain `python` interpreter does not (it still works, but any messages could be printed in the middle of a line that a user is editing, which could be confusing).
I _think_ server stdout/stderr is going to a log file currently. A longer-term solution could be to direct users there, and/or display a relevant portion in the app.

**Comment by benjaminpkane** [comment]
> As a side note: ipython handles printing to an interactive console well, but the plain `python` interpreter does not (it still works, but any messages could be printed in the middle of a line that a user is editing, which could be confusing).
> I _think_ server stdout/stderr is going to a log file currently. A longer-term solution could be to direct users there, and/or display a relevant portion in the app.

Good point. I'll circle back to this sooner than later.

**Pull request merged**
