### PR TITLE
Fix databricks integration

### LINKED ISSUE #2197: Databricks notebook visualization is no longer working
_Originally posted by @jpkoponen in https://github.com/voxel51/fiftyone/issues/1343#issuecomment-1292000330_

I think this issue should be re-opened. Apparently there has been some refactoring after merging the branch and Databricks integration doesn't work anymore. One clear issue is that in [`fiftyone/core/session/notebooks.py`](https://github.com/voxel51/fiftyone/blob/develop/fiftyone/core/session/notebooks.py#L52), the function for displaying Databricks has been omitted, causing the following KeyError:

```
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<command-3730664978028155> in <cell line: 1>()
----> 1 fo.launch_app()

/local_disk0/.ephemeral_nfs/envs/pythonEnv-8418e8e6-f1ac-4344-a764-0c078670b93a/lib/python3.9/site-packages/fiftyone/core/session/session.py in launch_app(dataset, view, port, address, remote, desktop, height, auto, config)
    154     close_app()
    155 
--> 156     _session = Session(
    157         dataset=dataset,
    158         view=view,

/local_disk0/.ephemeral_nfs/envs/pythonEnv-8418e8e6-f1ac-4344-a764-0c078670b93a/lib/python3.9/site-packages/fiftyone/core/session/session.py in __init__(self, dataset, view, plots, port, address, remote, desktop, height, auto, config)
    351 
    352         if self.auto and focx.is_notebook_context():
--> 353             self.show(height=config.notebook_height)
    354 
    355         if self.remote:

/local_disk0/.ephemeral_nfs/envs/pythonEnv-8418e8e6-f1ac-4344-a764-0c078670b93a/lib/python3.9/site-packages/fiftyone/core/session/session.py in wrapper(session, *args, **kwargs)
    208             if auto_show and session.auto and focx.is_notebook_context():
    209                 session.freeze()
--> 210             result = func(session, *args, **kwargs)
    211             session._client.send_event(StateUpdate(state=session._state))
    212             if auto_show and session.auto and focx.is_notebook_context():

/local_disk0/.ephemeral_nfs/envs/pythonEnv-8418e8e6-f1ac-4344-a764-0c078670b93a/lib/python3.9/site-packages/fiftyone/core/session/session.py in show(self, height)
    888         )
    889 
--> 890         fosn.display(self._client, self._notebook_cells[uuid])
    891 
    892     def no_show(self) -> fou.SetAttributes:

/local_disk0/.ephemeral_nfs/envs/pythonEnv-8418e8e6-f1ac-4344-a764-0c078670b93a/lib/python3.9/site-packages/fiftyone/core/session/notebooks.py in display(client, cell, reactivate)
     54         focx._IPYTHON: display_ipython,
     55     }
---> 56     fn = funcs[focx._get_context()]
     57     fn(client, cell, reactivate)
     58 

KeyError: 'DATABRICKS'

```

I tried to fix the issue by re-introducing [`_display_databricks()`](https://github.com/voxel51/fiftyone/pull/1343/files#diff-20487b959e9116a305a132d18998a4341410897edc5695d53d3f7e0580f911bdR1129) from the branch and using it in [`display()`](https://github.com/voxel51/fiftyone/blob/develop/fiftyone/core/session/notebooks.py#L48). I got no errors in Notebook but there was an empty page in place of the FiftyOne UI. There were also some 404 errors in the browser Javascript console. I'm not sure if it is due to some mismatch in the FiftyOne front-end paths or connectivity issues on our Databricks side. That's where I stopped exploring because I don't have strong web dev skills and it would take too much time.

Hopefully, these findings could help someone with more expertise and time to get the Databricks integration to work.

### LINKED ISSUE #2264: [BUG] Jupyter notebook App screenshots need some cleanup
On `fiftyone==0.18`, using `session.freeze()` to generate a screenshot in the App needs some cleanup:
- Selection boxes shouldn't appear
- Shadows should not appear
- Grid zoom tooltip looks weird

Screen Shot 2022-11-08 at 6 33 05 PM

Screen Shot 2022-11-08 at 6 33 38 PM

### PR DESCRIPTION
**Pull request by benjaminpkane**
Resolves #2197 

Testing requires a databricks account.

```py
!pip install fiftyone==0.18.1rc26

import fiftyone as fo
import fiftyone.zoo as foz

dataset = foz.load_zoo_dataset("quickstart")
session = fo.launch_app(dataset)
```

### CODE REVIEW

**Review by brimoor — COMMENTED** [review]
I haven't tested, but isn't a change to `display()` function required to actually call `display_databricks()`?

**Comment by brimoor** [comment]
> I haven't tested, but isn't a change to `display()` function required to actually call `display_databricks()` when in a databricks context?

Ah I see you added it here: https://github.com/voxel51/fiftyone/pull/2398

**Comment by benjaminpkane** [comment]
Can be tested with `!pip install fiftyone==0.18.1rc5`

**Comment by benjaminpkane** [comment]
Screen Shot 2022-12-06 at 4 13 15 PM

**Comment by BeardyBear** [comment]
Hi,

I am trying to run FiftyOne example in our Databricks with `0.18.1rc5`.
Getting 502 Bad Gateway, any idea what could cause it?

Screenshot:

[https://i.imgur.com/1ZwPHAx.png](url)

**Comment by benjaminpkane** [comment]
@BeardyBear it wasn't ready yet. You can try now with `0.18.1rc26`.

@brimoor ready 
Screen Shot 2023-01-04 at 12 07 38 PM

**Comment by paultreadel** [comment]
Unfortunately with this latest release `0.18.1rc26` I am still seeing the same 502 error (error below) @BeardyBear observed previously.

If its helpful, the last working version of fiftyone I can make work with Databricks is version `0.15.1`
image

**Comment by paultreadel** [comment]
an update on my 502 Bad Gateway error, I was able to successfully launch the app within databricks with `0.18.1rc26`

I found that if the first session I tried launching in a notebook did not contain "0.0.0.0" as the address argument for a session then a bad gateway error occurs and would continue to occur for all subsequent calls even if the correct address argument was provided.

Example of a failing code:
```
import fiftyone as fo
import fiftyone.zoo as foz

dataset = foz.load_zoo_dataset("quickstart")
session = fo.Session(dataset=dataset)
# would cause 502 gateway error

### NEXT COMMAND CELL

import fiftyone as fo
import fiftyone.zoo as foz

dataset = foz.load_zoo_dataset("quickstart")
session = fo.Session(dataset=dataset, address="0.0.0.0")
# would continue to cause 502 gateway error even though address "0.0.0.0" was provided
```

### My resolution
1. detach & reattach the notebook to the cluster
2. reinstall fiftyone by running command `pip install fiftyone==0.18.1rc26` in a notebook cell
3. make sure the very first session launch command includes an address of "0.0.0.0" like this:
```
import fiftyone as fo
import fiftyone.zoo as foz

dataset = foz.load_zoo_dataset("quickstart")
session = fo.Session(dataset=dataset, address="0.0.0.0")
```
Interestingly the address argument was no longer necessary to prevent 502 error for any subsequent session launch commands as long as the first launch contained it.

Any thoughts on why Session requires an address of "0.0.0.0" on the very first launch in a databricks notebook?

**Review by brimoor — APPROVED** [review]
LGTM

**Pull request merged**
