### PR TITLE
Adding support for populating query distances when sorting by similarity 

### PR DESCRIPTION
**Pull request by brimoor**
Resolves https://github.com/voxel51/fiftyone/issues/1545.

Adds an optional `dist_field` parameter that can specify the name of a (new or existing) float field in which to store query distances when [sorting by similarity](https://voxel51.com/docs/fiftyone/user_guide/using_views.html#visual-similarity):

```py
import fiftyone as fo
import fiftyone.brain as fob
import fiftyone.zoo as foz

dataset = foz.load_zoo_dataset("quickstart")
fob.compute_similarity(dataset, brain_key="img_sim")

view = dataset.sort_by_similarity(dataset.shuffle().first().id, dist_field="dist")

session = fo.launch_app(view)
```

This feature can be used when [sorting by similarity in the App](https://voxel51.com/docs/fiftyone/user_guide/app.html#sorting-by-visual-similarity), but currently the `dist_field` must be added in the view bar after initially creating the view:

sim-opt

### CODE REVIEW

**Comment by brimoor** [comment]
@benjaminpkane can you add `dist_field` as an optional field in the similarity menu?

**Comment by benjaminpkane** [comment]
LGTM. I will make App updates in #1369

**Comment by benjaminpkane** [comment]
It's a bit messy that you are changing the schema here. Working through it.

**Comment by brimoor** [comment]
> It's a bit messy that you are changing the schema here. Working through it.

Yeah I believe a `dataset.reload()` is called for to cause the schema to update

**Comment by brimoor** [comment]
If we've built things correctly, when the user then tries to access a sample from the main process, a `dataset.reload()` should automatically be triggered when they encounter data in an unexpected `dist_field`.

Maybe now is the time to get something similar working in the App process? That way if the user adds a new field from another process, the App will automatically reflect this upon the next refresh

**Comment by benjaminpkane** [comment]
That is beyond the point. The issue is you are asking for more hidden (extended view) state, but this stage changes schema. That breaks the rules of the extended view. I'm working through it.

**Comment by brimoor** [comment]
> That is beyond the point. The issue is you are asking for more hidden (extended view) state, but this stage changes schema. That breaks the rules of the extended view. I'm working through it.

I see. FWIW, we do not allow `DatasetView`s to declare new fields (they must be declared on the dataset itself), so the same can be true for the extended view: if `dist_field` is used, it always causes an irreversible field to be added to the dataset, and also the values are permanently written to the dataset.

I fully admit that this violates the notion of what a view stage should do, but I haven't found the motivation to allow `DatasetView` schemas to be "temporarily" expanded, primarily because I also haven't found a good way to implement attaching an arbitrary set of ephemeral field data to a view.

**Comment by benjaminpkane** [comment]
Note that this also opaquely makes synchronous db calls which will block when used by the server

**Comment by brimoor** [comment]
> Note that this also opaquely makes synchronous db calls which will block when used by the server

Yep but just a drop in the bucket compared to the linear algebra that it already does to compute nearest neighbors

**Pull request merged**
