### PR TITLE
Standardize app external links

### PR DESCRIPTION
**Pull request by lethosor**
## What changes are proposed in this pull request?

Added a standardized `ExternalLink` component, which works in both electron and browser environments. This fixes storybook, which was previously broken due to `electron` requiring `fs`, which is not available in browser environments.

Note: any components using recoil are encountering an error like this:
```
This component must be used inside a <RecoilRoot> component.
Error: This component must be used inside a <RecoilRoot> component.
    at Object.notInAContext (http://localhost:6006/vendors~main.ea027bf53ad6510ea6ab.bundle.js:6495:9)
    at http://localhost:6006/vendors~main.ea027bf53ad6510ea6ab.bundle.js:6196:60
    at Object.trace (http://localhost:6006/vendors~main.ea027bf53ad6510ea6ab.bundle.js:5963:10)
    at getRecoilValueAsLoadable (http://localhost:6006/vendors~main.ea027bf53ad6510ea6ab.bundle.js:6196:18)
    at useRecoilValueLoadable (http://localhost:6006/vendors~main.ea027bf53ad6510ea6ab.bundle.js:6985:14)
    at Object.useRecoilValue [as getRecoilValue] (http://localhost:6006/vendors~main.ea027bf53ad6510ea6ab.bundle.js:6992:24)
    at useRecoilValue (http://localhost:6006/vendors~main.ea027bf53ad6510ea6ab.bundle.js:7037:25)
    at Header (http://localhost:6006/main.ea027bf53ad6510ea6ab.bundle.js:4092:89)
    at renderWithHooks (http://localhost:6006/vendors~main.ea027bf53ad6510ea6ab.bundle.js:341969:18)
    at mountIndeterminateComponent (http://localhost:6006/vendors~main.ea027bf53ad6510ea6ab.bundle.js:344648:13)
```

I'm not sure why, because the decorator wrapping all stories in `<RecoilRoot>` is still present in preview.js, and this was working previously.

## How is this patch tested? If it is not, in a single sentence please explain why.

Local testing (in app and storybook)

### Is this a user-facing change?

-   [x] No. You can skip the rest of this section.
-   [ ] Yes. Give a description of this change to be included in the release
        notes for FiftyOne users.

### What areas of FiftyOne does this PR affect?

-   [x] `App`: FiftyOne application changes
-   [ ] `Build`: Build and test infrastructure changes
-   [ ] `Core`: Core `fiftyone` Python library changes
-   [ ] `Documentation`: FiftyOne documentation changes
-   [ ] `Other`

### CODE REVIEW

**Comment by benjaminpkane** [comment]
I'll review after the release. It'd be nice to resolve the recoil issue before merging, and I can probably figure that out.

**Comment by lethosor** [comment]
I think the recoil issue may be due to adding recoil to the root package.json in 1ab993a42. I suspect storybook and components are using different recoil packages, which would have different definitions of RecoilRoot, RecoilState, etc. (even though they're the same version). Investigating.

**Comment by benjaminpkane** [comment]
Interesting. I have a commit standing by that just adds `<RecoilRoot/>` to the relevant stories.

**Comment by lethosor** [comment]
https://github.com/voxel51/fiftyone/pull/483/commits/6939e7f5efbbd528e182f5f9f4f5551fd827dc54 is my proposed solution. I don't really like explicitly having `app/node_modules` in an `import` statement, but I'd also like to keep the decorator approach to avoid having to add RecoilRoot to every story that needs it (admittedly, those are a minority right now).
I'll see if Chromatic is happy with this, though.

**Comment by benjaminpkane** [comment]
Noting your solution and comments, can we just remove `recoil` from `.electron/app/package.json`. And keep it in the root package. It seems to work for me.

**Comment by lethosor** [comment]
Yeah, that would probably also work. Why do we have two `package.json`s, anyway? Was that just a thing that the electron boilerplate set up?

**Comment by benjaminpkane** [comment]
https://electron-react-boilerplate.js.org/docs/adding-dependencies/

which points to ...

https://www.electron.build/tutorials/two-package-structure.html

Still digesting this myself. It does look like electron 8 obsoleted this. Something for us to think about.

**Comment by lethosor** [comment]
Your idea seems to work!

**Pull request merged**
