### PR TITLE
Expand only labels and tags sidebar groups by default

### PR DESCRIPTION
**Pull request by benjaminpkane**
Screenshot 2023-10-31 at 2 27 04 PM

### CODE REVIEW

**Review by lanzhenw — DISMISSED** [review]
LGTM 🚀

**Comment by manivoxel51** [comment]
> Screenshot 2023-10-31 at 2 27 04 PM

Looks good 🍨 

There are some connections with other features that we may have to consider.

For example, if a field visibility is applied, do we keep all the fields collapsed or should we expand them? How would you know which collapsed field has field visibility applied to? one idea is to add an icon to every field with a count of fields hidden in that top field. but that seems like a overkill
There might be consequences to the work @lanzhenw has done with field filter/visibility feature too? thinking out loud

**Comment by manivoxel51** [comment]
Perhaps, this could be a setting in our settings dropdown too

**Comment by benjaminpkane** [comment]
> For example, if a field visibility is applied, do we keep all the fields collapsed or should we expand them? How would you know which collapsed field has field visibility applied to? one idea is to add an icon to every field with a count of fields hidden in that top field. but that seems like a overkill

Good points. I think I will hold off on merging this until we can discuss more

**Pull request closed without merging**
