### PR TITLE
Serializes numpy arrays as lists for server

### LINKED ISSUE #556: [BUG] numpy.array sample fields trigger server error when serialized
### System information

-   **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 20.04
-   **FiftyOne installed from (pip or source)**: source
-   **FiftyOne version (run `fiftyone --version`)**: v0.5.6 (e86c3570) - does not occur in v0.5.5
-   **Python version**: 3.6

### Commands to reproduce

1. Start server with `python fiftyone/server/main.py`
2. Start app with `yarn dev`
3. Run the code below

### Describe the problem

The server fails to serialize the sample (see traceback) and the sample does not display in the app.

### Code to reproduce issue
```python
import fiftyone as fo
import numpy as np
dataset = fo.Dataset()
dataset.add_sample(fo.Sample('/path/to/image', field=np.array([1,2,3])))
session = fo.launch_app(remote=True, dataset=dataset)
```

### Other info / logs

Probably introduced in #543, since that changed JSON encoding. Previously, this field was serialized as:
```
    "field": {
        "$binary": "eJyb7BfqGxDJyFDGUK2eklqcXKRupaBuk2mhrqOgnpZfVFKUmBefX5SSChJ3S8wpTgWKF2ckFqQC+RrGOpo6CrUKFAAuRgYIYILSzFAaAOdAG2c=",
        "$type": "00"
    }
```

Server traceback:
```
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File ".../lib/python3.6/site-packages/socketio/server.py", line 696, in _handle_event_internal
    binary=binary))
  File ".../lib/python3.6/site-packages/socketio/server.py", line 607, in _send_packet
    encoded_packet = pkt.encode()
  File ".../lib/python3.6/site-packages/socketio/packet.py", line 71, in encode
    encoded_packet += self.json.dumps(data, separators=(',', ':'))
  File "/home/alan/code/fiftyone/fiftyone/server/json_util.py", line 47, in dumps
    json_util.dumps(*args, **kwargs), parse_constant=lambda c: c
  File ".../lib/python3.6/site-packages/bson/json_util.py", line 383, in dumps
    return json.dumps(_json_convert(obj, json_options), *args, **kwargs)
  File "/usr/lib/python3.6/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
  File ".../lib/python3.6/site-packages/simplejson/encoder.py", line 275, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File ".../lib/python3.6/site-packages/simplejson/encoder.py", line 357, in iterencode
    return _iterencode(o, 0)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x9c in position 1: invalid start byte
```

### What areas of FiftyOne does this bug affect?

-   [ ] `App`: FiftyOne application issue
-   [ ] `Core`: Core `fiftyone` Python library issue
-   [x] `Server`: Fiftyone server issue

### PR DESCRIPTION
**Pull request by benjaminpkane**
## What changes are proposed in this pull request?

Resolves #556. This is not the cleanest solution, but currently we rely on MongoEngine for field serialization, and changing that would be quite the lift.

## How is this patch tested? If it is not, please explain why.

A check has been added to the encoder step in the server tests.

### Is this a user-facing change that should be mentioned in the release notes?

-   [ ] No. You can skip the rest of this section.
-   [x] Yes. Give a description of this change to be included in the release
        notes for FiftyOne users.

NumPy arrays are now serialized and sent to the App. Previously, an error was raised by the server when a dataset contained `VectorField`s or `ArrayField`s. 

### What areas of FiftyOne does this PR affect?

-   [x] App: FiftyOne application changes
-   [ ] Build: Build and test infrastructure changes
-   [ ] Core: Core `fiftyone` Python library changes
-   [ ] Documentation: FiftyOne documentation changes
-   [ ] Other

### CODE REVIEW

**Review by lethosor — APPROVED** [review]
Looks good!

**Review by brimoor — DISMISSED** [review]
How about just replacing `VectorField` and `ArrayField` with `None` when sending to App? They would never be used for anything directly. When we support visualizations like t-SNE, I suspect number crunching to generate the graph data (n-d -> 2D or 3D) will be done on backend.

**Comment by brimoor** [comment]
My comment doesn't need to be blocking. You can handle optimizations separately if desired.

**Comment by benjaminpkane** [comment]
I changed it to replace the arrays themselves with their shape. This will help App.

Optimizing serialization in general needs work. We resort to `json.loads(json.dumps(...))` in a few places. Omitting the nump-based from queries entirely (never loading the from mongodb) would be another optimization.

**Pull request merged**
