### PR TITLE
Improved range sliders and loading states

### LINKED ISSUE #693: [BUG] Applying a scalar filter in the App doesn't fully work
With prod `v0.6.5.2`, using `fiftyone quickstart`, I get weird behavior when trying to apply a uniqueness filter. When I drag the slider endpoints, the slider widget disappears. Also, although the label stats in the filter bar update, as do the number of the images in the image grid, the label graphs do not update.

Screen Shot 2020-11-17 at 1 11 46 PM

### PR DESCRIPTION
**Pull request by benjaminpkane**
## What changes are proposed in this pull request?

Resolves #693 

What is lacking right now is that all new extended statistics need to be computed when a confidence slider is changed, which shows loading indicators for all fields. This does not need to happen, as only the counts for the label field in question will change. Then again, when an `only_matches` option (blocked by only matches support for frame labels) is added, all extended statistics do need to be recomputed...

I think more granular loading will be best addressed when the Fields Sidebar is generalized.

## How is this patch tested? If it is not, please explain why.

Locally

### Is this a user-facing change that should be mentioned in the release notes?

-   [ ] No. You can skip the rest of this section.
-   [x] Yes. Give a description of this change to be included in the release
        notes for FiftyOne users.

TBD

### What areas of FiftyOne does this PR affect?

-   [x] App: FiftyOne application changes
-   [ ] Build: Build and test infrastructure changes
-   [x] Core: Core `fiftyone` Python library changes
-   [ ] Documentation: FiftyOne documentation changes
-   [ ] Other

### CODE REVIEW

**Comment by benjaminpkane** [comment]
Ready for review

**Review by brimoor — CHANGES_REQUESTED** [review]
I tested as per #693 and the label graphs still don't seem to be updating when either a label or scalar filter is applied.

Also, I loaded the `quickstart` dataset, then applied a uniqueness range filter, and then tried to create a `SortBy(uniqueness, True)` stage in the view bar, and I get the following error:

```
Traceback (most recent call last):
  File "main.py", line 132, in wrapper
    result = await func(self, *args, **kwargs)
  File "main.py", line 289, in on_message
    await event(**message)
  File "main.py", line 337, in on_update
    awaitables += self.get_statistics_awaitables()
  File "main.py", line 467, in get_statistics_awaitables
    view + _make_filter_stages(state.dataset, state.filters),
TypeError: unsupported operand type(s) for +: 'DatasetView' and 'list'
```

**Comment by brimoor** [comment]
Also, this may be unrelated to this PR, but if I load the `quickstart` dataset and then directly try to create a `SortBy(uniqueness, True)` view stage, the label stats are stuck in a loading spinner state

**Comment by benjaminpkane** [comment]
OK, things are looking better now. Apologies.

**Review by brimoor — APPROVED** [review]
Everything works now. Awesome!

**Pull request merged**
