### PR TITLE
Tutorials refresh, tagging guide, and screenshot fixes

### PR DESCRIPTION
**Pull request by benjaminpkane**
Updates the following tutorials:
 * evaluate detections
 * evaluating a classifier (only code + new plot types)
 * uniqueness
 * classification mistakes
 * detections mistakes

Adds a `Tags and tagging` section to the App user guide.

Some screenshotting bugs were also fixed. The grid would previously start to load during a screenshot, and the active handle was not always properly updated.

### CODE REVIEW

**Comment by benjaminpkane** [comment]
I need a couple more hours with this.

**Comment by benjaminpkane** [comment]
Working through some screenshotting stability issues

**Comment by benjaminpkane** [comment]
Ok, this is ready. 

In general, I'd like to make a more serious pass through the App user guide. Proposing I do that in a new PR.

As an aside, the server/web API is due for an upgrade. Making sure Colab is fully functional is becoming tricky.

**Review by brimoor — APPROVED** [review]
LGTM

**Pull request merged**
