### PR TITLE
ViewBar: Focus on enter for active stages, move right on stage commit

### PR DESCRIPTION
**Pull request by benjaminpkane**
## What changes are proposed in this pull request?

title

## How is this patch tested? If it is not, please explain why.

Locally

### Is this a user-facing change that should be mentioned in the release notes?

-   [x] No. You can skip the rest of this section.
-   [] Yes. Give a description of this change to be included in the release
        notes for FiftyOne users.

### CODE REVIEW

**Comment by benjaminpkane** [comment]
One moment, I couple issues to address.

**Comment by benjaminpkane** [comment]
I removed the move to next add stage button after a stage commit logic. Right now, I'm having difficulty with keeping the ViewBar in focus after submitting a view which is causing issues. Once that is solved, I can add the logic back.

**Comment by benjaminpkane** [comment]
OK. Both changes are working now.

**Review by lethosor — APPROVED** [review]
Looks good!

**Review by brimoor — COMMENTED** [review]
@benjaminpkane can you also give focus to the nearest still-existing stage (or `+/arrow` if no stages exist) after a stage is deleted by pressing `DEL`? The view bar currently loses focus

Note: if the user clicks the `X` to delete a stage, then they are using the mouse and would probably prefer the view bar *DO* lose focus. If they press `DEL`, however, then they are in keyboard mode and may want to continue pressing `DEL`

**Comment by benjaminpkane** [comment]
> @benjaminpkane can you also give focus to the nearest still-existing stage (or `+/arrow` if no stages exist) after a stage is deleted by pressing `DEL`? The view bar currently loses focus
> 
> Note: if the user clicks the `X` to delete a stage, then they are using the mouse and would probably prefer the view bar _DO_ lose focus. If they press `DEL`, however, then they are in keyboard mode and may want to continue pressing `DEL`

I'm looking into this. I'm actually still seeing a little bit of odd behavior for the move right logic. So looking at that too.

**Comment by brimoor** [comment]
Yeah I'm noticing that the first time `add stage` becomes active, it doesn't turn orange. Similarly, when you finalize a stage, both it and the stage to the right are now "active" (only the current stage is orange)

**Comment by benjaminpkane** [comment]
OK, perhaps there are still some kinks to work out, but I think this is in a good place. Merging.

I have deletion by clicking on the `x` maintaining focus because, almost by definition, that is what focus is.

**Pull request merged**
