### PR TITLE
Utilities for tagging and visualizing samples and labels

### PR DESCRIPTION
**Pull request by brimoor**
Resolves https://github.com/voxel51/fiftyone/issues/891.

**BREAKING CHANGE**
- All notions of "object" have been replaced by "label" in reference to entities with `id` attributes that can be selected in the App. This includes the following changes:
    - `session.selected_objects` -> `session.selected_labels`
    - `SampleCollection.select_objects()` -> `SampleCollection.select_labels()`
    - `SampleCollection.exclude_objects()` -> `SampleCollection.exclude_labels()`
    - `SelectObjects` -> `SelectLabels`
    - `ExcludeObjects` -> `ExcludeLabels`

**DESCRIPTION**

This PR adds more full-featured support for tagging sample as well as individual labels, which I believe will be pretty heavily used by users as we roll out more upcoming features that make it easy to identify groups of samples/labels of interest :)

Specifically, the `select_labels()` and `exclude_labels()` stages support new syntaxes for selecting labels from a collection:

```py
    @view_stage
    def select_labels(self, labels=None, ids=None, tags=None, fields=None):
        """Selects only the specified labels from the collection.

        The returned view will omit samples, sample fields, and individual
        labels that do not match the specified selection criteria.

        You can perform a selection via one of the following methods:

        -   Provide one or both of the ``ids`` and ``tags`` arguments, and
            optionally the ``fields`` argument

        -   Provide the ``labels`` argument

        Args:
            labels (None): a list of dicts specifying the labels to select
            ids (None): a list of IDs of the labels to select
            tags (None): a list of tags of labels to select
            fields (None): a list of fields from which to select labels
        """
```

A few related tagging utilities were also added to `SampleCollection`:

- `tag_samples()` - add tag to samples, if necessary
- `untag_samples()` - remove tag from samples, if necessary
- `count_sample_tags()` - compute histogram of sample tags
- `tag_labels()` - add tag to labels in one or more fields, if necessary
- `untag_labels()` - remove tag from labels in one or more fields, if necessary
- `count_label_tags()` - histogram of label tags in one or more fields 

Also, since "tags" are now first-class citizens in FiftyOne, the `tags` attribute is now declared on all `Label` types.

Notes
- `count_sample_tags()` is a simple alias for `count_values("tags")`, but I added it nonetheless for consistency with the other tags operations
- In the case of a single label field, `count_label_tags()` is also a simple alias for `count_values("field.name.tags")`, but I thought it would be handy to have a version that will consider all label fields by default, similar to how `select_labels(tags=["tag"])` works when no `fields=` argument is provided.
- I chose not to implement `count_label_tags()` as an `Aggregation` because all other aggregations refer to a specific field while this one can refer to multiple fields. And, if a user really is interested in a single field, then they can already compute a tag histogram via the `count_values("field.name.tags")` syntax
- There might be a more efficient way to implement `count_label_tags()` as a single `$group` stage without having to use `$facet`, but I didn't invest the time to look into that

**DISCUSSION**

- ~~The term "object" is used in this PR for consistency with the existing `Session.selected_objects` and `SampleCollection.select_objects()` terminology. However, "object" really refers to any `Label` with an `id`, which includes `Classification`, `Detection`, `Polyline`, `Keypoint`, and `Segmentation`, and excludes label list types like `Detections`. I worry that "object" is a confusing term because it will likely be associated only with `Detection`, and not things like `Classification` that do not have a spatial component. I wonder if a more appropriate term would be "label"? Making this change would come at the price of a breaking API change~~

**VISUALIZATION**

This PR also provides some handy utilities (implemented via `matplotlib`, for now) for visualizing samples/objects that can optionally be connected to a `Session` instance and interactively explored via clicking/lassoing:

The relevant user-facing utilities are:
- `fiftyone.utils.plot.scatter.scatterplot()`- an interactive scatterplot of arbitrary 2D/3D points
- `fiftyone.utils.plot.location.location_scatterplot()` - an interactive scatterplot of lat-lon coordinates

**EXAMPLE VISUALIZATION**

location_scatterplot_opt

scatterplot

**EXAMPLE SELECTION USAGE**

The new examples in the `select_labels()` docstring demonstrate this functionality nicely:

```py
import fiftyone as fo
import fiftyone.zoo as foz

dataset = foz.load_zoo_dataset("quickstart")

#
# Only include the labels currently selected in the App
#

session = fo.launch_app(dataset)

# Select some labels in the App...

view = dataset.select_labels(labels=session.selected_labels)

#
# Create a view that only includes labels with the specified IDs
#

# Grab some label IDs
ids = [
    dataset.first().ground_truth.detections[0].id,
    dataset.last().predictions.detections[0].id,
]

view = dataset.select_labels(ids=ids)

print(view.count("ground_truth.detections"))
print(view.count("predictions.detections"))

#
# Create a view that only includes labels with the specified tags
#

# Grab some label IDs
ids = [
    dataset.first().ground_truth.detections[0].id,
    dataset.last().predictions.detections[0].id,
]

# Give the labels a "test" tag
dataset = dataset.clone()  # create a copy since we're modifying data
dataset.select_labels(ids=ids).tag_labels("test")

print(dataset.count_label_tags())

# Retrieve the labels via their tag
view = dataset.select_labels(tags=["test"])

print(view.count("ground_truth.detections"))
print(view.count("predictions.detections"))
```

### CODE REVIEW

**Comment by benjaminpkane** [comment]
I think I'd like to remove the `objects` argument altogether, which I can add to this PR because there will need to be a couple App changes.

I also think renaming `object` to `label` now would be worthwhile, noting the breaking the change.

**Comment by brimoor** [comment]
> I think I'd like to remove the `objects` argument altogether, which I can add to this PR because there will need to be a couple App changes.
> 
> I also think renaming `object` to `label` now would be worthwhile, noting the breaking the change.

SGTM. I like switching to "label" and removing the `objects` argument altogether.

The only concern I have (and this may be needless performance worry), is that, if we were to do the obvious thing and make `session.selected_labels` return a simple list of object IDs, then `samples.select_labels(ids=session.selected_labels)` might be a bit slow if there are many label fields, without the benefit of the `fields` argument. Any thoughts on this?

Regardless, if you could handle the updates, that'd be much appreciated 💯 💯 💯

**Comment by benjaminpkane** [comment]
> > I think I'd like to remove the `objects` argument altogether, which I can add to this PR because there will need to be a couple App changes.
> > I also think renaming `object` to `label` now would be worthwhile, noting the breaking the change.
> 
> SGTM. I like switching to "label" and removing the `objects` argument altogether.
> 
> The only concern I have (and this may be needless performance worry), is that, if we were to do the obvious thing and make `session.selected_labels` return a simple list of object IDs, then `samples.select_labels(ids=session.selected_labels)` might be a bit slow if there are many label fields, without the benefit of the `fields` argument. Any thoughts on this?
> 
> Regardless, if you could handle the updates, that'd be much appreciated

Of course, no problem. I just looked at the `SelectObjects` implementation and now I think I've changed my mind on the `dict` argument. Regardless, I'll make a decision and address the above.

**Comment by benjaminpkane** [comment]
The selection elements will be overhauled in the `tagging` branch, https://github.com/voxel51/fiftyone/pull/892/commits/66b61d7741ac837d39494c67c2463f12c0571231 is the bare minimum. In terms of presentation, `label` should now always be used in the App.

**Comment by brimoor** [comment]
Hey @benjaminpkane when you get a chance, can you help get `SelectLabels` and `ExcludeLabels` working in the App? I think there may be issues with the fairly complex type specifications that these stages use:

```py
    @classmethod
    def _params(self):
        return [
            {
                "name": "labels",
                "type": "dict|NoneType",
                "placeholder": "[{...}]",
                "default": "None",
            },
            {
                "name": "ids",
                "type": "list<id>|id|NoneType",
                "placeholder": "...",
                "default": "None",
            },
            {
                "name": "tags",
                "type": "list<str>|str|NoneType",
                "placeholder": "...",
                "default": "None",
            },
            {
                "name": "fields",
                "type": "list<str>|str|NoneType",
                "placeholder": "...",
                "default": "None",
            },
        ]
```


```py
import fiftyone as fo
import fiftyone.zoo as foz

dataset = foz.load_zoo_dataset("quickstart")

session = fo.launch_app(dataset)

ids = [
    dataset.first().ground_truth.detections[0].id,
    dataset.last().predictions.detections[0].id,
]

# doesn't load correctly
session.view = dataset.select_labels(ids=ids)
```

**Comment by benjaminpkane** [comment]
There is a small but tricky issue I will get to when it makes sense that causes parsing a `list<...>|NoneType` to fail but `NoneType|list<...>` works. In the meantime, https://github.com/voxel51/fiftyone/pull/892/commits/3da1ca7edf51ddf828a19078b97888ac07aea61d has fixed things for me.

**Comment by brimoor** [comment]
Awesome, works!

**Review by benjaminpkane — APPROVED** [review]
LGTM. I'm not sure why the tests are failing. `develop` ETA has `etau.is_container`. Still investigating some.

**Pull request merged**
