### PR TITLE
QP sidebar enhancements

### PR DESCRIPTION
**Pull request by benjaminpkane**
Tested with

* https://gist.github.com/benjaminpkane/884265cdb6cbaaab453e96f510ec86be
* https://gist.github.com/benjaminpkane/693eda589e21d676d83174deeb803c73

```python
import fiftyone.zoo as foz
from fiftyone import ViewField as F

dataset = (
    foz.load_zoo_dataset("coco-2017", max_samples=1, split="validation")
    .select_fields()
    .clone("test-keypoints")
)
model = foz.load_zoo_model("keypoint-rcnn-resnet50-fpn-coco-torch")
dataset.default_skeleton = model.skeleton
dataset.apply_model(model, label_field="model")

sample = dataset.first()
sample["keypoint"] = sample.model_keypoints.keypoints[0]
sample.save()
``` 

## Release Notes

- **New Features**
	- Added a new `none` field to multiple GraphQL result types, enhancing data structure.
	- Introduced a `Box` component for improved UI loading states.
	- Added `frameFieldsList` and `isFrameField` selectors for better frame field management.

- **Improvements**
	- Enhanced error handling and control flow in various components and functions.
	- Streamlined rendering logic in several components for better performance and clarity.
	- Updated the `QueryPerformanceIcon` component to use the `Bolt` icon, maintaining consistent styling.

- **Bug Fixes**
	- Adjusted logic for handling disabled states and loading indicators across components.

### CODE REVIEW

**Comment by benjaminpkane** [comment]
Going to add all frontend sidebar tweaks to this PR. Converting to draft for now

**Review by minhtuev — DISMISSED** [review]
Thanks Ben ✅

**Comment by CamronStaley** [comment]
Noticed some regression.
In the sidebar the boxes are a bit weird:
Screenshot 2024-11-14 at 1 28 50 PM

It seems like the icon at the top of the sidebar filters column has become a regular lightning bolt instead of the a QueryPerformanceIcon.tsx which has the smart tooltip stuff requested by product
Screenshot 2024-11-14 at 1 29 11 PM

I assume the filters not properly overlapping will be later right (still seeing it here):
Screenshot 2024-11-14 at 1 31 09 PM

**Comment by benjaminpkane** [comment]
> I assume the filters not properly overlapping will be later right
Yes

> It seems like the icon at the top of the sidebar filters column has become a regular lightning bolt instead of the a QueryPerformanceIcon.tsx which has the smart tooltip stuff requested by product

Will fix

> In the sidebar the boxes are a bit weird:

Intentional. Pretty opinionated on this. It's size is meant to match a loaded slider (excluding datetime / date filters with a top line title). This minimizes layout shift from loading states

**Review by CamronStaley — APPROVED** [review]
thx for fixing that lgtm

**Pull request merged**
