### PR TITLE
Adding support for storing and rendering segmentation masks

### PR DESCRIPTION
**Pull request by brimoor**
Semantic segmentation and instance segmentation masks can now be stored on samples, visualized in the App, and rendered on images via `SampleCollection.draw_labels()`.

Example usage:

```py
import numpy as np

import fiftyone as fo
import fiftyone.utils.annotations as foua

IMAGE_PATH = "/path/to/white-image.png"
ANNO_PATH = "/path/for/white-image-anno.png"

sample = fo.Sample(filepath=IMAGE_PATH)

# Random instance mask
instance_mask = np.random.randn(32, 32) > 0
sample["detection"] = fo.Detection(
    label="cat",
    bounding_box=[0.3, 0.3, 0.4, 0.4],
    mask=instance_mask,
    confidence=0.9,
)

# Random segmentation mask
segmentation_mask = np.random.randn(8, 8) > 0
sample["segmentation"] = fo.Segmentation(mask=segmentation_mask)

dataset = fo.Dataset()
dataset.add_sample(sample)

print(sample)

foua.draw_labeled_image(sample, ANNO_PATH)
```

Example annotated image:

test-white-anno

### CODE REVIEW

**Comment by lethosor** [comment]
I can look into adding frontend support on this branch if you're done with backend support. (Note that player51 color handling changes may have broken mask support, so this may take some additional work to address.)

**Comment by brimoor** [comment]
Yes this PR is ready for you to add frontend support. I'd like to dedicate v0.6.0 to video, so we'll hold off on merging.

For instance masks (those stored within `Detection`s), the color should match the object's bounding box.

For segmentation masks (those stored within `Segmentation`s), we'll have to decide how to handle colors. Since each unique value in the mask represents a different semantic category, one typically renders each region with a different color.

This is somewhat analogous to the outstanding feature request to support per-object-label colors, where the user has the option of rendering all objects within a given sample field as either:
- a single uniform color (matching the label field)
- a different color per label

We could hook into the same behavior for `Segmentation` masks: let the user pick between per mask-pixel-value colors, or just treating the mask as a binary mask (`mask != 0`) where anything non-zero is rendered in the label field's color.

Note that the special value `mask == 0` is always reserved to mean no mask.

**Comment by lethosor** [comment]
I think frontend support is done now. @benjaminpkane if you have a chance, it would be good to double-check that my couple refactors didn't break anything.

**Comment by benjaminpkane** [comment]
LGTM! Deferring to @brimoor for a final review.

**Review by benjaminpkane — APPROVED** [review]

**Comment by lethosor** [comment]
Turns out there is an option to disable image smoothing. Image smoothing was kept in originally to match ETA, but Ben pointed out that it doesn't look as good with very low-resolution masks.

With smoothing:
image

Without smoothing:
image

Any thoughts? I can also compare with larger masks.

**Comment by lethosor** [comment]
@brimoor can this be merged or do you want to take another look? This will be blocking #562 fairly soon.

**Comment by brimoor** [comment]
I tested by running the example code in the PR description and segmentation visualization is working as expected. Nice!

Please turn off image smoothing for masks before merging though. This is for the same reason that we turned off smoothing for the raw images themselves: we're not trying to make the images/labels look good, we just want to show the user exactly what their raw data looks like. If they're trying to debug the tightness of their model's instance segmentation masks, for example, they'll want to see what the raw border looks like, not a smoothed version that may hide detail.

**Comment by lethosor** [comment]
All right, I disabled mask smoothing on the Fiftyone side. Should there also be backend changes to match (i.e. in what `draw_labeled_image()` uses)?

**Comment by brimoor** [comment]
No backend changes required. I'm mostly referring to the semantic segmentation masks being "pixelated" rather than "smoothed". That is definitely desirable. The fact that the contours around the instance masks (inside the objects) have a somewhat smoothed boundary when using `draw_labels()` is okay

**Review by lethosor — APPROVED** [review]

**Pull request merged**
