### PR TITLE
saved views bug fix + e2e fixes

### PR DESCRIPTION
**Pull request by sashankaryal**
- Fixed a bug in saved views editor caused by https://github.com/mui/material-ui/issues/10341.
- The editor doesn't work without `disablePortal` prop. On e2e side, because of this change, MUI backdrop intercepts mouse clicks and keypresses, and tests fail. The broken tests in saved views spec have been annotated with `.fixme()` until we we have a fix.
- Update e2e dependencies, run linter, fix type issues, etc.

### CODE REVIEW

**Comment by benjaminpkane** [comment]
Currently having difficulty with my local playwright environment. It'd be a shame to disable all these tests. I personally haven't been able to reproduce the call stack issue

**Comment by benjaminpkane** [comment]
Happy to defer to @manivoxel51. But maybe we just disable/fix the `[saved views › searching through saved views works]` spec?

**Comment by manivoxel51** [comment]
@sashankaryal I'll pull and test around tomorrow. haven't had a chance to dive deep. thanks for raising this 🙌

**Review by benjaminpkane — APPROVED** [review]

**Review by manivoxel51 — APPROVED** [review]
lgtm too! 🍨 

pulled and tested around

**Pull request merged**
