### PR TITLE
Multiple DB session support

### LINKED ISSUE #64: Add support for more than one fiftyone session on a machine
This is blocked by mongodb always using the same port (`27017`).

### PR DESCRIPTION
**Pull request by lethosor**
## What changes are proposed in this pull request?

This currently adds support for multiple database sessions (which partially addresses #64). This addresses the "mongodb exited with code 64" message mentioned in #204, among other places.

### To do

- [x] Address port conflicts - the easiest way is to bind to port 0 for both the DB and server, which will grab any unused port, but I'm unsure what consequences this will have for port forwarding, etc.. At the very least, there are a lot of references to port 5151 in the docs that will need to be updated or removed. I'm not sure if people actually rely on knowing the port number at the moment (@benjaminpkane any thoughts on this?).
  * Update: done for just the DB for now
- [x] Add automated tests for some of the workflows I've been testing locally
- [x] Test on Windows
- [ ] Test on macOS
- [x] Test on multi-user systems
- [ ] Docs
  * Not really necessary for now, other than release notes

## How is this patch tested? If it is not, in a single sentence please explain why.

Some unit tests, some more complicated manual testing

### Is this a user-facing change?

-   [ ] No. You can skip the rest of this section.
-   [x] Yes. Give a description of this change to be included in the release
        notes for FiftyOne users.

Support for multiple fiftyone sessions on the same machine

### What areas of FiftyOne does this PR affect?

-   [ ] `App`: FiftyOne application changes
-   [ ] `Build`: Build and test infrastructure changes
-   [x] `Core`: Core `fiftyone` Python library changes
-   [ ] `Documentation`: FiftyOne documentation changes
-   [ ] `Other`

### Should this PR be mentioned in the release notes? If so, please choose on category:

-   [ ] `breaking-change` - The PR will be mentioned in the "Breaking Changes"
        section
-   [x] `feature` - A new user-facing feature worth mentioning in the release
        notes
-   [x] `bug-fix` - A user-facing bug fix worth mentioning in the release notes
-   [ ] `documentation` - A user-facing documentation change worth mentioning
        in the release notes

### CODE REVIEW

**Comment by benjaminpkane** [comment]
Regarding ports, my view of the ideal functionality is:

* Mongodb always binds to port 0 (dynamic port configuration)
* The server port defaults to 5151, and falls back to dynamic port configuration if it is taken
* The user has the option to override the default 5151 server port, and explicitly define their own
  * if that port is taken, an error is raised

But, noting the considerations, that might be a lot to have ready for tomorrow. Maybe start with mongodb port binding?

**Comment by lethosor** [comment]
> The server port defaults to 5151, and falls back to dynamic port configuration if it is taken

The problem with this is that `ServerService` currently assumes that a listening server on port 5151 (that responds to `/fiftyone`) is a remote server, and deliberately doesn't start a new one. We will likely need to refactor the session logic to actually keep track of whether a session is connecting to a remote server. (#208 is a similar issue regarding the DB service.)

There is a *lot* of work that needs to be done across fiftyone to make everything work properly, for (currently) not a lot of users that need it. I will work on database port handling, but I think that's all that can feasibly be done for 0.5.2.

**Comment by benjaminpkane** [comment]
I agree with all of the above. That point was not fully thought through, and there isn't a huge demand from users atm.

**Comment by lethosor** [comment]
(I think the point I quoted makes sense, although it's a bit harder than always using a random port - it would just require more refactoring to get it working than I initially thought.)

**Pull request merged**
