### PR TITLE
Expandable plots

### LINKED ISSUE #546: [FR] Hide App scroll bars when not scrolling
The scroll bar in image grid mode is now always visible, whereas previously it would only appear when scrolling (on Mac).

Scroll bar behavior/look-and-feel is somewhat OS dependent, but the convention on the web is to hide scroll bars when not scrolling for Mac users. I think we should provide the same behavior for users of our App. (IE revert to previous behavior from earlier App versions)

### PR DESCRIPTION
**Pull request by benjaminpkane**
## What changes are proposed in this pull request?

Per official design documents, encapsulate plots within an expandable window in the main dataset page.

In order to simplify things, sticky nav behavior was dropped. Resolves #546.

Screenshot from 2020-11-03 16-16-02
Screenshot from 2020-11-03 16-15-57

## How is this patch tested? If it is not, please explain why.

Locally.

### Is this a user-facing change that should be mentioned in the release notes?

-   [ ] No. You can skip the rest of this section.
-   [x] Yes. Give a description of this change to be included in the release
        notes for FiftyOne users.

Plots are now held within an expandable window of the main dataset page as opposed to their own pages.
### What areas of FiftyOne does this PR affect?

-   [x] App: FiftyOne application changes
-   [ ] Build: Build and test infrastructure changes
-   [ ] Core: Core `fiftyone` Python library changes
-   [ ] Documentation: FiftyOne documentation changes
-   [ ] Other

### CODE REVIEW

**Comment by benjaminpkane** [comment]
I am happy to reintroduce sticky behavior, but I think it should be removed for now, as it relied on a framework that should be removed and was somewhat buggy.

Also, happy to improve on the scrollbars and make them even more similar to Mac OS, perhaps with this [library](Shttps://kingsora.github.io/OverlayScrollbars/#!overview). I suppose this work does not entirely resolve #546.

**Review by brimoor — COMMENTED** [review]
It's so cool to be able to view graphs and the sample grid at the same time!! 👏 👏 

A couple reactions after trying this out myself:

- Am I crazy, or does it make more sense for the carets in `Show ^` and `Hide v` to be swapped? IE `Show v` and `Hide ^` where the caret points in the direction where things "go". This might be a natural vs reverse scrolling thing...

- What do you think about adding a toggle for maximizing the graphs section, if desired? Maybe once the graph section is opened, there's a maximize icon similar to Player51 that allows you to get into/out of that state. It's great to be able to see both the graphs and the grid, but sometimes you do want to see more graphs. Related to this, perhaps it makes sense to add the `Samples` tab back at the top as a shortcut back to "minimized graph" state?

- How about allowing the user to grab the bottom of the graph section and drag it to readjust the size of the graphs section? I found myself expecting to be able to do this. Note that this is complementary-but-not-exclusive with the one-click way to maximize from the previous bullet point; both have value

It's great to see graphs more visible! The initial orange color of the `Show` button is begging to be clicked!

**Comment by benjaminpkane** [comment]
I addressed the first point.

I like the idea of resizing and maximizing, but I think it will take a small handful of hours to get both them right. Focusing on `websockets` right now. `resize` is a simple CSS property, but it only allows resizing from the bottom right corner.

Adding back the `samples` button I am less sure about. It would a mean a button of the same kind, does a different things. If maximizing and resizing are done right, I don't think the `samples` button is necessary. The `Hide` button can be used to close things out completely, even when in a maximized state.

**Comment by brimoor** [comment]
Okay I agree with your comments on not needing the `Samples` tab.

I think the real motivation for my comment is that I find it a bit weird that those "tabs" are visible when the graph section is collapsed. Typically in a "tabbed" layout there is always a tab corresponding to the state that you're currently in. But that's not true now.

**Comment by brimoor** [comment]
I do see maximizing and resizing as MVP additions to expandable plots though.

Comment for discussion: I usually set my FiftyOne App window to full height so that I can see as many samples as possible in the sample grid. With plots expanded, that cuts down on the number of images that I can see. What if it were possible to open  the plot component side-by-side (to the right) of the sample grid, rather than top-bottom? Then you could see a full grid of samples and multiple plots (or, in the future, plots that require more vertical space) at the same time? 😄

**Comment by brimoor** [comment]
A couple other comments related to the current implementation of plots (if the amount of work to address this isn't appropriate for the remaining lifespan of the current plots, then please take that into account):

- When a histogram has only a single bar, it is squashed horizontally and not readable
- x-tick labels beyond a pretty modest length are cut-off and not readable

**Comment by benjaminpkane** [comment]
My interpretation of maximizing and resizing have been added. Things feel pretty slick now.

I addressed bar size widths for smaller graphs I believe, and text overflow some but that won't fully be resolved until the plotting overhaul occurs.

I like the idea of side-by-side. I would hope that the FiftyOne UI begins to feel more modular as things progress. Happy to take this discussion offline. I'm not sure what the requirements should be for side-by-side as things stand in the App right now. A quick implementation might get messy.

**Comment by brimoor** [comment]
Looking good! Here's a couple observations I made while using the latest version of the tool:

- When the plots component is expanded, it causes the bottom part of the image grid and display options bar to extend beyond the App, but doesn't allow for scrolling. So, if you, for example, create a view that fits exactly on one page of the sample grid with the plots component collapsed, then when you expand the labels section, you'll never be able to see the samples that have extended beyond the bottom of the App. Ideally, the grid and the display options menu would be responsive and allow you to scroll to their bottom regardless of the state of the plots component

- It looks like the horizontal spacing between the bars on the scalar-valued histograms graphs has increased compared to prod. I think it would be better for them to be more compact so that more bars could be seen at a time. For that matter, the bars for categorical graphs could also be made closer together I think (as close as possible w/o the tick labels overlapping)

prod scalar histograms for `fiftyone quickstart`
Screen Shot 2020-11-12 at 1 53 30 PM

dev scalar histograms for `fiftyone quickstart`:
Screen Shot 2020-11-12 at 1 54 13 PM

**Comment by brimoor** [comment]
Regarding the maximizing/resizing functionality, what do you think about:

- Can you add a visual indicator to the bottom of the plot component that indicates that the component can be resized? As is, I'm concerned that users will not realize that it is adjustable (which may lead to them being unhappy relative to the current behavior of the App, where, although they can't see samples at the same time, they will at least be able to see as much graph as possible. We don't want to update into a middle ground where you can't quite see enough of either section, and think that there's nothing to be done about it). I'm thinking something like this:

```
----------------[::::]----------------
```

inspired by Claire's design for changing the order of view bar stages:

Screen Shot 2020-11-12 at 2 00 31 PM

- Moving the maximize/minimize icon to the upper right of the plot component (say, immediately to the left of the show/hide toggle)? This would be consistent with how this component is positioned on player51, would position all show/hide-related functionality in one place in the App, and it would avoid the maximize/minimize icon from overlapping with the tick labels on graphs. See below for screenshots

maximize/minimize positioning in expanded sample view:
Screen Shot 2020-11-12 at 1 36 26 PM

current location of maximize/minimize icon is hard to notice in the bottom right, and it overlaps with tick labels:
Screen Shot 2020-11-12 at 1 37 46 PM

**Comment by benjaminpkane** [comment]
> * When the plots component is expanded, it causes the bottom part of the image grid and display options bar to extend beyond the App, but doesn't allow for scrolling. So, if you, for example, create a view that fits exactly on one page of the sample grid with the plots component collapsed, then when you expand the labels section, you'll never be able to see the samples that have extended beyond the bottom of the App. Ideally, the grid and the display options menu would be responsive and allow you to scroll to their bottom regardless of the state of the plots component

Resolved in #681

**Comment by benjaminpkane** [comment]
All other comments addressed.
Screenshot from 2020-11-12 14-57-52

**Review by brimoor — APPROVED** [review]
Awesome! Thanks for entertaining my design suggestions. And now... one last thing: can you hide the maximize plots icon when the plots component is in its hidden state? It feels out of place because you can't see what you're expanding 😄 

Similar to how you first have to open the sample modal, and then you can click maximize.

**Comment by benjaminpkane** [comment]
> Similar to how you first have to open the sample modal, and then you can click maximize.

:unamused:

**Pull request merged**
