### PR TITLE
initial saved spaces ui

### PR DESCRIPTION
**Pull request by imanjra**
## What changes are proposed in this pull request?

initial saved spaces UI (part of a saved spaces feature)

## How is this patch tested? If it is not, please explain why.

By enabling the feature flag by setting the local storage key `savedSpaces` to `true`

Preview

https://github.com/voxel51/fiftyone/assets/25350704/863d9520-3caf-4bbd-b888-fa3c81c4d323

### Is this a user-facing change that should be mentioned in the release notes?

-   [x] No. You can skip the rest of this section.
-   [ ] Yes. Give a description of this change to be included in the release
        notes for FiftyOne users.

(Details in 1-2 sentences. You can just refer to another PR with a description
if this PR is part of a larger change.)

### What areas of FiftyOne does this PR affect?

-   [x] App: FiftyOne application changes
-   [ ] Build: Build and test infrastructure changes
-   [ ] Core: Core `fiftyone` Python library changes
-   [ ] Documentation: FiftyOne documentation changes
-   [ ] Other

## Summary by CodeRabbit

- **New Features**
	- Introduced a new `Dialog` component for enhanced dialog customization and interaction.
	- Added a `WorkspaceEditor` component for editing workspace settings such as name, description, and color.
	- Implemented a `SavedSpaces` component to manage and edit a list of saved workspaces, including search and filter capabilities.
	- Launched a `SavedSpace` component representing individual saved workspace items with options for detailed editing.
	- Developed a custom hook `useSavedSpaces` for managing saved workspace interactions in the application.

- **Refactor**
	- Updated `session.ts` to restructure properties within the `SPACES_DEFAULT` object for better clarity and organization.

- **Chores**
	- Enhanced state management with new atoms for workspace editing capabilities and integrating existing functionality.

### CODE REVIEW

**Comment by imanjra** [comment]
Converting to draft. Based on offline discussion, design needs some more work.

**Review by benjaminpkane — COMMENTED** [review]
Feature works great! Integrating this with #4235 was super easy.

For completeness, I believe some permission handling might need to be added similar to saved views, .i.e. usage of `canEditSavedViews` atom? I just pushed an equivalent `canEditWorkspaces` atom. Can discuss more offline

Also, wondering if there is any opportunity to reuse the React components from Saved Views?

**Comment by imanjra** [comment]
> Also, wondering if there is any opportunity to reuse the React components from Saved Views?

Yah, I do want to consolidate and share some more components (some are shared already) with saved view. However, it will require some refactor for saved view impl. I will do the refactor/cleanup in a follow-up PR instead.

**Comment by imanjra** [comment]
> For completeness, I believe some permission handling might need to be added similar to saved views, .i.e. usage of canEditSavedViews atom? I just pushed an equivalent canEditWorkspaces atom. Can discuss more offline

Nice! Thanks! I'll integrate perms before merge

**Review by benjaminpkane — APPROVED** [review]
LGTM 🚀

**Pull request merged**
