### PR TITLE
[Proposal] Remove unused e2e

### PR DESCRIPTION
**Pull request by benjaminpkane**
`./e2e-pw` has become the actively developed end to end project and has been integrated into ci. There **are** some tests that contain valuable coverage in the old `./e2e` project, in particular the dynamic group tests. But because the project is no longer developed, we might as well remove it. The project is still in the repository history if it needs to be referred to

### CODE REVIEW

**Comment by findtopher** [comment]
For context - we're getting pings on vulnerable packages in this configuration that can't be remediated (packages that are no longer being maintained that have dependencies that need to be upgraded)

Removing this unused directory structure would be very helpful in preparing for the ISO audit.

**Comment by benjaminpkane** [comment]
@sashankaryal Is there any other cleanup that should be done? Old documentation references?

**Review by findtopher — APPROVED** [review]
if @sashankaryal says it's good, then it's good!

**Review by sashankaryal — APPROVED** [review]
lgtm

**Pull request merged**
