### PR TITLE
Initial frontend video support

### PR DESCRIPTION
**Pull request by lethosor**
## What changes are proposed in this pull request?

This sets up player51 to play videos properly - they are now treated as videos, not images, and they are sized correctly in both the grid and modal views.

Note that labels are not yet handled (needs core work), and seeking does not work (likely needs server-side support).

## How is this patch tested? If it is not, please explain why.

Locally - took a 100-sample image dataset and replaced two samples with videos.

### CODE REVIEW

**Comment by benjaminpkane** [comment]
This is pretty cool to see in action! My videos don't have any height in the grid right now. Is that ever happening for you?

Workflow:
```
import fiftyone as fo

dataset = fo.Dataset()
sample = fo.Sample(filepath="/path/to/video.mp4")
dataset.add_sample(sample)
session = fo.Session(dataset=dataset)
```

**Comment by lethosor** [comment]
Good catch - I saw that when videos were alone in a row. It's probably still an issue (my most recent tests have just been with the dataset described above)

**Review by benjaminpkane — APPROVED** [review]
OK, feel free to merge. Plenty of work done in here already.

**Comment by benjaminpkane** [comment]
This work is now a part of #559. When closes, I can delete the `video` branch.

**Comment by lethosor** [comment]
Fixed the issue with video-only rows having 0 height: https://github.com/voxel51/fiftyone/pull/542/commits/b240448c2672ac4992d926a192bc6d2639878470?w=1

I'm not sure what you mean about #559 - I only see 3 commits there.

**Comment by benjaminpkane** [comment]
So I did things manually. The commits aren't there. Perhaps there is a way to get these commits into the commit history, I just thought what I did would be quicker.

I cherry picked https://github.com/voxel51/fiftyone/pull/542/commits/b240448c2672ac4992d926a192bc6d2639878470 into #559 (`video-support`). Currently, I'm having issues with the event handle in `Player51`  on #559 using the quickstart, but we can talk about it tomorrow.
https://github.com/voxel51/fiftyone/blob/66ab219c0b6fdfdceda5ede9513c7941284d64ee/electron/app/components/Player51.tsx#L151

**Comment by lethosor** [comment]
Got it. Did you remember to update submodules and rebuild player51? Those would be my guesses.

**Pull request merged**
