### PR TITLE
Video labels

### PR DESCRIPTION
**Pull request by benjaminpkane**
WIP but ready to be used in other work.

```py
import fiftyone as fo
import eta.core.utils as etau

samples = []
for path_to_a_video in etau.list_files("/path/to/dir/of/videos", abs_paths=True):
    s = fo.Sample(filepath=path_to_a_video)
    s[0] = fo.FrameSample() # for each frame, create a `fo.FrameSample`, to be simplified/hidden from public API
    s[0]["cls"] = fo.Classification(label="dog") # add labels to the frame like you would to an image sample
    samples.append(s)

d = fo.Dataset()
d.add_samples(samples)
```

This API is different than what was discussed. Right now, video samples have a reserved `frames` attribute which maps to a collection of `FrameSample`s. Allowing for arbitrary fields of video labels would have led to over-engineering based on our current use of MongoEngine (managing a variable number of collections, and so on).

I intend on merging later today once more things are fleshed out and documented.  Feel free to review the code, but things are still very much in motion. The core idea is that we leverage `Sample` and our `NoDataset`/`Dataset` concepts for video frames.

I recommend merging this branch into your branch to to start working with things.

### CODE REVIEW

**Comment by lethosor** [comment]
Thanks for the fixes!

Tested on https://github.com/voxel51/fiftyone/pull/564/commits/90f801f3ac72e42206d3d4ac59ec5827af66ce31. I'm running into a couple JSON encoding issues:
1. I have a numpy array field on a sample (`custom_raw_data=np.random.randn(3, 3)`) which was previously ignored, and is now somehow getting turned into a Uint8Array object when sent to the frontend, which leads to the following exception in the grid view:
    ```
    recoil.js:2588 Uncaught TypeError: Cannot freeze array buffer views with elements
        at Function.freeze (<anonymous>)
        at deepFreezeValue (recoil.js:2588)
    ...
    The above error occurred in the <Samples> component:
        in Samples (at SamplesContainer.tsx:189)
        in div (created by GridColumn)
        in GridColumn (at SamplesContainer.tsx:188)
    ...
    ```
    The same thing happens with `np.array([1,2,3])`, so it's not shape-dependent.
    This doesn't happen on develop due to #563 being merged there, but this particular error wasn't happening before (or if it was, it was masked by #556)

2. The `_id` field appears to be serialized as `{"$oid": id}` again, leading to this error in the expanded sample view (and likely other places, since this is being passed through the grid view too):
    ```
    Uncaught Error: Objects are not valid as a React child (found: object with keys {$oid}). If you meant to render a collection of children, use an array instead.
        in span (at SampleModal.tsx:198)
    ```

Other things:

3. Using `Dataset.from_images_dir()` or `Dataset.from_dir()` gives the following error:
    ```
      File ".../fiftyone/core/dataset.py", line 1342, in from_images_dir
        dataset.add_images_dir(images_dir, tags=tags, recursive=recursive)
      File ".../fiftyone/core/dataset.py", line 1070, in add_images_dir
        return self.add_images(image_paths, sample_parser, tags=tags)
      File ".../fiftyone/core/dataset.py", line 1007, in add_images
        return foud.add_images(self, samples, sample_parser, tags=tags)
      File ".../fiftyone/utils/data/parsers.py", line 75, in add_images
        _samples, num_samples=num_samples, expand_schema=False
      File ".../fiftyone/core/dataset.py", line 618, in add_samples
        self.media_type = samples[0].media_type
    TypeError: 'map' object is not subscriptable
    ```

**Comment by benjaminpkane** [comment]
Thanks! Working through the above now.

**Comment by benjaminpkane** [comment]
I think these are all addressed. I haven't tested `from_images_dir()`, etc. directly but will circle back to it.

**Comment by lethosor** [comment]
Confirmed, including `from_images_dir`/`from_dir`

**Comment by benjaminpkane** [comment]
This is functional App side and Core side. Testing has been limited, though. Merging into the feature branch, #559.

Changes requested today in #559 will be addressed today.

**Pull request merged**
