### PR TITLE
Added an optional argument map_type so that a user can choose between

### PR DESCRIPTION
**Pull request by xubojohndeere**
## What changes are proposed in this pull request?

Add an optional argument named `map_type` to `location_scatterplot()` so that a user can choose between 
  `roadmap` and `satellite`. Currently Fiftyone only supports `roadmap` (carto-positron).

The `satellite` option uses a public USGS imagery map with no token needed (see https://plotly.com/python/mapbox-layers/).

The `map_type` option is added through the following changes:

1. Add a method `_set_map_type_to_figure()` to set `mapbox_style` based on `map_type`.
2. Remove `mapbox_style="carto-positron"`  from `_plot_scatter_mapbox_numeric()`, `_plot_scatter_mapbox_density()`, `_plot_scatter_mapbox_categorical()`, and `_plot_scatter_mapbox_categorical_single_trace()`.
3. Call `_set_map_type_to_figure()` after the invoke of the `_plot_scatter_mapbox_*` methods.

The default value of `map_type` is `roadmap`. If a value other than `roadmap` and `satellite` is supplied by a user, `map_type` is defaulted to `roadmap` and a warning is displayed.

## How is this patch tested? If it is not, please explain why.

Tested `_plot_scatter_mapbox_numeric()`, `_plot_scatter_mapbox_density()`, `_plot_scatter_mapbox_categorical()`, and `_plot_scatter_mapbox_categorical_single_trace()` using the scripts provided in https://docs.voxel51.com/user_guide/plots.html#id7 and by Allen Lee.

### Is this a user-facing change that should be mentioned in the release notes?

Not sure.
-   [ ] No. You can skip the rest of this section.
-   [ ] Yes. Give a description of this change to be included in the release
        notes for FiftyOne users.

(Details in 1-2 sentences. You can just refer to another PR with a description
if this PR is part of a larger change.)

### What areas of FiftyOne does this PR affect?

-   [ ] App: FiftyOne application changes
-   [ ] Build: Build and test infrastructure changes
-   [x] Core: Core `fiftyone` Python library changes
-   [ ] Documentation: FiftyOne documentation changes
-   [ ] Other

### CODE REVIEW

**Comment by xubojohndeere** [comment]
When you use `map_type='satellite'`, you may see white blank blocks in some water bodies at certain zoom levels. This should be an artifact of USGS imagery.

**Comment by xubojohndeere** [comment]
That's great! Thanks Ben.

Bo



Public

________________________________

**Comment by xubojohndeere** [comment]
Hi @benjaminpkane, it looks like there are some build tests that fail. Do I need to worry about them?

**Comment by xubojohndeere** [comment]
> > Hi @benjaminpkane, it looks like there are some build tests that fail. Do I need to worry about them?
> 
> They are unrelated. Not to worry. But a rebase may need to happen. I will follow up later today!

Sounds good. Please let me know how I shall proceed with rebasing if needed.

**Comment by xubojohndeere** [comment]
> Disregard! We can merge without a rebase 🚀

Wonderful! Thanks Ben for promptly processing the PR. 

When will the change be available to "pip install"? No intention to push. Just wanted to get a rough idea when can people get the change from pip install.

**Comment by benjaminpkane** [comment]
> > Disregard! We can merge without a rebase 🚀
> 
> Wonderful! Thanks Ben for promptly processing the PR.
> 
> When will the change be available to "pip install"? No intention to push. Just wanted to get a rough idea when can people get the change from pip install.

It will unfortunately miss the next release. It won't be long, though. I will provide a date when I have more information 👍

**Pull request merged**
