### PR TITLE
Adds App error page

### PR DESCRIPTION
**Pull request by benjaminpkane**
## What changes are proposed in this pull request?

An error page that is shown when a rendering error occurs. It will not catch event errors, promise errors, etc. (automatically).

It does prevent (or replace) the white screen of death.

Screenshot from 2020-08-24 12-11-43

There is a lot more that can be added to App error handling, but this PR gets the ball rolling.

## How is this patch tested? If it is not, in a single sentence please explain why.

Not tested. The App still needs a test framework.

### Is this a user-facing change?

-   [ ] No. You can skip the rest of this section.
-   [x] Yes. Give a description of this change to be included in the release
        notes for FiftyOne users.

An App error page has been added.

### What areas of FiftyOne does this PR affect?

-   [x] `App`: FiftyOne application changes
-   [ ] `Build`: Build and test infrastructure changes
-   [ ] `Core`: Core `fiftyone` Python library changes
-   [ ] `Documentation`: FiftyOne documentation changes
-   [ ] `Other`

### Should this PR be mentioned in the release notes? If so, please choose on category:

-   [ ] `breaking-change` - The PR will be mentioned in the "Breaking Changes"
        section
-   [x] `feature` - A new user-facing feature worth mentioning in the release
        notes
-   [ ] `bug-fix` - A user-facing bug fix worth mentioning in the release notes
-   [ ] `documentation` - A user-facing documentation change worth mentioning
        in the release notes

### CODE REVIEW

**Comment by lethosor** [comment]
Agreed with the wording changes.

If the frontend error is caused by a bad view, `session.refresh()` wouldn't fix it - it would just restore the current (bad) view (are there things that it *would* fix?). My interpretation of `session.view = ...` is "reassign session.view to whatever it was before you saw this page". That isn't particularly useful if users *didn't* cause this error with a bad view, so it should be clear that doing so is optional.

Maybe something like this?

> Oops! Something went wrong.
>
> If you just changed your view, try reverting your changes:
> ```
> session.view = old_view
> ```
> 
> [Reload the app] to try again

Side note: if the viewbar is a common source of errors, we can also have an error boundary just around that, with a more informative view-specific error message, but I think that's overkill for now.

**Comment by brimoor** [comment]
Good point on view bar error boundaries. I definitely agree that there should be an error boundary around reading from the dataset/view, and if a problem occurs with that, the error should be displayed to user in the App, similar to how it would show in the Python shell.

I have created invalid views myself, for example last night by typing `session.view = dataset.sort_by("faster_cnn")` when the field is actually `faster_rcnn`. It took me awhile to track this down, and the instructions here wouldn't particularly help, because I thought I had constructed a valid view. Worse, sometimes `print(view)` will work, while `for sample in view` will not, as the error is only raised in particular cases.

For that reason, how about just restricting the instructions here to simply refreshing the app, and then handling dataset/view error boundaries separately?

**Comment by brimoor** [comment]
Comment on design: how about spicing up the error page by adding some pixels? How about adding this image with 100% width as a header:

pixels_top

and this image @ 100% width as a footer?

pixels_bottom

May want to crop as necessary

**Comment by benjaminpkane** [comment]
Thanks for the discussion here! I'll change the copy, and try adding background / improving styles.

The ViewBar will likely be a common source of errors, but adding another error boundary might not happen before tomorrow. More pressing matters, etc.

**Comment by benjaminpkane** [comment]
> Comment on design: how about spicing up the error page by adding some pixels? How about adding this image with 100% width as a header:
> 
> pixels_top
> 
> and this image @ 100% width as a footer?
> 
> pixels_bottom
> 
> May want to crop as necessary.
> 
> They should have transparent backgrounds

This isn't straightforward from a layout perspective. I don't think it will look good in all cases without some headache.

Ready for review. I think what is here is much better than nothing.

**Pull request merged**
