### PR TITLE
EmbeddedDocument field with a label type (ex: ground_truth of type Detections) should not have other typed fields of type primitives.

### PR DESCRIPTION
**Pull request by manivoxel51**
## What changes are proposed in this pull request?

An embedded document field with a label list type (ex: ground_truth of type Detections) should not have other typed fields (ground_truth.annotator for example) of type primitives.

Note this can be extended to more use cases but a good safeguard for now.

```
import fiftyone as fo

dataset = fo.load_datase("quickstart")
sample = dataset.first()
sample["ground_truth.annotator"] = "foo"
sample.save()

dataset.add_dynamic_sample_fields()
dataset.save()

// launch app
```

before fix

Screen Shot 2023-09-26 at 2 38 10 PM

after fix

Screen Shot 2023-09-26 at 2 08 50 PM

## How is this patch tested? If it is not, please explain why.

(Details)

### Is this a user-facing change that should be mentioned in the release notes?

-   [ ] No. You can skip the rest of this section.
-   [ ] Yes. Give a description of this change to be included in the release
        notes for FiftyOne users.

(Details in 1-2 sentences. You can just refer to another PR with a description
if this PR is part of a larger change.)

### What areas of FiftyOne does this PR affect?

-   [ ] App: FiftyOne application changes
-   [ ] Build: Build and test infrastructure changes
-   [ ] Core: Core `fiftyone` Python library changes
-   [ ] Documentation: FiftyOne documentation changes
-   [ ] Other

### CODE REVIEW

**Comment by lkaneda** [comment]
in your screenshot after fix, the field annotator got moved to live at the Detection level. did you change your code to make that happen? or are you showing it nested incorrectly?

**Comment by manivoxel51** [comment]
> in your screenshot after fix, the field annotator got moved to live at the Detection level. did you change your code to make that happen? or are you showing it nested incorrectly?

good point! the two shouldn't really be compared. I added a nested annotator to detections field (in the second screenshare) which is ok to show I believe. The fix is to remove the annotator as in the first screenshare

**Comment by lkaneda** [comment]
By showing it though, doesn't it imply that it can be visualized like the other fields (and that it would appear in the side bar). This is how I understand it.

**Comment by manivoxel51** [comment]
> By showing it though, doesn't it imply that it can be visualized like the other fields (and that it would appear in the side bar). This is how I understand it.

right! the annotator within `ground_truth.detections` is showing in the sidebar and in field visibility no?
Screen Shot 2023-09-26 at 4 06 43 PM

**Comment by lkaneda** [comment]
sweet - thanks for clarifying. lgtm!

**Review by benjaminpkane — CHANGES_REQUESTED** [review]
I made a tweak to this because I think we only need to include the list field itself. This ensures all fields are excluded, includings list fields, dict fields, etc.

For example
```py
dataset = foz.load_zoo_dataset("quickstart")
first = dataset.first()
first.detections["other_list"] = ["data"]
first.save()
```
We want `other_list` to be omitted from schema settings, which should be handled now.

I am seeing an issue with frame fields (see screenshot). The nested detection fields are missing `detections.detections` in the path. Is there an easy fix for that?
Screenshot 2023-09-28 at 9 04 12 AM

**Comment by manivoxel51** [comment]
> I made a tweak to this because I think we only need to include the list field itself. This ensures all fields are excluded, includings list fields, dict fields, etc.
> 
> For example
> 
> ```python
> dataset = foz.load_zoo_dataset("quickstart")
> first = dataset.first()
> first.detections["other_list"] = ["data"]
> first.save()
> ```
> 
> We want `other_list` to be omitted from schema settings, which should be handled now.
> 
> I am seeing an issue with frame fields (see screenshot). The nested detection fields are missing `detections.detections` in the path. Is there an easy fix for that? Screenshot 2023-09-28 at 9 04 12 AM

thanks for testing Ben! I'll address your comment out later today

**Review by benjaminpkane — APPROVED** [review]
LGTM, last comment is unrelated

**Pull request merged**
