### PR TITLE
Add Databricks notebook visualization

### LINKED ISSUE #1339: [FR] Support for visualization in Databricks
### Proposal Summary

I'd like to visualize the FiftyOne app in Databricks notebooks.

### Motivation

-   What is the use case for this feature? Visualization
-   Why is this use case valuable to support for FiftyOne users in general? Availability on more plattforms
-   Why is this use case valuable to support for your project(s) or
    organization? Databricks is the plattform my org uses
-   Why is it currently difficult to achieve this use case? (please be as
    specific as possible about why related FiftyOne features and components are
    insufficient) For an implementation like Colab the proxy might be an issue. I'm currently trying to figure that out.

### What areas of FiftyOne does this feature affect?

-   [ ] App: FiftyOne application
-   [x] Core: Core `fiftyone` Python library
-   [ ] Server: FiftyOne server

### Details

Databricks notebooks are, just like Colab, a proprietary implementation of notebooks that uses a custom python shell based on IPythons InteractiveShell and exposes a `display` and `displayHTML` method.
But `display` is pretty much limited to plots or dataframes.

### Willingness to contribute

The FiftyOne Community encourages new feature contributions. Would you or
another member of your organization be willing to contribute an implementation
of this feature?

-   [ ] Yes. I can contribute this feature independently.
-   [x] Yes. I would be willing to contribute this feature with guidance from
        the FiftyOne community.
-   [ ] No. I cannot contribute this feature at this time.

### PR DESCRIPTION
**Pull request by twsl**
## What changes are proposed in this pull request?

Fix #1339

## How is this patch tested? If it is not, please explain why.

Executed the code `_display_databricks` inside a databricks notebook cell to validate that it shows the website inside an iframe.
Haven't validated yet, that the session connects properly.

### Is this a user-facing change that should be mentioned in the release notes?

-   [ ] No. You can skip the rest of this section.
-   [x] Yes. Give a description of this change to be included in the release
        notes for FiftyOne users.

Add Databricks notebook visualization

### What areas of FiftyOne does this PR affect?

-   [ ] App: FiftyOne application changes
-   [ ] Build: Build and test infrastructure changes
-   [x] Core: Core `fiftyone` Python library changes
-   [ ] Documentation: FiftyOne documentation changes
-   [ ] Other

### CODE REVIEW

**Comment by benjaminpkane** [comment]
HI @twsl. I'll have to make some adjustments [here](https://github.com/voxel51/fiftyone/blob/develop/app/packages/app/src/shared/connection.ts) so the App respects the full proxy URL when creating routes.

**Comment by twsl** [comment]
@benjaminpkane for me it's working just fine and I can see the application inside the iframe.
I used the the installation commands you provided and then executed
```python
import fiftyone as fo
import fiftyone.zoo as foz

dataset = foz.load_zoo_dataset("quickstart")
session = fo.launch_app(dataset)
```
Tested in firefox and edge. But I do get some exception as soon as I want Filter the prediction labels:
```
Traceback (most recent call last):
 File "main.py", line 300, in wrapper
 result = await func(self, *args, **kwargs)
 File "main.py", line 402, in post
 await handle(caller, **message)
 File "main.py", line 1081, in on_count_values
 _write_message(message, app=True, only=self)
 File "main.py", line 1212, in _write_message
 only.write_message(message)
TypeError: write_message() missing 1 required positional argument: 'message'
```

The problem with the `Session._capture()` method and the visualization in general is, that I cannot get `IPython.display.DisplayHandle` to work properly, which makes updating quite hard.

**Comment by twsl** [comment]
Some responses indicating additional problems regardless of databricks DisplayHandle issue

push polling
```
{"type": "notification", "kind": "Server Error", "message": "An exception has been raised by the server. Your session has been reverted to its previous state.", "session_items": ["Traceback (most recent call last):\n  File \"main.py\", line 297, in wrapper\n    async def wrapper(self, *args, **kwargs):\n  File \"main.py\", line 399, in post\n    message[\"ignore_polling_client\"] = client\n  File \"main.py\", line 617, in on_update\n    Args:\n  File \"/databricks/python/lib/python3.8/site-packages/fiftyone/core/state.py\", line 124, in from_dict\n  File \"/databricks/python/lib/python3.8/site-packages/fiftyone/core/dataset.py\", line 96, in load_dataset\n    Returns:\n  File \"/databricks/python/lib/python3.8/site-packages/fiftyone/core/singletons.py\", line 33, in __call__\n    instance.__init__(name=name, _create=_create, *args, **kwargs)\n  File \"/databricks/python/lib/python3.8/site-packages/fiftyone/core/dataset.py\", line 235, in __init__\n    name, persistent=persistent, **kwargs\n  File \"/databricks/python/lib/python3.8/site-packages/fiftyone/core/dataset.py\", line 4523, in _load_dataset\n  File \"/databricks/python/lib/python3.8/site-packages/mongoengine/queryset/base.py\", line 260, in get\n    result = next(queryset)\n  File \"/databricks/python/lib/python3.8/site-packages/mongoengine/queryset/base.py\", line 1595, in __next__\n    doc = self._document._from_son(\n  File \"/databricks/python/lib/python3.8/site-packages/mongoengine/base/document.py\", line 783, in _from_son\n    obj = cls(\n  File \"/databricks/python/lib/python3.8/site-packages/mongoengine/base/document.py\", line 99, in __init__\n    raise FieldDoesNotExist(msg)\nmongoengine.errors.FieldDoesNotExist: The fields \"{'last_loaded_at'}\" do not exist on the document \"DatasetDocument\"\n"], "app_items": ["A traceback has been printed to your Python shell."]}
```

pull polling
```
{"type": "notification", "kind": "Server Error", "message": "An exception has been raised by the server. Your session has been reverted to its previous state.", "session_items": ["Traceback (most recent call last):\n  File \"main.py\", line 297, in wrapper\n    async def wrapper(self, *args, **kwargs):\n  File \"main.py\", line 414, in post\n    elif event == \"deactivate\":\n  File \"/databricks/python/lib/python3.8/site-packages/fiftyone/core/state.py\", line 124, in from_dict\n  File \"/databricks/python/lib/python3.8/site-packages/fiftyone/core/dataset.py\", line 96, in load_dataset\n    Returns:\n  File \"/databricks/python/lib/python3.8/site-packages/fiftyone/core/singletons.py\", line 33, in __call__\n    instance.__init__(name=name, _create=_create, *args, **kwargs)\n  File \"/databricks/python/lib/python3.8/site-packages/fiftyone/core/dataset.py\", line 235, in __init__\n    name, persistent=persistent, **kwargs\n  File \"/databricks/python/lib/python3.8/site-packages/fiftyone/core/dataset.py\", line 4523, in _load_dataset\n  File \"/databricks/python/lib/python3.8/site-packages/mongoengine/queryset/base.py\", line 260, in get\n    result = next(queryset)\n  File \"/databricks/python/lib/python3.8/site-packages/mongoengine/queryset/base.py\", line 1595, in __next__\n    doc = self._document._from_son(\n  File \"/databricks/python/lib/python3.8/site-packages/mongoengine/base/document.py\", line 783, in _from_son\n    obj = cls(\n  File \"/databricks/python/lib/python3.8/site-packages/mongoengine/base/document.py\", line 99, in __init__\n    raise FieldDoesNotExist(msg)\nmongoengine.errors.FieldDoesNotExist: The fields \"{'last_loaded_at'}\" do not exist on the document \"DatasetDocument\"\n"], "app_items": ["A traceback has been printed to your Python shell."]}
```

**Comment by brimoor** [comment]
Hey @twsl the `last_loaded_at` error is because that's a new field that was introduced into the data model recently. You seem to have a dataset that was created with a newer version of the code that has this `last_loaded_at` field but you're trying to load it with an older version of the code that doesn't have `last_loaded_at`.

You should be able to fix this by merging the latest `develop` into your branch and rerunning the install script (`bash install.bash`) so the package version is appropriately updated. Then when you try to load any dataset it will be automatically upgraded.

[Downgrades](https://voxel51.com/docs/fiftyone/getting_started/install.html#downgrading-fiftyone) are a bit trickier but I don't think you need to be running a version < 0.14.

**Comment by twsl** [comment]
With the recent changes to [InteractivePlot.save()](https://voxel51.com/docs/fiftyone/api/fiftyone.core.plots.base.html#fiftyone.core.plots.base.InteractivePlot.save) and [ViewPlot.save()](https://voxel51.com/docs/fiftyone/api/fiftyone.core.plots.base.html#fiftyone.core.plots.base.ViewPlot), how does this impact this PR, @brimoor ?

**Comment by twsl** [comment]
Sorry for messing up the git history, took me a while to notice that installing from git via pip doesnt build the frontend

**Review by benjaminpkane — APPROVED** [review]
Thanks for the contribution @twsl! We'll work this into the next release.

**Comment by jpkoponen** [comment]
Hi!

I think this issue should be re-opened. Apparently there has been some refactoring after merging the branch and Databricks integration doesn't work anymore. One clear issue is that in [`fiftyone/core/session/notebooks.py`](https://github.com/voxel51/fiftyone/blob/develop/fiftyone/core/session/notebooks.py#L52), the function for displaying Databricks has been omitted, causing the following KeyError:

```
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<command-3730664978028155> in <cell line: 1>()
----> 1 fo.launch_app()

/local_disk0/.ephemeral_nfs/envs/pythonEnv-8418e8e6-f1ac-4344-a764-0c078670b93a/lib/python3.9/site-packages/fiftyone/core/session/session.py in launch_app(dataset, view, port, address, remote, desktop, height, auto, config)
    154     close_app()
    155 
--> 156     _session = Session(
    157         dataset=dataset,
    158         view=view,

/local_disk0/.ephemeral_nfs/envs/pythonEnv-8418e8e6-f1ac-4344-a764-0c078670b93a/lib/python3.9/site-packages/fiftyone/core/session/session.py in __init__(self, dataset, view, plots, port, address, remote, desktop, height, auto, config)
    351 
    352         if self.auto and focx.is_notebook_context():
--> 353             self.show(height=config.notebook_height)
    354 
    355         if self.remote:

/local_disk0/.ephemeral_nfs/envs/pythonEnv-8418e8e6-f1ac-4344-a764-0c078670b93a/lib/python3.9/site-packages/fiftyone/core/session/session.py in wrapper(session, *args, **kwargs)
    208             if auto_show and session.auto and focx.is_notebook_context():
    209                 session.freeze()
--> 210             result = func(session, *args, **kwargs)
    211             session._client.send_event(StateUpdate(state=session._state))
    212             if auto_show and session.auto and focx.is_notebook_context():

/local_disk0/.ephemeral_nfs/envs/pythonEnv-8418e8e6-f1ac-4344-a764-0c078670b93a/lib/python3.9/site-packages/fiftyone/core/session/session.py in show(self, height)
    888         )
    889 
--> 890         fosn.display(self._client, self._notebook_cells[uuid])
    891 
    892     def no_show(self) -> fou.SetAttributes:

/local_disk0/.ephemeral_nfs/envs/pythonEnv-8418e8e6-f1ac-4344-a764-0c078670b93a/lib/python3.9/site-packages/fiftyone/core/session/notebooks.py in display(client, cell, reactivate)
     54         focx._IPYTHON: display_ipython,
     55     }
---> 56     fn = funcs[focx._get_context()]
     57     fn(client, cell, reactivate)
     58 

KeyError: 'DATABRICKS'

```

I tried to fix the issue by re-introducing [`_display_databricks()`](https://github.com/voxel51/fiftyone/pull/1343/files#diff-20487b959e9116a305a132d18998a4341410897edc5695d53d3f7e0580f911bdR1129) from the branch and using it in [`display()`](https://github.com/voxel51/fiftyone/blob/develop/fiftyone/core/session/notebooks.py#L48). I got no errors in Notebook but there was an empty page in place of the FiftyOne UI. There were also some 404 errors in the browser Javascript console. I'm not sure if it is due to some mismatch in the FiftyOne front-end paths or connectivity issues on our Databricks side. That's where I stopped exploring because I don't have strong web dev skills and it would take too much time.

Hopefully, these findings could help someone with more expertise and time to get the Databricks integration to work.

**Pull request merged**
