### PR TITLE
Reading/writing datasets in COCO, VOC, KITTI, BDD, CVAT, and TFRecord formats

### PR DESCRIPTION
**Pull request by brimoor**
**Dataset import/export**
- adding support for importing and exporting datasets in a bunch of common formats:
  - COCO (`fiftyone.types.COCODetectionDataset`)
  - VOC (`fiftyone.types.VOCDetectionDataset`)
  - KITTI (`fiftyone.types.KITTIDetectionDataset`)
  - Image classification TFRecords (`fiftyone.types.TFImageClassificationDataset`), including support for reading/writing sharded TFRecords
  - TF Object Detection API TFRecords (`fiftyone.types.TFObjectDetectionDataset`), including support for reading/writing sharded TFRecords
  - CVAT image (`fiftyone.types.CVATImageDataset`)
  - Berkeley DeepDrive (`fiftyone.types.BDDDataset`)
- adding `Dataset.add_dir()` and `Dataset.from_dir()` methods that allow for convenient ingestion of datasets on disk in any of the above formats into FiftyOne datasets
- updating `Collections.export` to support export of samples in all available dataset types listed above
- added a `fiftyone.utils.data.convert_dataset()` method that allows for convenient conversion of datasets on disk between available formats (under the hood a non-persistent FO dataset is created as the intermediate type)

**Core data model**
- added the notion of `fiftyone.core.labels.Attribute`s, including `CategoricalAttribute`, `NumericAttribute`, `BooleanAttribute`, and `VectorAttribute` subclasses. These are used to store attributes of various types that can now be attached to `fiftyone.core.labels.Detection` instances in a new `attributes` dictionary field to represent object attributes. These were necessary to represent attributes in dataset types such as COCO, VOC, CVAT, etc

**CLI additions**
- `fiftyone convert` to convert datasets on disk between any supported formats
- `fiftyone datasets head/tail` to print the head/tail of datasets
- `fiftyone datasets stream` to stream the samples in a dataset to the terminal with a `less`-like interface. I think this is pretty cool!
- `fiftyone datasets export` to export datasets in any available format

**Dataset Zoo**
- adding full support for downloading COCO 2014/2017 via the Torch backend

**Documentation**
- splitting the dataset creation example into the three guides below. This probably breaks the doc building process, but this "tutorial" is being migrated to the user guide/recipes anyway, so it's not important
  - zoo datasets: significantly expanded description of interacting with the dataset zoo
  - datasets on disk: a new section that provides examples of importing datasets in all available formats
  - custom datasets: this describes how to add samples to a dataset in various formats using `Dataset.add_*_samples`. I'm working on updating this to remove the need for all of these `*` methods. Stay tuned on that
- added a CLI guide at `docs/cli_guide.md` that provides a raw dump of the CLI documentation. We'll likely want to upgrade this somehow to create the final "CLI documentation" in the docs

**Cleanup**
- removing the `fiftyone.experimental` package, which now contains nothing of interest (import/export was the last thing there that needed to be properly implemented in the official package)

### CODE REVIEW

**Comment by qingzi02010** [comment]
As to BDDDataset, I need to convert the initial data structure to the below data structure, right? But I have a question, the initial label.json is independent, so as <filename0>.json, if I have 50k images to covert to the dataset, do I need the 50k label.json to one labels.json? If yes, then the labels.json is huge and the process is not flexible.

<dataset_dir>/
    data/
        <filename0>.<ext>
        <filename1>.<ext>
        ...
    labels.json

**Comment by qingzi02010** [comment]
Another question with the bdd100k dataset, the inner structure between the bdd100k and BDDDataset is different. So I need to rewrite the labels.json from scratch, right?

**Comment by brimoor** [comment]
Hi @qingzi02010, I'll clarify a couple things for you that should help.

1. The [BDDDataset format](https://voxel51.com/docs/fiftyone/user_guide/dataset_creation/datasets.html#bdddataset) is a specification that we define for reading/writing arbitrary datasets (other than the official BDD100k dataset) in a format similar to how the BDD authors distributed the BDD100k dataset (more on that next). As you mention, the spec requests that datasets of this kind be arranged on disk as follows:

```
<dataset_dir>/
    data/
        <filename0>.<ext>
        <filename1>.<ext>
        ...
    labels.json
```

You raise a good point that `labels.json` may be large if there are many images. This would apply to other formats like COCO, CVAT, etc. as well, where the labels are stored in a single JSON/XML file. I'll make an issue to consider supporting sharded labels files in these cases.

2. We provide support for loading the BDD100k dataset itself via the [Dataset Zoo](https://voxel51.com/docs/fiftyone/user_guide/dataset_creation/zoo.html). You can do that as follows:

```py
import fiftyone.zoo as foz

# Parse the raw download in `source_dir`
foz.download_zoo_dataset("bdd100k", source_dir="/path/to/bdd100k-download-folder")

# Load the validation split into FiftyOne
validation = foz.load_zoo_dataset("bdd100k", split="validation")
```

Ordinarily, running the `download_zoo_dataset()` will download the source files from the web and wrangle them into a format that FiftyOne understands. In the case of BDD100k, you provide the path to the raw download of the BDD100k files that you downloaded from https://bdd-data.berkeley.edu/login.html via the `source_dir` argument, and the command will take care of wrangling the data into a known format for FiftyOne.

The description below explains what format `source_dir` should be in:

```py
zoo_dataset = foz.get_zoo_dataset("bdd100k")
print(zoo_dataset.__doc__)
```

```
The Berkeley Deep Drive (BDD) dataset is one of the largest and most
diverese video datasets for autonomous vehicles.

The BDD100k dataset contains 100,000 video clips collected from more than
50,000 rides covering New York, San Francisco Bay Area, and other regions.
The dataset contains diverse scene types such as city streets, residential
areas, and highways. Furthermore, the videos were recorded in diverse
weather conditions at different times of the day.

The videos are split into training (70K), validation (10K) and testing
(20K) sets. Each video is 40 seconds long with 720p resolution and a frame
rate of 30fps. The frame at the 10th second of each video is annotated for
image classification, detection, and segmentation tasks.

This version of the dataset contains only the 100K images extracted from
the videos as described above, together with the image classification,
detection, and segmentation labels.

**Manual download instructions**

This dataset requires you to download the source data manually. You must
register at https://bdd-data.berkeley.edu/ in order to get the link to
download the dataset.

After extracting the download, you will find contents similar to::

    bdd100k/
        labels/
            bdd100k_labels_images_train.json
            bdd100k_labels_images_val.json
        images/
            100k/
                train/
                test/
                val/
        ...

You must provide the path to the above ``bdd100k/`` folder when loading
this dataset.

Dataset size:
    7.1GB

Source:
    https://bdd-data.berkeley.edu

Args:
    source_dir (None): the path to the downloaded ``bdd100k/`` folder on
        disk
    copy_files (True): whether to move (False) or create copies (True) of
        the source files when populating the dataset directory
```

**Comment by qingzi02010** [comment]
OK. I need to process the initial image, so the fiftyone-zoo-dataset zoo is not suited for me. So I had better wait for the sharing label method, although I can not understand how to share the label.json. Thanks very much!

**Pull request merged**
